export const capitalTypes = [
  "VC",
  "PE",
  "DFI",
  "Climate finance",
  "Infrastructure",
  "Sovereign",
  "Corporate debt",
  "Grant",
  "M&A",
  "Project finance",
  "Green bond",
  "Carbon",
] as const;

export const capitalRows = [
  {
    id: "demo-1",
    investor: "EXAMPLE DFI A",
    amount: "—",
    currency: "USD",
    target: "EXAMPLE grid project",
    country: "Kenya",
    sector: "Energy",
    type: "Climate finance",
    stage: "Commitment (demo)",
    year: "2026",
  },
  {
    id: "demo-2",
    investor: "EXAMPLE FUND B",
    amount: "—",
    currency: "USD",
    target: "EXAMPLE payments company",
    country: "Nigeria",
    sector: "Fintech",
    type: "VC",
    stage: "Growth (demo)",
    year: "2026",
  },
  {
    id: "demo-3",
    investor: "EXAMPLE BANK C",
    amount: "—",
    currency: "USD",
    target: "EXAMPLE corridor rail",
    country: "Angola / DRC / Zambia",
    sector: "Infrastructure",
    type: "Project finance",
    stage: "Announced (demo)",
    year: "2025",
  },
] as const;
