export type ChangelogEntry = {
  slug: string;
  title: string;
  phase: string;
  status: "shipped" | "draft";
  lede: string;
  hrefs: string[];
};

/** Product changelog. Entries describe shipped shells — not invented metrics. */
export const changelogEntries: ChangelogEntry[] = [
  {
    slug: "phase-18",
    title: "Searches, licensing, notifications, corridor desk",
    phase: "18",
    status: "shipped",
    lede: "Saved-search templates, enterprise licence catalogue, offline notification prefs, Ethiopia and Northern Corridor graph desks.",
    hrefs: ["/searches", "/licensing", "/notifications", "/graph/northern-corridor"],
  },
  {
    slug: "phase-19",
    title: "Changelog, audit, reports, Morocco desk",
    phase: "19",
    status: "draft",
    lede: "Product changelog, empty audit log, research report shells, Morocco graph desk.",
    hrefs: ["/changelog", "/audit", "/reports", "/graph/morocco"],
  },
  {
    slug: "phase-20",
    title: "Calendar, partners, Central Corridor, API expand",
    phase: "20",
    status: "draft",
    lede: "Desk calendar, empty partner inventory, Central Corridor graph desk, /api/graph and /api/status.",
    hrefs: ["/calendar", "/partners", "/graph/central-corridor", "/developers"],
  },
  {
    slug: "phase-21",
    title: "Coverage, glossary, CI/Angola/Lobito desks",
    phase: "21",
    status: "draft",
    lede: "Honest coverage board, house glossary, Côte d’Ivoire, Angola and Lobito Corridor desks.",
    hrefs: ["/coverage", "/glossary", "/graph/cote-divoire", "/graph/lobito-corridor"],
  },
  {
    slug: "phase-22",
    title: "Onboarding, webhooks, SN/MZ, Maputo Corridor",
    phase: "22",
    status: "draft",
    lede: "New-seat path, webhook catalogue, Senegal and Mozambique desks, Maputo Corridor graph.",
    hrefs: ["/onboarding", "/webhooks", "/graph/senegal", "/graph/maputo-corridor"],
  },
  {
    slug: "phase-23",
    title: "Regions, runbooks, Zambia / Lobito span",
    phase: "23",
    status: "draft",
    lede: "Regional hubs, desk SOP shells, Zambia desk, Lobito Corridor spans Angola and Zambia.",
    hrefs: ["/regions", "/runbooks", "/graph/zambia", "/graph/lobito-corridor"],
  },
  {
    slug: "phase-24",
    title: "Layers, press, Tunisia desk",
    phase: "24",
    status: "draft",
    lede: "NEWS→DECISIONS layer map, media kit shells, Tunisia graph desk.",
    hrefs: ["/layers", "/press", "/graph/tunisia"],
  },
  {
    slug: "phase-25",
    title: "Go-live gates + LinkedIn social desk",
    phase: "25",
    status: "draft",
    lede: "Honest blockers before official prints; LinkedIn share intents and company URL hook.",
    hrefs: ["/golive", "/social"],
  },
  {
    slug: "phase-26",
    title: "Embeds, Algeria desk, LinkedIn cross-post",
    phase: "26",
    status: "draft",
    lede: "Widget catalogue with zero issued keys; Algeria graph desk; LinkedIn cross-post runbook.",
    hrefs: ["/embeds", "/graph/algeria", "/runbooks"],
  },
  {
    slug: "phase-27",
    title: "Security trust + Botswana desk",
    phase: "27",
    status: "draft",
    lede: "Honest control catalogue with no fake compliance badges; Botswana graph desk.",
    hrefs: ["/security", "/graph/botswana"],
  },
  {
    slug: "phase-28",
    title: "Integrations + Cameroon desk",
    phase: "28",
    status: "draft",
    lede: "Slack/Teams/email delivery catalogue with zero connections; Cameroon graph desk.",
    hrefs: ["/integrations", "/graph/cameroon"],
  },
  {
    slug: "phase-29",
    title: "SLA catalogue + Namibia desk",
    phase: "29",
    status: "draft",
    lede: "Service commitment shells with no fake uptime %; Namibia graph desk.",
    hrefs: ["/sla", "/graph/namibia"],
  },
  {
    slug: "phase-30",
    title: "Brand kit + Trans-Kalahari corridor",
    phase: "30",
    status: "draft",
    lede: "Identity catalogue without a fake logo pack; Trans-Kalahari corridor desk.",
    hrefs: ["/brand", "/graph/trans-kalahari", "/trade/trans-kalahari"],
  },
  {
    slug: "phase-31",
    title: "Roadmap, accessibility, Libya, Beira",
    phase: "31",
    status: "draft",
    lede: "Public roadmap and a11y posture; Libya and Zimbabwe desks; Beira Corridor.",
    hrefs: ["/roadmap", "/accessibility", "/graph/libya", "/graph/beira-corridor"],
  },
  {
    slug: "phase-32",
    title: "SDK catalogue + Mauritius desk",
    phase: "32",
    status: "draft",
    lede: "Client SDK shells with zero published packages; Mauritius graph desk.",
    hrefs: ["/sdk", "/graph/mauritius"],
  },
  {
    slug: "phase-33",
    title: "Templates, support, Djibouti desk",
    phase: "33",
    status: "draft",
    lede: "Desk template catalogue, honest support doors, Djibouti ports graph desk.",
    hrefs: ["/templates", "/support", "/graph/djibouti"],
  },
  {
    slug: "phase-34",
    title: "Newsletters + Gabon desk",
    phase: "34",
    status: "draft",
    lede: "Email digest catalogue with zero sends; Gabon graph desk.",
    hrefs: ["/newsletters", "/graph/gabon"],
  },
  {
    slug: "phase-35",
    title: "Careers + Malawi desk",
    phase: "35",
    status: "draft",
    lede: "Role shapes with zero open posts; Malawi graph desk.",
    hrefs: ["/careers", "/graph/malawi"],
  },
  {
    slug: "phase-36",
    title: "Contact doors + Benin desk",
    phase: "36",
    status: "draft",
    lede: "Contact catalogue with no fake form delivery; Benin graph desk.",
    hrefs: ["/contact", "/graph/benin"],
  },
  {
    slug: "phase-37",
    title: "FAQ + Togo desk",
    phase: "37",
    status: "draft",
    lede: "Honest product FAQ; Togo ports graph desk.",
    hrefs: ["/faq", "/graph/togo"],
  },
  {
    slug: "phase-38",
    title: "Cookies posture + Mali desk",
    phase: "38",
    status: "draft",
    lede: "Cookie catalogue with no fake banner; Mali graph desk.",
    hrefs: ["/legal/cookies", "/graph/mali"],
  },
  {
    slug: "phase-39",
    title: "Trust center + Niger desk",
    phase: "39",
    status: "draft",
    lede: "Trust hub for method, security and go-live; Niger graph desk.",
    hrefs: ["/trust", "/graph/niger"],
  },
  {
    slug: "phase-40",
    title: "Credits + BF/GN/LR desks",
    phase: "40",
    status: "draft",
    lede: "House credits; Burkina Faso, Guinea and Liberia graph desks.",
    hrefs: ["/credits", "/graph/burkina-faso", "/graph/guinea", "/graph/liberia"],
  },
  {
    slug: "phase-41",
    title: "Manifesto + SL/MR/GM/TD desks",
    phase: "41",
    status: "draft",
    lede: "Product manifesto; Sierra Leone, Mauritania, Gambia and Chad desks.",
    hrefs: ["/manifesto", "/graph/sierra-leone", "/graph/mauritania", "/graph/gambia", "/graph/chad"],
  },
  {
    slug: "phase-42",
    title: "Imprint + Madagascar / Congo desks",
    phase: "42",
    status: "draft",
    lede: "Publisher imprint with empty counsel fields; Madagascar and Congo graph desks.",
    hrefs: ["/imprint", "/graph/madagascar", "/graph/congo"],
  },
  {
    slug: "phase-43",
    title: "Syndication + Burundi / CAR / Equatorial Guinea desks",
    phase: "43",
    status: "draft",
    lede: "Public RSS, sitemap and status doors with no audience figures; Burundi, CAR and Equatorial Guinea graph desks.",
    hrefs: ["/syndication", "/graph/burundi", "/graph/central-african-republic", "/graph/equatorial-guinea"],
  },
  {
    slug: "phase-44",
    title: "Notices + DR Congo / São Tomé / South Sudan desks",
    phase: "44",
    status: "draft",
    lede: "House notice slots with nothing posted; DR Congo, São Tomé and Príncipe, and South Sudan graph desks.",
    hrefs: ["/notices", "/graph/dr-congo", "/graph/sao-tome-and-principe", "/graph/south-sudan"],
  },
  {
    slug: "phase-45",
    title: "Languages + Sudan / Eritrea / Somalia desks",
    phase: "45",
    status: "draft",
    lede: "English is the only live edition; Sudan, Eritrea and Somalia graph desks.",
    hrefs: ["/languages", "/graph/sudan", "/graph/eritrea", "/graph/somalia"],
  },
  {
    slug: "phase-46",
    title: "Units + Cabo Verde / Guinea-Bissau / Comoros desks",
    phase: "46",
    status: "draft",
    lede: "Unit vocabulary with no stored series; Cabo Verde, Guinea-Bissau and Comoros graph desks.",
    hrefs: ["/units", "/graph/cabo-verde", "/graph/guinea-bissau", "/graph/comoros"],
  },
  {
    slug: "phase-47",
    title: "Correspondents + Eswatini / Lesotho desks",
    phase: "47",
    status: "draft",
    lede: "Correspondent seats with no invented bylines; Eswatini and Lesotho graph desks.",
    hrefs: ["/correspondents", "/graph/eswatini", "/graph/lesotho"],
  },
  {
    slug: "phase-48",
    title: "Citations + Seychelles desk",
    phase: "48",
    status: "draft",
    lede: "Citation shapes with no sample print; Seychelles graph desk. Country desks now cover the full set.",
    hrefs: ["/citations", "/graph/seychelles"],
  },
  {
    slug: "phase-49",
    title: "Corridors + Abidjan–Lagos / Nacala",
    phase: "49",
    status: "draft",
    lede: "Named corridor catalogue with no stored volumes; Abidjan–Lagos and Nacala graph desks.",
    hrefs: ["/corridors", "/graph/abidjan-lagos", "/graph/nacala-corridor"],
  },
  {
    slug: "phase-50",
    title: "Identifiers + LAPSSET / North-South",
    phase: "50",
    status: "draft",
    lede: "Identifier vocabulary with no crosswalk; LAPSSET and North-South corridor desks.",
    hrefs: ["/identifiers", "/graph/lapsset", "/graph/north-south-corridor"],
  },
  {
    slug: "phase-51",
    title: "Series + Douala–N'Djamena / Walvis–Ndola",
    phase: "51",
    status: "draft",
    lede: "Series shapes with no observations; Douala–N'Djamena and Walvis Bay–Ndola desks.",
    hrefs: ["/series", "/graph/douala-ndjamena", "/graph/walvis-ndola"],
  },
  {
    slug: "phase-52",
    title: "Revisions + Djibouti–Addis / Dakar–Bamako",
    phase: "52",
    status: "draft",
    lede: "Revision shapes with nothing posted; Djibouti–Addis and Dakar–Bamako desks.",
    hrefs: ["/revisions", "/graph/djibouti-addis", "/graph/dakar-bamako"],
  },
  {
    slug: "phase-53",
    title: "Classifications + Cotonou–Niamey / Lomé–Ouagadougou",
    phase: "53",
    status: "draft",
    lede: "Grouping words with no code table; Cotonou–Niamey and Lomé–Ouagadougou desks.",
    hrefs: ["/classifications", "/graph/cotonou-niamey", "/graph/lome-ouagadougou"],
  },
  {
    slug: "phase-54",
    title: "Releases + Abidjan–Ouagadougou / Conakry–Bamako",
    phase: "54",
    status: "draft",
    lede: "Release shapes with no scheduled date; Abidjan–Ouagadougou and Conakry–Bamako desks.",
    hrefs: ["/releases", "/graph/abidjan-ouagadougou", "/graph/conakry-bamako"],
  },
  {
    slug: "phase-55",
    title: "Datelines + Pointe-Noire / TAZARA",
    phase: "55",
    status: "draft",
    lede: "Dateline shapes with no filed story; Pointe-Noire–Brazzaville and TAZARA desks.",
    hrefs: ["/datelines", "/graph/pointe-noire-brazzaville", "/graph/tazara"],
  },
  {
    slug: "phase-56",
    title: "Borders + Douala–Bangui / Tema–Ouagadougou",
    phase: "56",
    status: "draft",
    lede: "Border shapes with nothing recorded; Douala–Bangui and Tema–Ouagadougou desks.",
    hrefs: ["/borders", "/graph/douala-bangui", "/graph/tema-ouagadougou"],
  },
  {
    slug: "phase-57",
    title: "Customs + Abidjan–Bamako / Lomé–Niamey",
    phase: "57",
    status: "draft",
    lede: "Customs shapes with nothing filed; Abidjan–Bamako and Lomé–Niamey desks.",
    hrefs: ["/customs", "/graph/abidjan-bamako", "/graph/lome-niamey"],
  },
  {
    slug: "phase-58",
    title: "Modes + Nouakchott–Dakar / Lagos–Niamey",
    phase: "58",
    status: "draft",
    lede: "Mode words with no tonnage; Nouakchott–Dakar and Lagos–Niamey desks.",
    hrefs: ["/modes", "/graph/nouakchott-dakar", "/graph/lagos-niamey"],
  },
  {
    slug: "phase-59",
    title: "Observations + Matadi–Kinshasa / Berbera–Addis",
    phase: "59",
    status: "draft",
    lede: "Observation shapes with no dated print; Matadi–Kinshasa and Berbera–Addis desks.",
    hrefs: ["/observations", "/graph/matadi-kinshasa", "/graph/berbera-addis"],
  },
  {
    slug: "phase-60",
    title: "Frequencies + Cape Town–Johannesburg / Alexandria–Cairo",
    phase: "60",
    status: "draft",
    lede: "Frequency words with no calendar; Cape Town–Johannesburg and Alexandria–Cairo desks.",
    hrefs: ["/frequencies", "/graph/cape-town-johannesburg", "/graph/alexandria-cairo"],
  },
  {
    slug: "phase-61",
    title: "Vintages + Port Said–Cairo / Banjul–Dakar",
    phase: "61",
    status: "draft",
    lede: "Vintage shapes with nothing posted; Port Said–Cairo and Banjul–Dakar desks.",
    hrefs: ["/vintages", "/graph/port-said-cairo", "/graph/banjul-dakar"],
  },
  {
    slug: "phase-62",
    title: "Lineage + Freetown–Monrovia / Luanda–Lobito",
    phase: "62",
    status: "draft",
    lede: "Lineage shapes with no source chain; Freetown–Monrovia and Luanda–Lobito desks.",
    hrefs: ["/lineage", "/graph/freetown-monrovia", "/graph/luanda-lobito"],
  },
  {
    slug: "phase-63",
    title: "Gaps + Port Sudan–Khartoum / Toamasina–Antananarivo",
    phase: "63",
    status: "draft",
    lede: "Gap shapes with no missing date; Port Sudan–Khartoum and Toamasina–Antananarivo desks.",
    hrefs: ["/gaps", "/graph/port-sudan-khartoum", "/graph/toamasina-antananarivo"],
  },
  {
    slug: "phase-64",
    title: "Periods + Mbabane–Maputo / Maseru–Johannesburg",
    phase: "64",
    status: "draft",
    lede: "Period words with no window; Mbabane–Maputo and Maseru–Johannesburg desks.",
    hrefs: ["/periods", "/graph/mbabane-maputo", "/graph/maseru-johannesburg"],
  },
  {
    slug: "phase-65",
    title: "Lags + Bissau–Dakar / Mogadishu–Berbera",
    phase: "65",
    status: "draft",
    lede: "Lag shapes with no delay; Bissau–Dakar and Mogadishu–Berbera desks.",
    hrefs: ["/lags", "/graph/bissau-dakar", "/graph/mogadishu-berbera"],
  },
  {
    slug: "phase-66",
    title: "Benchmarks + Accra–Tema / Abuja–Lagos",
    phase: "66",
    status: "draft",
    lede: "Benchmark shapes with no reference print; Accra–Tema and Abuja–Lagos desks.",
    hrefs: ["/benchmarks", "/graph/accra-tema", "/graph/abuja-lagos"],
  },
  {
    slug: "phase-67",
    title: "Baskets + Douala–Yaoundé / Massawa–Asmara",
    phase: "67",
    status: "draft",
    lede: "Basket shapes with no weight; Douala–Yaoundé and Massawa–Asmara desks.",
    hrefs: ["/baskets", "/graph/douala-yaounde", "/graph/massawa-asmara"],
  },
  {
    slug: "phase-68",
    title: "Thresholds + Tangier–Casablanca / Tunis–Sfax",
    phase: "68",
    status: "draft",
    lede: "Threshold shapes with no level; Tangier–Casablanca and Tunis–Sfax desks.",
    hrefs: ["/thresholds", "/graph/tangier-casablanca", "/graph/tunis-sfax"],
  },
  {
    slug: "phase-69",
    title: "Peers + Algiers–Oran / Tripoli–Benghazi",
    phase: "69",
    status: "draft",
    lede: "Peer shapes with no comparison set; Algiers–Oran and Tripoli–Benghazi desks.",
    hrefs: ["/peers", "/graph/algiers-oran", "/graph/tripoli-benghazi"],
  },
  {
    slug: "phase-70",
    title: "Weights + Libreville–Port-Gentil / Malabo–Bata",
    phase: "70",
    status: "draft",
    lede: "Weight shapes with no share; Libreville–Port-Gentil and Malabo–Bata desks.",
    hrefs: ["/weights", "/graph/libreville-port-gentil", "/graph/malabo-bata"],
  },
  {
    slug: "phase-71",
    title: "Constituents + Nouakchott–Nouadhibou / Lusaka–Ndola",
    phase: "71",
    status: "draft",
    lede: "Constituent shapes with no member; Nouakchott–Nouadhibou and Lusaka–Ndola desks.",
    hrefs: ["/constituents", "/graph/nouakchott-nouadhibou", "/graph/lusaka-ndola"],
  },
  {
    slug: "phase-72",
    title: "Horizons + Beira–Lilongwe / Harare–Bulawayo",
    phase: "72",
    status: "draft",
    lede: "Horizon words with no forecast; Beira–Lilongwe and Harare–Bulawayo desks.",
    hrefs: ["/horizons", "/graph/beira-lilongwe", "/graph/harare-bulawayo"],
  },
  {
    slug: "phase-73",
    title: "Baselines + Accra–Kumasi / Brazzaville–Kinshasa",
    phase: "73",
    status: "draft",
    lede: "Baseline shapes with no starting print; Accra–Kumasi and Brazzaville–Kinshasa desks.",
    hrefs: ["/baselines", "/graph/accra-kumasi", "/graph/brazzaville-kinshasa"],
  },
  {
    slug: "phase-74",
    title: "Spreads + Gaborone–Francistown / Windhoek–Walvis Bay",
    phase: "74",
    status: "draft",
    lede: "Spread shapes with no gap; Gaborone–Francistown and Windhoek–Walvis Bay desks.",
    hrefs: ["/spreads", "/graph/gaborone-francistown", "/graph/windhoek-walvis-bay"],
  },
  {
    slug: "phase-75",
    title: "Seasons + Mombasa–Nairobi / Dar es Salaam–Dodoma",
    phase: "75",
    status: "draft",
    lede: "Season words with no window; Mombasa–Nairobi and Dar es Salaam–Dodoma desks.",
    hrefs: ["/seasons", "/graph/mombasa-nairobi", "/graph/dar-es-salaam-dodoma"],
  },
  {
    slug: "phase-76",
    title: "Adjustments + Kano–Lagos / Blantyre–Lilongwe",
    phase: "76",
    status: "draft",
    lede: "Adjustment shapes with no factor; Kano–Lagos and Blantyre–Lilongwe desks.",
    hrefs: ["/adjustments", "/graph/kano-lagos", "/graph/blantyre-lilongwe"],
  },
  {
    slug: "phase-77",
    title: "Footnotes + Cairo–Aswan / Casablanca–Marrakech",
    phase: "77",
    status: "draft",
    lede: "Footnote shapes with no caveat; Cairo–Aswan and Casablanca–Marrakech desks.",
    hrefs: ["/footnotes", "/graph/cairo-aswan", "/graph/casablanca-marrakech"],
  },
  {
    slug: "phase-78",
    title: "Scales + Durban–Johannesburg / Kampala–Kigali",
    phase: "78",
    status: "draft",
    lede: "Scale words with no transform; Durban–Johannesburg and Kampala–Kigali desks.",
    hrefs: ["/scales", "/graph/durban-johannesburg", "/graph/kampala-kigali"],
  },
  {
    slug: "phase-79",
    title: "Precision + Juba–Kampala / Ouagadougou–Niamey",
    phase: "79",
    status: "draft",
    lede: "Precision shapes with no fineness; Juba–Kampala and Ouagadougou–Niamey desks.",
    hrefs: ["/precision", "/graph/juba-kampala", "/graph/ouagadougou-niamey"],
  },
  {
    slug: "phase-80",
    title: "Rounding + Addis Ababa–Nairobi / Bamako–Ouagadougou",
    phase: "80",
    status: "draft",
    lede: "Rounding shapes with no convention; Addis Ababa–Nairobi and Bamako–Ouagadougou desks.",
    hrefs: ["/rounding", "/graph/addis-ababa-nairobi", "/graph/bamako-ouagadougou"],
  },
  {
    slug: "phase-81",
    title: "Crosswalks + Niamey–Kano / Algiers–Constantine",
    phase: "81",
    status: "draft",
    lede: "Crosswalk shapes with no map; Niamey–Kano and Algiers–Constantine desks.",
    hrefs: ["/crosswalks", "/graph/niamey-kano", "/graph/algiers-constantine"],
  },
  {
    slug: "phase-82",
    title: "Aliases + Accra–Takoradi / Kigali–Bujumbura",
    phase: "82",
    status: "draft",
    lede: "Alias shapes with no other name; Accra–Takoradi and Kigali–Bujumbura desks.",
    hrefs: ["/aliases", "/graph/accra-takoradi", "/graph/kigali-bujumbura"],
  },
  {
    slug: "phase-83",
    title: "Embargoes + Lusaka–Harare / Lagos–Port Harcourt",
    phase: "83",
    status: "draft",
    lede: "Embargo shapes with no hold; Lusaka–Harare and Lagos–Port Harcourt desks.",
    hrefs: ["/embargoes", "/graph/lusaka-harare", "/graph/lagos-port-harcourt"],
  },
  {
    slug: "phase-84",
    title: "Sessions + Nairobi–Kisumu / Abidjan–San-Pédro",
    phase: "84",
    status: "draft",
    lede: "Session words with no clock time; Nairobi–Kisumu and Abidjan–San-Pédro desks.",
    hrefs: ["/sessions", "/graph/nairobi-kisumu", "/graph/abidjan-san-pedro"],
  },
  {
    slug: "phase-85",
    title: "Holidays + Beira–Tete / Monrovia–Buchanan",
    phase: "85",
    status: "draft",
    lede: "Holiday shapes with no date; Beira–Tete and Monrovia–Buchanan desks.",
    hrefs: ["/holidays", "/graph/beira-tete", "/graph/monrovia-buchanan"],
  },
  {
    slug: "phase-86",
    title: "Factors + Casablanca–Rabat / Johannesburg–Pretoria",
    phase: "86",
    status: "draft",
    lede: "Factor shapes with no conversion; Casablanca–Rabat and Johannesburg–Pretoria desks.",
    hrefs: ["/factors", "/graph/casablanca-rabat", "/graph/johannesburg-pretoria"],
  },
  {
    slug: "phase-87",
    title: "Tenors + Dakar–Saint-Louis / Accra–Tamale",
    phase: "87",
    status: "draft",
    lede: "Tenor words with no maturity date; Dakar–Saint-Louis and Accra–Tamale desks.",
    hrefs: ["/tenors", "/graph/dakar-saint-louis", "/graph/accra-tamale"],
  },
  {
    slug: "phase-88",
    title: "Grades + Luanda–Namibe / Kinshasa–Lubumbashi",
    phase: "88",
    status: "draft",
    lede: "Grade shapes with no specification; Luanda–Namibe and Kinshasa–Lubumbashi desks.",
    hrefs: ["/grades", "/graph/luanda-namibe", "/graph/kinshasa-lubumbashi"],
  },
  {
    slug: "phase-89",
    title: "Flags + Algiers–Annaba / Lagos–Calabar",
    phase: "89",
    status: "draft",
    lede: "Flag words with no quality mark; Algiers–Annaba and Lagos–Calabar desks.",
    hrefs: ["/flags", "/graph/algiers-annaba", "/graph/lagos-calabar"],
  },
  {
    slug: "phase-90",
    title: "Windows + Kampala–Entebbe / Dar es Salaam–Mwanza",
    phase: "90",
    status: "draft",
    lede: "Window shapes with no span of time; Kampala–Entebbe and Dar es Salaam–Mwanza desks.",
    hrefs: ["/windows", "/graph/kampala-entebbe", "/graph/dar-es-salaam-mwanza"],
  },
  {
    slug: "phase-91",
    title: "Cutoffs + Cotonou–Porto-Novo / Lomé–Kara",
    phase: "91",
    status: "draft",
    lede: "Cutoff shapes with no clock time; Cotonou–Porto-Novo and Lomé–Kara desks.",
    hrefs: ["/cutoffs", "/graph/cotonou-porto-novo", "/graph/lome-kara"],
  },
  {
    slug: "phase-92",
    title: "Stamps + Tunis–Sousse / Cairo–Luxor",
    phase: "92",
    status: "draft",
    lede: "Stamp shapes with no as-of date; Tunis–Sousse and Cairo–Luxor desks.",
    hrefs: ["/stamps", "/graph/tunis-sousse", "/graph/cairo-luxor"],
  },
  {
    slug: "phase-93",
    title: "Breaks + Conakry–Kankan / Libreville–Franceville",
    phase: "93",
    status: "draft",
    lede: "Break shapes with no series split; Conakry–Kankan and Libreville–Franceville desks.",
    hrefs: ["/breaks", "/graph/conakry-kankan", "/graph/libreville-franceville"],
  },
  {
    slug: "phase-94",
    title: "Curves + Nairobi–Nakuru / Addis Ababa–Dire Dawa",
    phase: "94",
    status: "draft",
    lede: "Curve shapes with no plot; Nairobi–Nakuru and Addis Ababa–Dire Dawa desks.",
    hrefs: ["/curves", "/graph/nairobi-nakuru", "/graph/addis-ababa-dire-dawa"],
  },
  {
    slug: "phase-95",
    title: "Fixes + Abidjan–Bouaké / Lagos–Ibadan",
    phase: "95",
    status: "draft",
    lede: "Fixing shapes with no rate; Abidjan–Bouaké and Lagos–Ibadan desks.",
    hrefs: ["/fixes", "/graph/abidjan-bouake", "/graph/lagos-ibadan"],
  },
  {
    slug: "phase-96",
    title: "Lots + Johannesburg–Bloemfontein / Lusaka–Livingstone",
    phase: "96",
    status: "draft",
    lede: "Lot shapes with no parcel; Johannesburg–Bloemfontein and Lusaka–Livingstone desks.",
    hrefs: ["/lots", "/graph/johannesburg-bloemfontein", "/graph/lusaka-livingstone"],
  },
  {
    slug: "phase-97",
    title: "Quotes + Marrakech–Agadir / Kampala–Jinja",
    phase: "97",
    status: "draft",
    lede: "Quote shapes with no price; Marrakech–Agadir and Kampala–Jinja desks.",
    hrefs: ["/quotes", "/graph/marrakech-agadir", "/graph/kampala-jinja"],
  },
  {
    slug: "phase-98",
    title: "Contracts + Yaoundé–Garoua / Harare–Mutare",
    phase: "98",
    status: "draft",
    lede: "Contract shapes with no agreement; Yaoundé–Garoua and Harare–Mutare desks.",
    hrefs: ["/contracts", "/graph/yaounde-garoua", "/graph/harare-mutare"],
  },
  {
    slug: "phase-99",
    title: "Samples + Maputo–Nampula / Accra–Cape Coast",
    phase: "99",
    status: "draft",
    lede: "Sample shapes with no draw; Maputo–Nampula and Accra–Cape Coast desks.",
    hrefs: ["/samples", "/graph/maputo-nampula", "/graph/accra-cape-coast"],
  },
  {
    slug: "phase-100",
    title: "Indices + Windhoek–Rundu / Gaborone–Maun",
    phase: "100",
    status: "draft",
    lede: "Index shapes with no basket; Windhoek–Rundu and Gaborone–Maun desks.",
    hrefs: ["/indices", "/graph/windhoek-rundu", "/graph/gaborone-maun"],
  },
  {
    slug: "phase-101",
    title: "Manifests + Tripoli–Misrata / Oran–Constantine",
    phase: "101",
    status: "draft",
    lede: "Manifest shapes with no cargo list; Tripoli–Misrata and Oran–Constantine desks.",
    hrefs: ["/manifests", "/graph/tripoli-misrata", "/graph/oran-constantine"],
  },
  {
    slug: "phase-102",
    title: "Parcels + Blantyre–Zomba / Asmara–Keren",
    phase: "102",
    status: "draft",
    lede: "Parcel shapes with no shipment; Blantyre–Zomba and Asmara–Keren desks.",
    hrefs: ["/parcels", "/graph/blantyre-zomba", "/graph/asmara-keren"],
  },
  {
    slug: "phase-103",
    title: "Draws + Luanda–Malanje / Antananarivo–Fianarantsoa",
    phase: "103",
    status: "draft",
    lede: "Draw shapes with no selection; Luanda–Malanje and Antananarivo–Fianarantsoa desks.",
    hrefs: ["/draws", "/graph/luanda-malanje", "/graph/antananarivo-fianarantsoa"],
  },
  {
    slug: "phase-104",
    title: "Settlements + Dakar–Kaolack / Bamako–Sikasso",
    phase: "104",
    status: "draft",
    lede: "Settlement shapes with no movement; Dakar–Kaolack and Bamako–Sikasso desks.",
    hrefs: ["/settlements", "/graph/dakar-kaolack", "/graph/bamako-sikasso"],
  },
  {
    slug: "phase-105",
    title: "Positions + Ouagadougou–Bobo-Dioulasso / Khartoum–Kassala",
    phase: "105",
    status: "draft",
    lede: "Position shapes with no holding; Ouagadougou–Bobo-Dioulasso and Khartoum–Kassala desks.",
    hrefs: ["/positions", "/graph/ouagadougou-bobo-dioulasso", "/graph/khartoum-kassala"],
  },
  {
    slug: "phase-106",
    title: "Auctions + N'Djamena–Moundou / Kigali–Musanze",
    phase: "106",
    status: "draft",
    lede: "Auction shapes with no sale; N'Djamena–Moundou and Kigali–Musanze desks.",
    hrefs: ["/auctions", "/graph/ndjamena-moundou", "/graph/kigali-musanze"],
  },
  {
    slug: "phase-109",
    title: "Clearances + Abuja–Kano / Dodoma–Mwanza",
    phase: "109",
    status: "draft",
    lede: "Clearance shapes with no decision; Abuja–Kano and Dodoma–Mwanza desks.",
    hrefs: ["/clearances", "/graph/abuja-kano", "/graph/dodoma-mwanza"],
  },
  {
    slug: "phase-110",
    title: "Warehouses + Pretoria–Bloemfontein / Niamey–Zinder",
    phase: "110",
    status: "draft",
    lede: "Warehouse shapes with no stock; Pretoria–Bloemfontein and Niamey–Zinder desks.",
    hrefs: ["/warehouses", "/graph/pretoria-bloemfontein", "/graph/niamey-zinder"],
  },
  {
    slug: "phase-111",
    title: "Permits + Bujumbura–Gitega / Bangui–Bambari",
    phase: "111",
    status: "draft",
    lede: "Permit shapes with no authorisation; Bujumbura–Gitega and Bangui–Bambari desks.",
    hrefs: ["/permits", "/graph/bujumbura-gitega", "/graph/bangui-bambari"],
  },
  {
    slug: "phase-112",
    title: "Guarantees + Juba–Wau / Rabat–Fès",
    phase: "112",
    status: "draft",
    lede: "Guarantee shapes with no security; Juba–Wau and Rabat–Fès desks.",
    hrefs: ["/guarantees", "/graph/juba-wau", "/graph/rabat-fes"],
  },
  {
    slug: "phase-113",
    title: "Inspections + Kisumu–Eldoret / Kumasi–Tamale",
    phase: "113",
    status: "draft",
    lede: "Inspection shapes with no finding; Kisumu–Eldoret and Kumasi–Tamale desks.",
    hrefs: ["/inspections", "/graph/kisumu-eldoret", "/graph/kumasi-tamale"],
  },
  {
    slug: "phase-114",
    title: "Waybills + Ibadan–Ilorin / Kampala–Gulu",
    phase: "114",
    status: "draft",
    lede: "Waybill shapes with no carriage document; Ibadan–Ilorin and Kampala–Gulu desks.",
    hrefs: ["/waybills", "/graph/ibadan-ilorin", "/graph/kampala-gulu"],
  },
  {
    slug: "phase-115",
    title: "Consignments + Lusaka–Chipata / Harare–Gweru",
    phase: "115",
    status: "draft",
    lede: "Consignment shapes with no movement; Lusaka–Chipata and Harare–Gweru desks.",
    hrefs: ["/consignments", "/graph/lusaka-chipata", "/graph/harare-gweru"],
  },
  {
    slug: "phase-116",
    title: "Certificates + Ndola–Kitwe / Addis Ababa–Mekelle",
    phase: "116",
    status: "draft",
    lede: "Certificate shapes with no authority document; Ndola–Kitwe and Addis Ababa–Mekelle desks.",
    hrefs: ["/certificates", "/graph/ndola-kitwe", "/graph/addis-ababa-mekelle"],
  },
  {
    slug: "phase-117",
    title: "Surveys + Nakuru–Eldoret / Tamale–Bolgatanga",
    phase: "117",
    status: "draft",
    lede: "Survey shapes with no reading; Nakuru–Eldoret and Tamale–Bolgatanga desks.",
    hrefs: ["/surveys", "/graph/nakuru-eldoret", "/graph/tamale-bolgatanga"],
  },
  {
    slug: "phase-118",
    title: "Duties + Kano–Maiduguri / Jinja–Mbale",
    phase: "118",
    status: "draft",
    lede: "Duty shapes with no assessment amount; Kano–Maiduguri and Jinja–Mbale desks.",
    hrefs: ["/duties", "/graph/kano-maiduguri", "/graph/jinja-mbale"],
  },
  {
    slug: "phase-119",
    title: "Quotas + Durban–Pietermaritzburg / Beira–Chimoio",
    phase: "119",
    status: "draft",
    lede: "Quota shapes with no fill; Durban–Pietermaritzburg and Beira–Chimoio desks.",
    hrefs: ["/quotas", "/graph/durban-pietermaritzburg", "/graph/beira-chimoio"],
  },
  {
    slug: "phase-120",
    title: "Assays + Lubumbashi–Kolwezi / Antananarivo–Antsirabe",
    phase: "120",
    status: "draft",
    lede: "Assay shapes with no laboratory result; Lubumbashi–Kolwezi and Antananarivo–Antsirabe desks.",
    hrefs: ["/assays", "/graph/lubumbashi-kolwezi", "/graph/antananarivo-antsirabe"],
  },
  {
    slug: "phase-121",
    title: "Tallies + Enugu–Onitsha / Meknes–Fès",
    phase: "121",
    status: "draft",
    lede: "Tally shapes with no count; Enugu–Onitsha and Meknes–Fès desks.",
    hrefs: ["/tallies", "/graph/enugu-onitsha", "/graph/meknes-fes"],
  },
  {
    slug: "phase-122",
    title: "Seals + Kaduna–Zaria / Huambo–Lubango",
    phase: "122",
    status: "draft",
    lede: "Seal shapes with no closure record; Kaduna–Zaria and Huambo–Lubango desks.",
    hrefs: ["/seals", "/graph/kaduna-zaria", "/graph/huambo-lubango"],
  },
  {
    slug: "phase-123",
    title: "Stowage + Arusha–Moshi / Garoua–Maroua",
    phase: "123",
    status: "draft",
    lede: "Stowage shapes with no plan; Arusha–Moshi and Garoua–Maroua desks.",
    hrefs: ["/stowage", "/graph/arusha-moshi", "/graph/garoua-maroua"],
  },
  {
    slug: "phase-124",
    title: "Nominations + Jos–Bauchi / Polokwane–Mbombela",
    phase: "124",
    status: "draft",
    lede: "Nomination shapes with no name; Jos–Bauchi and Polokwane–Mbombela desks.",
    hrefs: ["/nominations", "/graph/jos-bauchi", "/graph/polokwane-mbombela"],
  },
  {
    slug: "phase-125",
    title: "Berths + Sokoto–Katsina / Oujda–Taza",
    phase: "125",
    status: "draft",
    lede: "Berth shapes with no call; Sokoto–Katsina and Oujda–Taza desks.",
    hrefs: ["/berths", "/graph/sokoto-katsina", "/graph/oujda-taza"],
  },
  {
    slug: "phase-126",
    title: "Laytime + Sunyani–Techiman / Tabora–Kigoma",
    phase: "126",
    status: "draft",
    lede: "Laytime shapes with no allowance; Sunyani–Techiman and Tabora–Kigoma desks.",
    hrefs: ["/laytime", "/graph/sunyani-techiman", "/graph/tabora-kigoma"],
  },
  {
    slug: "phase-127",
    title: "Shortages + Bloemfontein–Kimberley / Mzuzu–Karonga",
    phase: "127",
    status: "draft",
    lede: "Shortage shapes with no quantity; Bloemfontein–Kimberley and Mzuzu–Karonga desks.",
    hrefs: ["/shortages", "/graph/bloemfontein-kimberley", "/graph/mzuzu-karonga"],
  },
  {
    slug: "phase-128",
    title: "Endorsements + Abeokuta–Ibadan / Sétif–Batna",
    phase: "128",
    status: "draft",
    lede: "Endorsement shapes with no mark; Abeokuta–Ibadan and Sétif–Batna desks.",
    hrefs: ["/endorsements", "/graph/abeokuta-ibadan", "/graph/setif-batna"],
  },
  {
    slug: "phase-129",
    title: "Demurrage + Makurdi–Lafia / Bahir Dar–Gondar",
    phase: "129",
    status: "draft",
    lede: "Demurrage shapes with no charge; Makurdi–Lafia and Bahir Dar–Gondar desks.",
    hrefs: ["/demurrage", "/graph/makurdi-lafia", "/graph/bahir-dar-gondar"],
  },
  {
    slug: "phase-130",
    title: "Handovers + Mbeya–Iringa / Mbarara–Kabale",
    phase: "130",
    status: "draft",
    lede: "Handover shapes with no pass; Mbeya–Iringa and Mbarara–Kabale desks.",
    hrefs: ["/handovers", "/graph/mbeya-iringa", "/graph/mbarara-kabale"],
  },
  {
    slug: "phase-131",
    title: "Receipts + Ségou–Mopti / Kairouan–Gafsa",
    phase: "131",
    status: "draft",
    lede: "Receipt shapes with no confirmation; Ségou–Mopti and Kairouan–Gafsa desks.",
    hrefs: ["/receipts", "/graph/segou-mopti", "/graph/kairouan-gafsa"],
  },
  {
    slug: "phase-132",
    title: "Waivers + Masvingo–Chiredzi / Huye–Muhanga",
    phase: "132",
    status: "draft",
    lede: "Waiver shapes with no waiver; Masvingo–Chiredzi and Huye–Muhanga desks.",
    hrefs: ["/waivers", "/graph/masvingo-chiredzi", "/graph/huye-muhanga"],
  },
  {
    slug: "phase-133",
    title: "Laycans + Yola–Jalingo / Nyeri–Nanyuki",
    phase: "133",
    status: "draft",
    lede: "Laycan shapes with no date; Yola–Jalingo and Nyeri–Nanyuki desks.",
    hrefs: ["/laycans", "/graph/yola-jalingo", "/graph/nyeri-nanyuki"],
  },
  {
    slug: "phase-134",
    title: "Protests + Bamenda–Bafoussam / Kabwe–Kapiri",
    phase: "134",
    status: "draft",
    lede: "Protest shapes with no note; Bamenda–Bafoussam and Kabwe–Kapiri desks.",
    hrefs: ["/protests", "/graph/bamenda-bafoussam", "/graph/kabwe-kapiri"],
  },
  {
    slug: "phase-135",
    title: "Discharges + Goma–Bukavu / Asyut–Sohag",
    phase: "135",
    status: "draft",
    lede: "Discharge shapes with no quantity; Goma–Bukavu and Asyut–Sohag desks.",
    hrefs: ["/discharges", "/graph/goma-bukavu", "/graph/asyut-sohag"],
  },
  {
    slug: "phase-136",
    title: "Bonds + Thiès–Diourbel / Palapye–Serowe",
    phase: "136",
    status: "draft",
    lede: "Bond shapes with no amount; Thiès–Diourbel and Palapye–Serowe desks.",
    hrefs: ["/bonds", "/graph/thies-diourbel", "/graph/palapye-serowe"],
  },
  {
    slug: "phase-108",
    title: "Desk agents",
    phase: "108",
    status: "draft",
    lede: "Daily prints agent reads World Bank Open Data. A cell stays empty when the response has no number.",
    hrefs: ["/agents", "/observations", "/api/cron/agents"],
  },
  {
    slug: "phase-107",
    title: "Ledgers + Lilongwe–Mzuzu / Addis Ababa–Hawassa",
    phase: "107",
    status: "draft",
    lede: "Ledger shapes with no book; Lilongwe–Mzuzu and Addis Ababa–Hawassa desks.",
    hrefs: ["/ledgers", "/graph/lilongwe-mzuzu", "/graph/addis-ababa-hawassa"],
  },
  {
    slug: "phase-17",
    title: "Feeds, status, UG/TZ desks",
    phase: "17",
    status: "shipped",
    lede: "Enterprise feed catalogue, honest status board, Uganda and Tanzania corridor desks.",
    hrefs: ["/feeds", "/status", "/graph/uganda", "/graph/tanzania"],
  },
  {
    slug: "phase-16",
    title: "Sources, compare, ingestion",
    phase: "16",
    status: "shipped",
    lede: "Official door registry, featured desk matrix with empty cells, ops job board.",
    hrefs: ["/sources", "/compare", "/ingestion"],
  },
  {
    slug: "phase-15",
    title: "Featured desks, method, usage, packs",
    phase: "15",
    status: "shipped",
    lede: "Ghana and Rwanda desks, method registry, usage meters, briefing packs.",
    hrefs: ["/method/registry", "/account/usage", "/packs", "/graph/ghana"],
  },
];

export function shippedChangelogCount() {
  return changelogEntries.filter((item) => item.status === "shipped").length;
}
