export type GraphNodeKind =
  | "country"
  | "currency"
  | "agency"
  | "exchange"
  | "industry"
  | "indicator"
  | "corridor"
  | "company"
  | "city"
  | "person"
  | "concept";

export type GraphNode = {
  id: string;
  label: string;
  kind: GraphNodeKind;
  href?: string;
};

export type GraphEdge = {
  id: string;
  from: string;
  rel: string;
  to: string;
  source: string;
  asOf: string | null;
  status: "demo" | "editorial" | "verified";
};

export const graphNodes: GraphNode[] = [
  { id: "kenya", label: "Kenya", kind: "country", href: "/countries/kenya" },
  { id: "kes", label: "KES", kind: "currency", href: "/markets/currencies/usd-kes" },
  { id: "cbk", label: "CBK", kind: "agency", href: "/institutions/cbk" },
  { id: "nse", label: "NSE", kind: "exchange", href: "/institutions/nse" },
  { id: "nairobi", label: "Nairobi", kind: "city", href: "/cities/nairobi" },
  { id: "mombasa", label: "Mombasa", kind: "city", href: "/cities/mombasa" },
  { id: "banking", label: "Banking", kind: "industry", href: "/industries/banking/kenya" },
  { id: "agriculture", label: "Agriculture", kind: "industry", href: "/industries/agriculture/kenya" },
  { id: "energy", label: "Energy", kind: "industry", href: "/industries/energy/kenya" },
  { id: "policy-rate", label: "Policy rate", kind: "indicator", href: "/indicators/policy-rate/kenya" },
  { id: "northern-corridor", label: "Northern Corridor", kind: "corridor", href: "/trade/northern-corridor/kenya" },
  { id: "safaricom", label: "Safaricom", kind: "company", href: "/companies/safaricom" },
  { id: "equity", label: "Equity Group", kind: "company", href: "/companies/equity-group" },
  { id: "governor", label: "CBK governor", kind: "person", href: "/people/central-bank-governor/kenya" },
  { id: "inflation-costs", label: "Inflation / manufacturing costs", kind: "concept" },
  { id: "nigeria", label: "Nigeria", kind: "country", href: "/countries/nigeria" },
  { id: "ngn", label: "NGN", kind: "currency", href: "/markets/currencies/usd-ngn" },
  { id: "cbn", label: "CBN", kind: "agency", href: "/agencies/central-bank/nigeria" },
  { id: "ngx", label: "NGX", kind: "exchange", href: "/markets/exchanges/ngx-asi" },
  { id: "lagos", label: "Lagos", kind: "city", href: "/cities/lagos" },
  { id: "mtn-nigeria", label: "MTN Nigeria", kind: "company", href: "/companies/mtn-nigeria" },
  { id: "ng-banking", label: "Banking · Nigeria", kind: "industry", href: "/industries/banking/nigeria" },
  { id: "ng-policy-rate", label: "Policy rate · Nigeria", kind: "indicator", href: "/indicators/policy-rate/nigeria" },
  { id: "south-africa", label: "South Africa", kind: "country", href: "/countries/south-africa" },
  { id: "zar", label: "ZAR", kind: "currency", href: "/markets/currencies/usd-zar" },
  { id: "sarb", label: "SARB", kind: "agency", href: "/agencies/central-bank/south-africa" },
  { id: "jse", label: "JSE", kind: "exchange", href: "/markets/exchanges/jse-alsi" },
  { id: "johannesburg", label: "Johannesburg", kind: "city", href: "/cities/johannesburg" },
  { id: "standard-bank", label: "Standard Bank", kind: "company", href: "/companies/standard-bank" },
  { id: "za-banking", label: "Banking · South Africa", kind: "industry", href: "/industries/banking/south-africa" },
  { id: "egypt", label: "Egypt", kind: "country", href: "/countries/egypt" },
  { id: "egp", label: "EGP", kind: "currency", href: "/markets/currencies/usd-egp" },
  { id: "cbe", label: "CBE", kind: "agency", href: "/agencies/central-bank/egypt" },
  { id: "egx", label: "EGX", kind: "exchange", href: "/markets/exchanges/egx-30" },
  { id: "cairo", label: "Cairo", kind: "city", href: "/cities/cairo" },
  { id: "eg-energy", label: "Energy · Egypt", kind: "industry", href: "/industries/energy/egypt" },
  { id: "ghana", label: "Ghana", kind: "country", href: "/countries/ghana" },
  { id: "ghs", label: "GHS", kind: "currency", href: "/markets/currencies/usd-ghs" },
  { id: "bog", label: "BoG", kind: "agency", href: "/agencies/central-bank/ghana" },
  { id: "gse", label: "GSE", kind: "exchange", href: "/markets/exchanges/gse-ci" },
  { id: "accra", label: "Accra", kind: "city", href: "/cities/accra" },
  { id: "gh-banking", label: "Banking · Ghana", kind: "industry", href: "/industries/banking/ghana" },
  { id: "tema", label: "Tema", kind: "city", href: "/trade/ports/tema" },
  { id: "rwanda", label: "Rwanda", kind: "country", href: "/countries/rwanda" },
  { id: "rwf", label: "RWF", kind: "currency", href: "/markets/currencies/usd-rwf" },
  { id: "bnr", label: "BNR", kind: "agency", href: "/agencies/central-bank/rwanda" },
  { id: "kigali", label: "Kigali", kind: "city", href: "/cities/kigali" },
  { id: "rw-fintech", label: "Fintech · Rwanda", kind: "industry", href: "/technology/fintech/rwanda" },
  { id: "northern-corridor-rw", label: "Northern Corridor · Rwanda", kind: "corridor", href: "/trade/northern-corridor/rwanda" },
  { id: "uganda", label: "Uganda", kind: "country", href: "/countries/uganda" },
  { id: "ugx", label: "UGX", kind: "currency", href: "/markets/currencies/usd-ugx" },
  { id: "bou", label: "BoU", kind: "agency", href: "/agencies/central-bank/uganda" },
  { id: "kampala", label: "Kampala", kind: "city", href: "/cities/kampala" },
  { id: "northern-corridor-ug", label: "Northern Corridor · Uganda", kind: "corridor", href: "/trade/northern-corridor/uganda" },
  { id: "ug-agriculture", label: "Agriculture · Uganda", kind: "industry", href: "/industries/agriculture/uganda" },
  { id: "tanzania", label: "Tanzania", kind: "country", href: "/countries/tanzania" },
  { id: "tzs", label: "TZS", kind: "currency", href: "/markets/currencies/usd-tzs" },
  { id: "bot", label: "BoT", kind: "agency", href: "/agencies/central-bank/tanzania" },
  { id: "dar-es-salaam", label: "Dar es Salaam", kind: "city", href: "/cities/dar-es-salaam" },
  { id: "central-corridor", label: "Central Corridor", kind: "corridor", href: "/trade/central-corridor" },
  { id: "tz-ports", label: "Ports · Tanzania", kind: "industry", href: "/industries/logistics/tanzania" },
  { id: "ethiopia", label: "Ethiopia", kind: "country", href: "/countries/ethiopia" },
  { id: "etb", label: "ETB", kind: "currency", href: "/countries/ethiopia" },
  { id: "nbe", label: "NBE", kind: "agency", href: "/agencies/central-bank/ethiopia" },
  { id: "addis-ababa", label: "Addis Ababa", kind: "city", href: "/cities/addis-ababa" },
  { id: "et-agriculture", label: "Agriculture · Ethiopia", kind: "industry", href: "/industries/agriculture/ethiopia" },
  { id: "et-aviation", label: "Aviation · Ethiopia", kind: "industry", href: "/industries/logistics/ethiopia" },
  { id: "morocco", label: "Morocco", kind: "country", href: "/countries/morocco" },
  { id: "mad", label: "MAD", kind: "currency", href: "/markets/currencies/usd-mad" },
  { id: "bam", label: "BAM", kind: "agency", href: "/agencies/central-bank/morocco" },
  { id: "casablanca", label: "Casablanca", kind: "city", href: "/cities/casablanca" },
  { id: "ma-banking", label: "Banking · Morocco", kind: "industry", href: "/industries/banking/morocco" },
  { id: "ma-tourism", label: "Tourism · Morocco", kind: "industry", href: "/industries/tourism/morocco" },
  { id: "cote-divoire", label: "Côte d’Ivoire", kind: "country", href: "/countries/cote-divoire" },
  { id: "xof", label: "XOF", kind: "currency", href: "/markets/currencies/usd-xof" },
  { id: "bceao", label: "BCEAO", kind: "agency", href: "/agencies/central-bank/cote-divoire" },
  { id: "abidjan", label: "Abidjan", kind: "city", href: "/cities/abidjan" },
  { id: "ci-banking", label: "Banking · Côte d’Ivoire", kind: "industry", href: "/industries/banking/cote-divoire" },
  { id: "ci-cocoa", label: "Cocoa · Côte d’Ivoire", kind: "industry", href: "/industries/agriculture/cote-divoire" },
  { id: "angola", label: "Angola", kind: "country", href: "/countries/angola" },
  { id: "aoa", label: "AOA", kind: "currency", href: "/countries/angola" },
  { id: "luanda", label: "Luanda", kind: "city", href: "/cities/luanda" },
  { id: "lobito", label: "Lobito", kind: "city", href: "/trade/ports/lobito" },
  { id: "lobito-corridor", label: "Lobito Corridor", kind: "corridor", href: "/trade/lobito-corridor" },
  { id: "ao-energy", label: "Energy · Angola", kind: "industry", href: "/industries/energy/angola" },
  { id: "senegal", label: "Senegal", kind: "country", href: "/countries/senegal" },
  { id: "dakar", label: "Dakar", kind: "city", href: "/cities/dakar" },
  { id: "sn-energy", label: "Energy · Senegal", kind: "industry", href: "/industries/energy/senegal" },
  { id: "sn-ports", label: "Ports · Senegal", kind: "industry", href: "/industries/logistics/senegal" },
  { id: "mozambique", label: "Mozambique", kind: "country", href: "/countries/mozambique" },
  { id: "maputo", label: "Maputo", kind: "city", href: "/cities/maputo" },
  { id: "durban", label: "Durban", kind: "city", href: "/cities/durban" },
  { id: "maputo-corridor", label: "Maputo Corridor", kind: "corridor", href: "/trade/maputo-corridor" },
  { id: "mz-energy", label: "Energy · Mozambique", kind: "industry", href: "/industries/energy/mozambique" },
  { id: "zambia", label: "Zambia", kind: "country", href: "/countries/zambia" },
  { id: "zmw", label: "ZMW", kind: "currency", href: "/countries/zambia" },
  { id: "lusaka", label: "Lusaka", kind: "city", href: "/cities/lusaka" },
  { id: "zm-mining", label: "Mining · Zambia", kind: "industry", href: "/industries/mining/zambia" },
  { id: "zm-energy", label: "Energy · Zambia", kind: "industry", href: "/industries/energy/zambia" },
  { id: "tunisia", label: "Tunisia", kind: "country", href: "/countries/tunisia" },
  { id: "tnd", label: "TND", kind: "currency", href: "/countries/tunisia" },
  { id: "tunis", label: "Tunis", kind: "city", href: "/cities/tunis" },
  { id: "tn-industry", label: "Industry · Tunisia", kind: "industry", href: "/industries/industry/tunisia" },
  { id: "tn-tourism", label: "Tourism · Tunisia", kind: "industry", href: "/industries/tourism/tunisia" },
  { id: "algeria", label: "Algeria", kind: "country", href: "/countries/algeria" },
  { id: "dzd", label: "DZD", kind: "currency", href: "/countries/algeria" },
  { id: "algiers", label: "Algiers", kind: "city", href: "/cities/algiers" },
  { id: "dz-energy", label: "Energy · Algeria", kind: "industry", href: "/industries/energy/algeria" },
  { id: "dz-banking", label: "Banking · Algeria", kind: "industry", href: "/industries/banking/algeria" },
  { id: "botswana", label: "Botswana", kind: "country", href: "/countries/botswana" },
  { id: "bwp", label: "BWP", kind: "currency", href: "/countries/botswana" },
  { id: "gaborone", label: "Gaborone", kind: "city", href: "/cities/gaborone" },
  { id: "bw-mining", label: "Mining · Botswana", kind: "industry", href: "/industries/mining/botswana" },
  { id: "bw-banking", label: "Banking · Botswana", kind: "industry", href: "/industries/banking/botswana" },
  { id: "cameroon", label: "Cameroon", kind: "country", href: "/countries/cameroon" },
  { id: "xaf-cm", label: "XAF · CM", kind: "currency", href: "/countries/cameroon" },
  { id: "douala", label: "Douala", kind: "city", href: "/cities/douala" },
  { id: "cm-energy", label: "Energy · Cameroon", kind: "industry", href: "/industries/energy/cameroon" },
  { id: "cm-agriculture", label: "Agriculture · Cameroon", kind: "industry", href: "/industries/agriculture/cameroon" },
  { id: "namibia", label: "Namibia", kind: "country", href: "/countries/namibia" },
  { id: "nad", label: "NAD", kind: "currency", href: "/countries/namibia" },
  { id: "windhoek", label: "Windhoek", kind: "city", href: "/cities/windhoek" },
  { id: "na-mining", label: "Mining · Namibia", kind: "industry", href: "/industries/mining/namibia" },
  { id: "na-banking", label: "Banking · Namibia", kind: "industry", href: "/industries/banking/namibia" },
  { id: "walvis-bay", label: "Walvis Bay", kind: "city", href: "/trade/ports/walvis-bay" },
  { id: "trans-kalahari", label: "Trans-Kalahari Corridor", kind: "corridor", href: "/trade/trans-kalahari" },
  { id: "libya", label: "Libya", kind: "country", href: "/countries/libya" },
  { id: "lyd", label: "LYD", kind: "currency", href: "/countries/libya" },
  { id: "tripoli", label: "Tripoli", kind: "city", href: "/cities/tripoli" },
  { id: "ly-energy", label: "Energy · Libya", kind: "industry", href: "/industries/energy/libya" },
  { id: "ly-oil", label: "Oil · Libya", kind: "industry", href: "/industries/oil/libya" },
  { id: "zimbabwe", label: "Zimbabwe", kind: "country", href: "/countries/zimbabwe" },
  { id: "zwg", label: "ZWG", kind: "currency", href: "/countries/zimbabwe" },
  { id: "harare", label: "Harare", kind: "city", href: "/cities/harare" },
  { id: "beira", label: "Beira", kind: "city", href: "/trade/ports/beira" },
  { id: "beira-corridor", label: "Beira Corridor", kind: "corridor", href: "/trade/beira-corridor" },
  { id: "mauritius", label: "Mauritius", kind: "country", href: "/countries/mauritius" },
  { id: "mur", label: "MUR", kind: "currency", href: "/countries/mauritius" },
  { id: "port-louis", label: "Port Louis", kind: "city", href: "/cities/port-louis" },
  { id: "mu-finance", label: "Finance · Mauritius", kind: "industry", href: "/industries/finance/mauritius" },
  { id: "mu-services", label: "Services · Mauritius", kind: "industry", href: "/industries/services/mauritius" },
  { id: "djibouti", label: "Djibouti", kind: "country", href: "/countries/djibouti" },
  { id: "djf", label: "DJF", kind: "currency", href: "/countries/djibouti" },
  { id: "djibouti-city", label: "Djibouti City", kind: "city", href: "/cities/djibouti-city" },
  { id: "dj-ports", label: "Ports · Djibouti", kind: "industry", href: "/industries/logistics/djibouti" },
  { id: "dj-logistics", label: "Logistics · Djibouti", kind: "industry", href: "/industries/logistics/djibouti" },
];

export const graphEdges: GraphEdge[] = [
  {
    id: "ke-kes",
    from: "kenya",
    rel: "currency",
    to: "kes",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-cbk",
    from: "kenya",
    rel: "central bank",
    to: "cbk",
    source: "CBK official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cbk-policy",
    from: "cbk",
    rel: "policy",
    to: "policy-rate",
    source: "Indicator cell scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cbk-banks",
    from: "cbk",
    rel: "supervises",
    to: "banking",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cbk-governor",
    from: "cbk",
    rel: "role",
    to: "governor",
    source: "Role file — no invented name",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-nse",
    from: "kenya",
    rel: "exchange",
    to: "nse",
    source: "NSE official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-nairobi",
    from: "kenya",
    rel: "capital desk",
    to: "nairobi",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-mombasa",
    from: "kenya",
    rel: "port city",
    to: "mombasa",
    source: "City / port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-agri",
    from: "kenya",
    rel: "sector",
    to: "agriculture",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ke-energy",
    from: "kenya",
    rel: "sector",
    to: "energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "energy-costs",
    from: "energy",
    rel: "exposes",
    to: "inflation-costs",
    source: "Editorial scaffold — not a print",
    asOf: null,
    status: "demo",
  },
  {
    id: "ke-corridor",
    from: "kenya",
    rel: "corridor",
    to: "northern-corridor",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nse-saf",
    from: "nse",
    rel: "lists",
    to: "safaricom",
    source: "Issuer scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nse-equity",
    from: "nse",
    rel: "lists",
    to: "equity",
    source: "Issuer scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "banking-equity",
    from: "banking",
    rel: "issuer",
    to: "equity",
    source: "Company sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ng-ngn",
    from: "nigeria",
    rel: "currency",
    to: "ngn",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ng-cbn",
    from: "nigeria",
    rel: "central bank",
    to: "cbn",
    source: "CBN official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cbn-policy",
    from: "cbn",
    rel: "policy",
    to: "ng-policy-rate",
    source: "Indicator cell scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ng-ngx",
    from: "nigeria",
    rel: "exchange",
    to: "ngx",
    source: "NGX official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ng-lagos",
    from: "nigeria",
    rel: "commercial desk",
    to: "lagos",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ngx-mtn",
    from: "ngx",
    rel: "lists",
    to: "mtn-nigeria",
    source: "Issuer scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ng-banking",
    from: "nigeria",
    rel: "sector",
    to: "ng-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "za-zar",
    from: "south-africa",
    rel: "currency",
    to: "zar",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "za-sarb",
    from: "south-africa",
    rel: "central bank",
    to: "sarb",
    source: "SARB official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "za-jse",
    from: "south-africa",
    rel: "exchange",
    to: "jse",
    source: "JSE official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "za-jhb",
    from: "south-africa",
    rel: "markets desk",
    to: "johannesburg",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "jse-sbk",
    from: "jse",
    rel: "lists",
    to: "standard-bank",
    source: "Issuer scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "za-banking",
    from: "south-africa",
    rel: "sector",
    to: "za-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "eg-egp",
    from: "egypt",
    rel: "currency",
    to: "egp",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "eg-cbe",
    from: "egypt",
    rel: "central bank",
    to: "cbe",
    source: "CBE official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "eg-egx",
    from: "egypt",
    rel: "exchange",
    to: "egx",
    source: "EGX official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "eg-cairo",
    from: "egypt",
    rel: "capital desk",
    to: "cairo",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "eg-energy",
    from: "egypt",
    rel: "sector",
    to: "eg-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-ghs",
    from: "ghana",
    rel: "currency",
    to: "ghs",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-bog",
    from: "ghana",
    rel: "central bank",
    to: "bog",
    source: "BoG official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-gse",
    from: "ghana",
    rel: "exchange",
    to: "gse",
    source: "GSE official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-accra",
    from: "ghana",
    rel: "capital desk",
    to: "accra",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-banking",
    from: "ghana",
    rel: "sector",
    to: "gh-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "gh-tema",
    from: "ghana",
    rel: "port",
    to: "tema",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "rw-rwf",
    from: "rwanda",
    rel: "currency",
    to: "rwf",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "rw-bnr",
    from: "rwanda",
    rel: "central bank",
    to: "bnr",
    source: "BNR official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "rw-kigali",
    from: "rwanda",
    rel: "capital desk",
    to: "kigali",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "rw-fintech",
    from: "rwanda",
    rel: "sector",
    to: "rw-fintech",
    source: "Technology lens scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "rw-corridor",
    from: "rwanda",
    rel: "corridor",
    to: "northern-corridor-rw",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ug-ugx",
    from: "uganda",
    rel: "currency",
    to: "ugx",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ug-bou",
    from: "uganda",
    rel: "central bank",
    to: "bou",
    source: "BoU official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ug-kampala",
    from: "uganda",
    rel: "capital desk",
    to: "kampala",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ug-corridor",
    from: "uganda",
    rel: "corridor",
    to: "northern-corridor-ug",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ug-agri",
    from: "uganda",
    rel: "sector",
    to: "ug-agriculture",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tz-tzs",
    from: "tanzania",
    rel: "currency",
    to: "tzs",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tz-bot",
    from: "tanzania",
    rel: "central bank",
    to: "bot",
    source: "BoT official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tz-dar",
    from: "tanzania",
    rel: "port desk",
    to: "dar-es-salaam",
    source: "City / port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tz-corridor",
    from: "tanzania",
    rel: "corridor",
    to: "central-corridor",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tz-ports",
    from: "tanzania",
    rel: "sector",
    to: "tz-ports",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "et-etb",
    from: "ethiopia",
    rel: "currency",
    to: "etb",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "et-nbe",
    from: "ethiopia",
    rel: "central bank",
    to: "nbe",
    source: "NBE official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "et-addis",
    from: "ethiopia",
    rel: "capital desk",
    to: "addis-ababa",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "et-agri",
    from: "ethiopia",
    rel: "sector",
    to: "et-agriculture",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "et-aviation",
    from: "ethiopia",
    rel: "sector",
    to: "et-aviation",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nc-kenya",
    from: "northern-corridor",
    rel: "spans",
    to: "kenya",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nc-uganda",
    from: "northern-corridor",
    rel: "spans",
    to: "uganda",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nc-rwanda",
    from: "northern-corridor",
    rel: "spans",
    to: "rwanda",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "nc-mombasa",
    from: "northern-corridor",
    rel: "gateway",
    to: "mombasa",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ma-mad",
    from: "morocco",
    rel: "currency",
    to: "mad",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ma-bam",
    from: "morocco",
    rel: "central bank",
    to: "bam",
    source: "BAM official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ma-casa",
    from: "morocco",
    rel: "markets desk",
    to: "casablanca",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ma-banking",
    from: "morocco",
    rel: "sector",
    to: "ma-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ma-tourism",
    from: "morocco",
    rel: "sector",
    to: "ma-tourism",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cc-tanzania",
    from: "central-corridor",
    rel: "spans",
    to: "tanzania",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cc-rwanda",
    from: "central-corridor",
    rel: "spans",
    to: "rwanda",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cc-dar",
    from: "central-corridor",
    rel: "gateway",
    to: "dar-es-salaam",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ci-xof",
    from: "cote-divoire",
    rel: "currency",
    to: "xof",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ci-bceao",
    from: "cote-divoire",
    rel: "central bank",
    to: "bceao",
    source: "BCEAO official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ci-abidjan",
    from: "cote-divoire",
    rel: "commercial desk",
    to: "abidjan",
    source: "City / port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ci-banking",
    from: "cote-divoire",
    rel: "sector",
    to: "ci-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ci-cocoa",
    from: "cote-divoire",
    rel: "sector",
    to: "ci-cocoa",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ao-aoa",
    from: "angola",
    rel: "currency",
    to: "aoa",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ao-luanda",
    from: "angola",
    rel: "capital desk",
    to: "luanda",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ao-lobito",
    from: "angola",
    rel: "port",
    to: "lobito",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ao-energy",
    from: "angola",
    rel: "sector",
    to: "ao-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "lc-angola",
    from: "lobito-corridor",
    rel: "spans",
    to: "angola",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "lc-lobito",
    from: "lobito-corridor",
    rel: "gateway",
    to: "lobito",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "sn-xof",
    from: "senegal",
    rel: "currency",
    to: "xof",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "sn-bceao",
    from: "senegal",
    rel: "central bank",
    to: "bceao",
    source: "BCEAO official door",
    asOf: null,
    status: "editorial",
  },
  {
    id: "sn-dakar",
    from: "senegal",
    rel: "capital desk",
    to: "dakar",
    source: "City / port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "sn-energy",
    from: "senegal",
    rel: "sector",
    to: "sn-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "sn-ports",
    from: "senegal",
    rel: "sector",
    to: "sn-ports",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mz-maputo",
    from: "mozambique",
    rel: "capital desk",
    to: "maputo",
    source: "City / port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mz-energy",
    from: "mozambique",
    rel: "sector",
    to: "mz-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mc-mozambique",
    from: "maputo-corridor",
    rel: "spans",
    to: "mozambique",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mc-south-africa",
    from: "maputo-corridor",
    rel: "spans",
    to: "south-africa",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mc-maputo",
    from: "maputo-corridor",
    rel: "gateway",
    to: "maputo",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mc-durban",
    from: "maputo-corridor",
    rel: "peer port",
    to: "durban",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zm-zmw",
    from: "zambia",
    rel: "currency",
    to: "zmw",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zm-lusaka",
    from: "zambia",
    rel: "capital desk",
    to: "lusaka",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zm-mining",
    from: "zambia",
    rel: "sector",
    to: "zm-mining",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zm-energy",
    from: "zambia",
    rel: "sector",
    to: "zm-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "lc-zambia",
    from: "lobito-corridor",
    rel: "spans",
    to: "zambia",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tn-tnd",
    from: "tunisia",
    rel: "currency",
    to: "tnd",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tn-tunis",
    from: "tunisia",
    rel: "capital desk",
    to: "tunis",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tn-industry",
    from: "tunisia",
    rel: "sector",
    to: "tn-industry",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tn-tourism",
    from: "tunisia",
    rel: "sector",
    to: "tn-tourism",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dz-dzd",
    from: "algeria",
    rel: "currency",
    to: "dzd",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dz-algiers",
    from: "algeria",
    rel: "capital desk",
    to: "algiers",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dz-energy",
    from: "algeria",
    rel: "sector",
    to: "dz-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dz-banking",
    from: "algeria",
    rel: "sector",
    to: "dz-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bw-bwp",
    from: "botswana",
    rel: "currency",
    to: "bwp",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bw-gaborone",
    from: "botswana",
    rel: "capital desk",
    to: "gaborone",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bw-mining",
    from: "botswana",
    rel: "sector",
    to: "bw-mining",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bw-banking",
    from: "botswana",
    rel: "sector",
    to: "bw-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cm-xaf",
    from: "cameroon",
    rel: "currency",
    to: "xaf-cm",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cm-douala",
    from: "cameroon",
    rel: "commercial desk",
    to: "douala",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cm-energy",
    from: "cameroon",
    rel: "sector",
    to: "cm-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "cm-agriculture",
    from: "cameroon",
    rel: "sector",
    to: "cm-agriculture",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "na-nad",
    from: "namibia",
    rel: "currency",
    to: "nad",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "na-windhoek",
    from: "namibia",
    rel: "capital desk",
    to: "windhoek",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "na-mining",
    from: "namibia",
    rel: "sector",
    to: "na-mining",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "na-banking",
    from: "namibia",
    rel: "sector",
    to: "na-banking",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-namibia",
    from: "trans-kalahari",
    rel: "spans",
    to: "namibia",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-botswana",
    from: "trans-kalahari",
    rel: "spans",
    to: "botswana",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-south-africa",
    from: "trans-kalahari",
    rel: "spans",
    to: "south-africa",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-walvis",
    from: "trans-kalahari",
    rel: "gateway",
    to: "walvis-bay",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-gaborone",
    from: "trans-kalahari",
    rel: "node",
    to: "gaborone",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "tk-johannesburg",
    from: "trans-kalahari",
    rel: "node",
    to: "johannesburg",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ly-lyd",
    from: "libya",
    rel: "currency",
    to: "lyd",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ly-tripoli",
    from: "libya",
    rel: "capital desk",
    to: "tripoli",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ly-energy",
    from: "libya",
    rel: "sector",
    to: "ly-energy",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "ly-oil",
    from: "libya",
    rel: "sector",
    to: "ly-oil",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zw-zwg",
    from: "zimbabwe",
    rel: "currency",
    to: "zwg",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "zw-harare",
    from: "zimbabwe",
    rel: "capital desk",
    to: "harare",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bc-mozambique",
    from: "beira-corridor",
    rel: "spans",
    to: "mozambique",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bc-zimbabwe",
    from: "beira-corridor",
    rel: "spans",
    to: "zimbabwe",
    source: "Trade corridor file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bc-beira",
    from: "beira-corridor",
    rel: "gateway",
    to: "beira",
    source: "Port file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "bc-harare",
    from: "beira-corridor",
    rel: "node",
    to: "harare",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mu-mur",
    from: "mauritius",
    rel: "currency",
    to: "mur",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mu-port-louis",
    from: "mauritius",
    rel: "capital desk",
    to: "port-louis",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mu-finance",
    from: "mauritius",
    rel: "sector",
    to: "mu-finance",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "mu-services",
    from: "mauritius",
    rel: "sector",
    to: "mu-services",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dj-djf",
    from: "djibouti",
    rel: "currency",
    to: "djf",
    source: "Editorial scaffold",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dj-city",
    from: "djibouti",
    rel: "capital desk",
    to: "djibouti-city",
    source: "City file",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dj-ports",
    from: "djibouti",
    rel: "sector",
    to: "dj-ports",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
  {
    id: "dj-logistics",
    from: "djibouti",
    rel: "sector",
    to: "dj-logistics",
    source: "Country sector tag",
    asOf: null,
    status: "editorial",
  },
];

export const graphDesks = [
  {
    slug: "kenya",
    label: "Kenya desk",
    lede: "First populated edges. Every node opens a file or stays blank without a source.",
    nodeIds: [
      "kenya",
      "kes",
      "cbk",
      "nse",
      "nairobi",
      "mombasa",
      "banking",
      "agriculture",
      "energy",
      "policy-rate",
      "northern-corridor",
      "safaricom",
      "equity",
      "governor",
      "inflation-costs",
    ],
  },
  {
    slug: "nigeria",
    label: "Nigeria desk",
    lede: "CBN, NGX, Lagos and issuer scaffolds. No invented prints.",
    nodeIds: ["nigeria", "ngn", "cbn", "ngx", "lagos", "mtn-nigeria", "ng-banking", "ng-policy-rate"],
  },
  {
    slug: "south-africa",
    label: "South Africa desk",
    lede: "SARB, JSE and Johannesburg markets desk. Amounts stay blank until cited.",
    nodeIds: ["south-africa", "zar", "sarb", "jse", "johannesburg", "standard-bank", "za-banking"],
  },
  {
    slug: "egypt",
    label: "Egypt desk",
    lede: "CBE, EGX and Cairo. Energy sector tagged from the country file.",
    nodeIds: ["egypt", "egp", "cbe", "egx", "cairo", "eg-energy"],
  },
  {
    slug: "ghana",
    label: "Ghana desk",
    lede: "BoG, GSE, Accra and Tema. No invented prints.",
    nodeIds: ["ghana", "ghs", "bog", "gse", "accra", "gh-banking", "tema"],
  },
  {
    slug: "rwanda",
    label: "Rwanda desk",
    lede: "BNR, Kigali and Northern Corridor scaffolds. Fintech lens empty until cited.",
    nodeIds: ["rwanda", "rwf", "bnr", "kigali", "rw-fintech", "northern-corridor-rw"],
  },
  {
    slug: "uganda",
    label: "Uganda desk",
    lede: "BoU, Kampala and Northern Corridor. Agriculture sector tagged — no invented prints.",
    nodeIds: ["uganda", "ugx", "bou", "kampala", "northern-corridor-ug", "ug-agriculture"],
  },
  {
    slug: "tanzania",
    label: "Tanzania desk",
    lede: "BoT, Dar es Salaam and Central Corridor. Port sector empty until cited.",
    nodeIds: ["tanzania", "tzs", "bot", "dar-es-salaam", "central-corridor", "tz-ports"],
  },
  {
    slug: "ethiopia",
    label: "Ethiopia desk",
    lede: "NBE, Addis Ababa, agriculture and aviation scaffolds. No invented prints.",
    nodeIds: ["ethiopia", "etb", "nbe", "addis-ababa", "et-agriculture", "et-aviation"],
  },
  {
    slug: "northern-corridor",
    label: "Northern Corridor desk",
    lede: "Cross-border scaffold spanning Kenya, Uganda and Rwanda. Volumes unpublished.",
    nodeIds: [
      "northern-corridor",
      "kenya",
      "uganda",
      "rwanda",
      "mombasa",
      "kampala",
      "kigali",
      "northern-corridor-ug",
      "northern-corridor-rw",
    ],
  },
  {
    slug: "morocco",
    label: "Morocco desk",
    lede: "BAM, Casablanca, banking and tourism scaffolds. No invented prints.",
    nodeIds: ["morocco", "mad", "bam", "casablanca", "ma-banking", "ma-tourism"],
  },
  {
    slug: "central-corridor",
    label: "Central Corridor desk",
    lede: "Dar es Salaam — Rwanda scaffold. Throughput blank until sourced.",
    nodeIds: ["central-corridor", "tanzania", "rwanda", "dar-es-salaam", "kigali", "tz-ports"],
  },
  {
    slug: "cote-divoire",
    label: "Côte d’Ivoire desk",
    lede: "BCEAO, Abidjan, banking and cocoa scaffolds. No invented prints.",
    nodeIds: ["cote-divoire", "xof", "bceao", "abidjan", "ci-banking", "ci-cocoa"],
  },
  {
    slug: "angola",
    label: "Angola desk",
    lede: "Luanda, Lobito and energy sector tags. FX cells blank until cited.",
    nodeIds: ["angola", "aoa", "luanda", "lobito", "ao-energy"],
  },
  {
    slug: "lobito-corridor",
    label: "Lobito Corridor desk",
    lede: "Atlantic gateway scaffold spanning Angola and Zambia. Throughput unpublished.",
    nodeIds: ["lobito-corridor", "angola", "zambia", "lobito", "luanda", "lusaka", "ao-energy", "zm-mining"],
  },
  {
    slug: "senegal",
    label: "Senegal desk",
    lede: "BCEAO, Dakar, energy and ports scaffolds. No invented prints.",
    nodeIds: ["senegal", "xof", "bceao", "dakar", "sn-energy", "sn-ports"],
  },
  {
    slug: "mozambique",
    label: "Mozambique desk",
    lede: "Maputo and energy sector tags. LNG figures stay blank until cited.",
    nodeIds: ["mozambique", "maputo", "mz-energy"],
  },
  {
    slug: "maputo-corridor",
    label: "Maputo Corridor desk",
    lede: "Maputo — South Africa scaffold. Throughput unpublished.",
    nodeIds: ["maputo-corridor", "mozambique", "south-africa", "maputo", "durban", "johannesburg"],
  },
  {
    slug: "zambia",
    label: "Zambia desk",
    lede: "Lusaka, copperbelt mining and energy scaffolds. No invented prints.",
    nodeIds: ["zambia", "zmw", "lusaka", "zm-mining", "zm-energy"],
  },
  {
    slug: "tunisia",
    label: "Tunisia desk",
    lede: "Tunis, industry and tourism scaffolds. FX cells blank until cited.",
    nodeIds: ["tunisia", "tnd", "tunis", "tn-industry", "tn-tourism"],
  },
  {
    slug: "algeria",
    label: "Algeria desk",
    lede: "Algiers, energy and banking scaffolds. No invented prints.",
    nodeIds: ["algeria", "dzd", "algiers", "dz-energy", "dz-banking"],
  },
  {
    slug: "botswana",
    label: "Botswana desk",
    lede: "Gaborone, mining and banking scaffolds. FX cells blank until cited.",
    nodeIds: ["botswana", "bwp", "gaborone", "bw-mining", "bw-banking"],
  },
  {
    slug: "cameroon",
    label: "Cameroon desk",
    lede: "Douala, energy and agriculture scaffolds. No invented prints.",
    nodeIds: ["cameroon", "xaf-cm", "douala", "cm-energy", "cm-agriculture"],
  },
  {
    slug: "namibia",
    label: "Namibia desk",
    lede: "Windhoek, mining and banking scaffolds. FX cells blank until cited.",
    nodeIds: ["namibia", "nad", "windhoek", "na-mining", "na-banking"],
  },
  {
    slug: "trans-kalahari",
    label: "Trans-Kalahari Corridor",
    lede: "Walvis Bay — Windhoek — Gaborone — Johannesburg. Volumes blank until sourced.",
    nodeIds: [
      "trans-kalahari",
      "namibia",
      "botswana",
      "south-africa",
      "walvis-bay",
      "windhoek",
      "gaborone",
      "johannesburg",
    ],
  },
  {
    slug: "libya",
    label: "Libya desk",
    lede: "Tripoli, energy and oil scaffolds. No invented prints.",
    nodeIds: ["libya", "lyd", "tripoli", "ly-energy", "ly-oil"],
  },
  {
    slug: "zimbabwe",
    label: "Zimbabwe desk",
    lede: "Harare scaffold for Beira hinterland. FX cells blank until cited.",
    nodeIds: ["zimbabwe", "zwg", "harare"],
  },
  {
    slug: "beira-corridor",
    label: "Beira Corridor",
    lede: "Beira — Harare hinterland scaffold. Throughput unpublished.",
    nodeIds: ["beira-corridor", "mozambique", "zimbabwe", "beira", "harare", "maputo"],
  },
  {
    slug: "mauritius",
    label: "Mauritius desk",
    lede: "Port Louis, finance and services scaffolds. FX cells blank until cited.",
    nodeIds: ["mauritius", "mur", "port-louis", "mu-finance", "mu-services"],
  },
  {
    slug: "djibouti",
    label: "Djibouti desk",
    lede: "Port and logistics scaffolds. Volumes blank until sourced.",
    nodeIds: ["djibouti", "djf", "djibouti-city", "dj-ports", "dj-logistics"],
  },
] as const;

export function getGraphNode(id: string) {
  return graphNodes.find((node) => node.id === id);
}

export function getGraphDesk(slug: string) {
  return graphDesks.find((desk) => desk.slug === slug);
}

export function edgesForDesk(slug: string) {
  const desk = getGraphDesk(slug);
  if (!desk) return [];
  const allowed = new Set<string>(desk.nodeIds);
  return graphEdges.filter((edge) => allowed.has(edge.from) && allowed.has(edge.to));
}

export function edgesForNode(nodeId: string) {
  return graphEdges.filter((edge) => edge.from === nodeId || edge.to === nodeId);
}

export function graphFileHref(slug: string) {
  return `/graph/${slug}`;
}
