export type SystemSurface = {
  id: string;
  label: string;
  state: "live" | "scaffold" | "offline";
  note: string;
  href?: string;
};

/** Honest product status. Never invent a green light for a dark store. */
export const systemSurfaces: SystemSurface[] = [
  {
    id: "editorial-md",
    label: "Filesystem Markdown desk",
    state: "live",
    note: "Kenya desk articles and briefs ship from /content.",
    href: "/today",
  },
  {
    id: "country-terminals",
    label: "Country terminals",
    state: "live",
    note: "54 shells. Observation cells stay blank until sourced.",
    href: "/countries",
  },
  {
    id: "graph-desks",
    label: "Graph desks",
    state: "scaffold",
    note: "Featured desks are editorial. Resolution jobs are not scheduled.",
    href: "/graph",
  },
  {
    id: "ask-rag",
    label: "Ask / RAG index",
    state: "offline",
    note: "Corpus slots exist. Embeddings and retrieval are not connected.",
    href: "/ask/corpus",
  },
  {
    id: "auth-billing",
    label: "Auth + billing",
    state: "offline",
    note: "Every visitor is Free. Checkout stubs only.",
    href: "/account",
  },
  {
    id: "api-keys",
    label: "API keys",
    state: "offline",
    note: "Catalogue is public. Keys are not issued.",
    href: "/developers",
  },
  {
    id: "exports",
    label: "Export mint",
    state: "offline",
    note: "Packages are product shape. No CSV is minted.",
    href: "/exports",
  },
  {
    id: "ingestion",
    label: "Ingestion runner",
    state: "offline",
    note: "Ops board lists stubs. No cron against a live queue.",
    href: "/ingestion",
  },
  {
    id: "feeds",
    label: "Enterprise feeds",
    state: "offline",
    note: "Catalogue only. No licensed delivery.",
    href: "/feeds",
  },
  {
    id: "notifications",
    label: "Notification delivery",
    state: "offline",
    note: "Channels listed. Nothing is pushed.",
    href: "/notifications",
  },
  {
    id: "licensing",
    label: "Enterprise licensing",
    state: "offline",
    note: "Catalogue only. No fake quotes.",
    href: "/licensing",
  },
  {
    id: "audit",
    label: "Editorial audit log",
    state: "offline",
    note: "Action kinds listed. Event store empty.",
    href: "/audit",
  },
  {
    id: "reports",
    label: "Research reports",
    state: "scaffold",
    note: "Memo shells. Published count is zero.",
    href: "/reports",
  },
  {
    id: "calendar",
    label: "Desk calendar",
    state: "offline",
    note: "Slots listed. Dates blank until cited.",
    href: "/calendar",
  },
  {
    id: "partners",
    label: "Partner inventory",
    state: "offline",
    note: "Sponsor surfaces empty. Editorial separate.",
    href: "/partners",
  },
  {
    id: "coverage",
    label: "Coverage board",
    state: "scaffold",
    note: "Honest scaffold counts. No vanity score.",
    href: "/coverage",
  },
  {
    id: "webhooks",
    label: "Webhook delivery",
    state: "offline",
    note: "Catalogue only. Nothing armed.",
    href: "/webhooks",
  },
  {
    id: "onboarding",
    label: "Seat onboarding",
    state: "scaffold",
    note: "Steps open. Progress store empty.",
    href: "/onboarding",
  },
  {
    id: "regions",
    label: "Regional hubs",
    state: "scaffold",
    note: "Five region indexes. No regional scoreboard.",
    href: "/regions",
  },
  {
    id: "runbooks",
    label: "Desk runbooks",
    state: "scaffold",
    note: "SOP shells. Empty until steps are filed.",
    href: "/runbooks",
  },
  {
    id: "layers",
    label: "Intelligence layers",
    state: "scaffold",
    note: "NEWS→DECISIONS map. Decisions layer offline.",
    href: "/layers",
  },
  {
    id: "press",
    label: "Press kit",
    state: "scaffold",
    note: "Media assets mostly empty. No KPI PDF.",
    href: "/press",
  },
  {
    id: "golive",
    label: "Go-live gates",
    state: "scaffold",
    note: "Blocked gates listed. No fake green lights.",
    href: "/golive",
  },
  {
    id: "social",
    label: "LinkedIn / social",
    state: "scaffold",
    note: "Company page linked. Share intents live. No post scheduler.",
    href: "/social",
  },
  {
    id: "embeds",
    label: "Embed widgets",
    state: "scaffold",
    note: "Catalogue only. No iframe or white-label key issued.",
    href: "/embeds",
  },
  {
    id: "security",
    label: "Security / trust",
    state: "scaffold",
    note: "Control list published. SOC 2 and pen-test remain empty.",
    href: "/security",
  },
  {
    id: "integrations",
    label: "Integrations",
    state: "scaffold",
    note: "Catalogue only. No Slack, Teams or Zap connected.",
    href: "/integrations",
  },
  {
    id: "sla",
    label: "SLA commitments",
    state: "scaffold",
    note: "Shapes only. No contracted uptime percentage.",
    href: "/sla",
  },
  {
    id: "brand",
    label: "Brand kit",
    state: "scaffold",
    note: "Live names on site. Download packs empty.",
    href: "/brand",
  },
  {
    id: "roadmap",
    label: "Public roadmap",
    state: "scaffold",
    note: "Derived from changelog + gates. No fake dates.",
    href: "/roadmap",
  },
  {
    id: "accessibility",
    label: "Accessibility",
    state: "scaffold",
    note: "Honest posture. WCAG claim untested.",
    href: "/accessibility",
  },
  {
    id: "sdk",
    label: "SDK catalogue",
    state: "scaffold",
    note: "Catalogue only. No npm/PyPI publish.",
    href: "/sdk",
  },
  {
    id: "templates",
    label: "Desk templates",
    state: "scaffold",
    note: "Outlines only. No minted fills.",
    href: "/templates",
  },
  {
    id: "support",
    label: "Support doors",
    state: "scaffold",
    note: "Open pages linked. Ticket queue offline.",
    href: "/support",
  },
  {
    id: "newsletters",
    label: "Newsletters",
    state: "scaffold",
    note: "Catalogue only. Mail runner offline.",
    href: "/newsletters",
  },
  {
    id: "careers",
    label: "Careers",
    state: "scaffold",
    note: "Role shapes only. No open posts.",
    href: "/careers",
  },
  {
    id: "contact",
    label: "Contact",
    state: "scaffold",
    note: "Doors only. Form delivery offline.",
    href: "/contact",
  },
  {
    id: "faq",
    label: "FAQ",
    state: "scaffold",
    note: "Honest product answers. No fake coverage.",
    href: "/faq",
  },
  {
    id: "cookies",
    label: "Cookies",
    state: "scaffold",
    note: "Posture only. No consent invent.",
    href: "/legal/cookies",
  },
  {
    id: "trust",
    label: "Trust center",
    state: "scaffold",
    note: "Index of method, security, SLA and gates.",
    href: "/trust",
  },
  {
    id: "credits",
    label: "Credits",
    state: "scaffold",
    note: "House and stack lines. No fake partners.",
    href: "/credits",
  },
  {
    id: "manifesto",
    label: "Manifesto",
    state: "scaffold",
    note: "Principles only. No coverage invent.",
    href: "/manifesto",
  },
  {
    id: "imprint",
    label: "Imprint",
    state: "scaffold",
    note: "Publisher notice. Address fields empty.",
    href: "/imprint",
  },
  {
    id: "syndication",
    label: "Syndication",
    state: "scaffold",
    note: "RSS, sitemap and status doors. No audience or uptime figures.",
    href: "/syndication",
  },
  {
    id: "notices",
    label: "Notices",
    state: "scaffold",
    note: "Notice slots. Nothing posted.",
    href: "/notices",
  },
  {
    id: "languages",
    label: "Languages",
    state: "scaffold",
    note: "English is live. Other editions empty.",
    href: "/languages",
  },
  {
    id: "units",
    label: "Units",
    state: "scaffold",
    note: "Unit words only. No series stored.",
    href: "/units",
  },
  {
    id: "correspondents",
    label: "Correspondents",
    state: "scaffold",
    note: "Seats only. No invented bylines.",
    href: "/correspondents",
  },
  {
    id: "citations",
    label: "Citations",
    state: "scaffold",
    note: "Citation shapes. No sample print.",
    href: "/citations",
  },
  {
    id: "corridors",
    label: "Corridors",
    state: "scaffold",
    note: "Named routes. No volumes stored.",
    href: "/corridors",
  },
  {
    id: "identifiers",
    label: "Identifiers",
    state: "scaffold",
    note: "Code words only. No crosswalk.",
    href: "/identifiers",
  },
  {
    id: "series",
    label: "Series",
    state: "scaffold",
    note: "Series shapes. No observations.",
    href: "/series",
  },
  {
    id: "revisions",
    label: "Revisions",
    state: "scaffold",
    note: "Revision shapes. Nothing posted.",
    href: "/revisions",
  },
  {
    id: "classifications",
    label: "Classifications",
    state: "scaffold",
    note: "Grouping words. No code table.",
    href: "/classifications",
  },
  {
    id: "releases",
    label: "Releases",
    state: "scaffold",
    note: "Release shapes. No date scheduled.",
    href: "/releases",
  },
  {
    id: "datelines",
    label: "Datelines",
    state: "scaffold",
    note: "Places only. No story filed.",
    href: "/datelines",
  },
  {
    id: "borders",
    label: "Borders",
    state: "scaffold",
    note: "Border shapes. Nothing recorded.",
    href: "/borders",
  },
  {
    id: "customs",
    label: "Customs",
    state: "scaffold",
    note: "Customs shapes. Nothing filed.",
    href: "/customs",
  },
  {
    id: "modes",
    label: "Modes",
    state: "scaffold",
    note: "Mode words. No tonnage stored.",
    href: "/modes",
  },
  {
    id: "observations",
    label: "Observations",
    state: "scaffold",
    note: "Observation shapes. No dated print.",
    href: "/observations",
  },
  {
    id: "frequencies",
    label: "Frequencies",
    state: "scaffold",
    note: "Frequency words. No calendar.",
    href: "/frequencies",
  },
  {
    id: "vintages",
    label: "Vintages",
    state: "scaffold",
    note: "Vintage shapes. Nothing posted.",
    href: "/vintages",
  },
  {
    id: "lineage",
    label: "Lineage",
    state: "scaffold",
    note: "Lineage shapes. No source chain.",
    href: "/lineage",
  },
  {
    id: "gaps",
    label: "Gaps",
    state: "scaffold",
    note: "Gap shapes. No missing date.",
    href: "/gaps",
  },
  {
    id: "periods",
    label: "Periods",
    state: "scaffold",
    note: "Period words. No window.",
    href: "/periods",
  },
  {
    id: "lags",
    label: "Lags",
    state: "scaffold",
    note: "Lag shapes. No delay.",
    href: "/lags",
  },
  {
    id: "benchmarks",
    label: "Benchmarks",
    state: "scaffold",
    note: "Benchmark shapes. No reference print.",
    href: "/benchmarks",
  },
  {
    id: "baskets",
    label: "Baskets",
    state: "scaffold",
    note: "Basket shapes. No weight.",
    href: "/baskets",
  },
  {
    id: "thresholds",
    label: "Thresholds",
    state: "scaffold",
    note: "Threshold shapes. No level.",
    href: "/thresholds",
  },
  {
    id: "peers",
    label: "Peers",
    state: "scaffold",
    note: "Peer shapes. No comparison set.",
    href: "/peers",
  },
  {
    id: "weights",
    label: "Weights",
    state: "scaffold",
    note: "Weight shapes. No share.",
    href: "/weights",
  },
  {
    id: "constituents",
    label: "Constituents",
    state: "scaffold",
    note: "Constituent shapes. No member.",
    href: "/constituents",
  },
  {
    id: "horizons",
    label: "Horizons",
    state: "scaffold",
    note: "Horizon words. No forecast.",
    href: "/horizons",
  },
  {
    id: "baselines",
    label: "Baselines",
    state: "scaffold",
    note: "Baseline shapes. No starting print.",
    href: "/baselines",
  },
  {
    id: "spreads",
    label: "Spreads",
    state: "scaffold",
    note: "Spread shapes. No gap.",
    href: "/spreads",
  },
  {
    id: "seasons",
    label: "Seasons",
    state: "scaffold",
    note: "Season words. No window.",
    href: "/seasons",
  },
  {
    id: "adjustments",
    label: "Adjustments",
    state: "scaffold",
    note: "Adjustment shapes. No factor.",
    href: "/adjustments",
  },
  {
    id: "footnotes",
    label: "Footnotes",
    state: "scaffold",
    note: "Footnote shapes. No caveat.",
    href: "/footnotes",
  },
  {
    id: "scales",
    label: "Scales",
    state: "scaffold",
    note: "Scale words. No transform.",
    href: "/scales",
  },
  {
    id: "precision",
    label: "Precision",
    state: "scaffold",
    note: "Precision shapes. No fineness.",
    href: "/precision",
  },
  {
    id: "rounding",
    label: "Rounding",
    state: "scaffold",
    note: "Rounding shapes. No convention.",
    href: "/rounding",
  },
  {
    id: "crosswalks",
    label: "Crosswalks",
    state: "scaffold",
    note: "Crosswalk shapes. No map.",
    href: "/crosswalks",
  },
  {
    id: "aliases",
    label: "Aliases",
    state: "scaffold",
    note: "Alias shapes. No other name.",
    href: "/aliases",
  },
  {
    id: "embargoes",
    label: "Embargoes",
    state: "scaffold",
    note: "Embargo shapes. No hold.",
    href: "/embargoes",
  },
  {
    id: "sessions",
    label: "Sessions",
    state: "scaffold",
    note: "Session words. No clock time.",
    href: "/sessions",
  },
  {
    id: "holidays",
    label: "Holidays",
    state: "scaffold",
    note: "Holiday shapes. No date.",
    href: "/holidays",
  },
  {
    id: "factors",
    label: "Factors",
    state: "scaffold",
    note: "Factor shapes. No conversion.",
    href: "/factors",
  },
  {
    id: "tenors",
    label: "Tenors",
    state: "scaffold",
    note: "Tenor words. No maturity date.",
    href: "/tenors",
  },
  {
    id: "grades",
    label: "Grades",
    state: "scaffold",
    note: "Grade shapes. No specification.",
    href: "/grades",
  },
  {
    id: "flags",
    label: "Flags",
    state: "scaffold",
    note: "Flag words. No quality mark.",
    href: "/flags",
  },
  {
    id: "windows",
    label: "Windows",
    state: "scaffold",
    note: "Window shapes. No span of time.",
    href: "/windows",
  },
  {
    id: "cutoffs",
    label: "Cutoffs",
    state: "scaffold",
    note: "Cutoff shapes. No clock time.",
    href: "/cutoffs",
  },
  {
    id: "stamps",
    label: "Stamps",
    state: "scaffold",
    note: "Stamp shapes. No as-of date.",
    href: "/stamps",
  },
  {
    id: "breaks",
    label: "Breaks",
    state: "scaffold",
    note: "Break shapes. No series split.",
    href: "/breaks",
  },
  {
    id: "curves",
    label: "Curves",
    state: "scaffold",
    note: "Curve shapes. No plot.",
    href: "/curves",
  },
  {
    id: "fixes",
    label: "Fixes",
    state: "scaffold",
    note: "Fixing shapes. No rate.",
    href: "/fixes",
  },
  {
    id: "lots",
    label: "Lots",
    state: "scaffold",
    note: "Lot shapes. No parcel.",
    href: "/lots",
  },
  {
    id: "quotes",
    label: "Quotes",
    state: "scaffold",
    note: "Quote shapes. No price.",
    href: "/quotes",
  },
  {
    id: "contracts",
    label: "Contracts",
    state: "scaffold",
    note: "Contract shapes. No agreement.",
    href: "/contracts",
  },
  {
    id: "samples",
    label: "Samples",
    state: "scaffold",
    note: "Sample shapes. No draw.",
    href: "/samples",
  },
  {
    id: "indices",
    label: "Indices",
    state: "scaffold",
    note: "Index shapes. No basket.",
    href: "/indices",
  },
  {
    id: "manifests",
    label: "Manifests",
    state: "scaffold",
    note: "Manifest shapes. No cargo list.",
    href: "/manifests",
  },
  {
    id: "parcels",
    label: "Parcels",
    state: "scaffold",
    note: "Parcel shapes. No shipment.",
    href: "/parcels",
  },
  {
    id: "draws",
    label: "Draws",
    state: "scaffold",
    note: "Draw shapes. No selection.",
    href: "/draws",
  },
];

export function surfacesByState(state: SystemSurface["state"]) {
  return systemSurfaces.filter((item) => item.state === state);
}
