export const corridors = [
  {
    slug: "northern-corridor",
    name: "Northern Corridor",
    geography: "Mombasa — Nairobi — Kampala — Kigali — Bujumbura / South Sudan",
    modes: ["Port", "Road", "Rail", "Border posts"],
    countrySlugs: ["kenya", "uganda", "rwanda", "burundi", "south-sudan"],
    note: "Volumes, dwell times and disruption series are not connected.",
  },
  {
    slug: "central-corridor",
    name: "Central Corridor",
    geography: "Dar es Salaam — Dodoma — Kigali / Bujumbura / DRC",
    modes: ["Port", "Rail", "Road"],
    countrySlugs: ["tanzania", "rwanda", "burundi", "dr-congo"],
    note: "Awaiting licensed logistics and customs prints.",
  },
  {
    slug: "lobito-corridor",
    name: "Lobito Corridor",
    geography: "Lobito — DRC Copperbelt — Zambia",
    modes: ["Port", "Rail"],
    countrySlugs: ["angola", "dr-congo", "zambia"],
    note: "Project and throughput figures stay blank until sourced.",
  },
  {
    slug: "maputo-corridor",
    name: "Maputo Corridor",
    geography: "Maputo — Mpumalanga — Gauteng",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["mozambique", "south-africa"],
    note: "No invented trade volumes.",
  },
  {
    slug: "trans-kalahari",
    name: "Trans-Kalahari Corridor",
    geography: "Walvis Bay — Windhoek — Gaborone — Johannesburg",
    modes: ["Port", "Road"],
    countrySlugs: ["namibia", "botswana", "south-africa"],
    note: "Volumes and border dwell stay blank until sourced.",
  },
  {
    slug: "beira-corridor",
    name: "Beira Corridor",
    geography: "Beira — Harare hinterland",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["mozambique", "zimbabwe"],
    note: "No invented throughput or dwell times.",
  },
  {
    slug: "abidjan-lagos",
    name: "Abidjan–Lagos Corridor",
    geography: "Abidjan — Tema — Lomé — Cotonou — Lagos",
    modes: ["Port", "Road"],
    countrySlugs: ["cote-divoire", "ghana", "togo", "benin", "nigeria"],
    note: "Coastal span only. Volumes and dwell stay blank until sourced.",
  },
  {
    slug: "nacala-corridor",
    name: "Nacala Corridor",
    geography: "Nacala — Lilongwe — Lusaka",
    modes: ["Port", "Rail", "Road"],
    countrySlugs: ["mozambique", "malawi", "zambia"],
    note: "No invented throughput or rail tonnage.",
  },
  {
    slug: "lapsset",
    name: "LAPSSET Corridor",
    geography: "Lamu — South Sudan — Addis Ababa",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["kenya", "south-sudan", "ethiopia"],
    note: "Route scaffold. Project cost and cargo series are not stored.",
  },
  {
    slug: "north-south-corridor",
    name: "North-South Corridor",
    geography: "Durban — Harare — Lusaka — Dar es Salaam",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["south-africa", "zimbabwe", "zambia", "tanzania"],
    note: "No invented border dwell or freight volumes.",
  },
  {
    slug: "douala-ndjamena",
    name: "Douala–N'Djamena Corridor",
    geography: "Douala — N’Djamena",
    modes: ["Port", "Road"],
    countrySlugs: ["cameroon", "chad"],
    note: "Hinterland span. Transit times stay blank until cited.",
  },
  {
    slug: "walvis-ndola",
    name: "Walvis Bay–Ndola Corridor",
    geography: "Walvis Bay — Lusaka — Ndola",
    modes: ["Port", "Road"],
    countrySlugs: ["namibia", "zambia"],
    note: "Distinct from Trans-Kalahari. Copperbelt volumes unpublished.",
  },
  {
    slug: "djibouti-addis",
    name: "Djibouti–Addis Corridor",
    geography: "Djibouti — Addis Ababa",
    modes: ["Port", "Rail", "Road"],
    countrySlugs: ["djibouti", "ethiopia"],
    note: "Rail and road span. Cargo series not stored.",
  },
  {
    slug: "dakar-bamako",
    name: "Dakar–Bamako Corridor",
    geography: "Dakar — Bamako",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["senegal", "mali"],
    note: "Hinterland span. Transit times stay blank until cited.",
  },
  {
    slug: "cotonou-niamey",
    name: "Cotonou–Niamey Corridor",
    geography: "Cotonou — Niamey",
    modes: ["Port", "Road"],
    countrySlugs: ["benin", "niger"],
    note: "No invented dwell or freight volumes.",
  },
  {
    slug: "lome-ouagadougou",
    name: "Lomé–Ouagadougou Corridor",
    geography: "Lomé — Ouagadougou",
    modes: ["Port", "Road"],
    countrySlugs: ["togo", "burkina-faso"],
    note: "Hinterland span. Volumes unpublished.",
  },
  {
    slug: "abidjan-ouagadougou",
    name: "Abidjan–Ouagadougou Corridor",
    geography: "Abidjan — Ouagadougou",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["cote-divoire", "burkina-faso"],
    note: "Distinct from Abidjan–Lagos. Throughput blank until sourced.",
  },
  {
    slug: "conakry-bamako",
    name: "Conakry–Bamako Corridor",
    geography: "Conakry — Bamako",
    modes: ["Port", "Road"],
    countrySlugs: ["guinea", "mali"],
    note: "No invented transit times.",
  },
  {
    slug: "pointe-noire-brazzaville",
    name: "Pointe-Noire–Brazzaville Corridor",
    geography: "Pointe-Noire — Brazzaville",
    modes: ["Port", "Rail"],
    countrySlugs: ["congo"],
    note: "Domestic rail span. Tonnage unpublished.",
  },
  {
    slug: "tazara",
    name: "TAZARA",
    geography: "Dar es Salaam — Lusaka",
    modes: ["Port", "Rail"],
    countrySlugs: ["tanzania", "zambia"],
    note: "Rail span. Distinct from the Central Corridor. Tonnage unpublished.",
  },
  {
    slug: "douala-bangui",
    name: "Douala–Bangui Corridor",
    geography: "Douala — Bangui",
    modes: ["Port", "Road"],
    countrySlugs: ["cameroon", "central-african-republic"],
    note: "Hinterland span. Transit times stay blank until cited.",
  },
  {
    slug: "tema-ouagadougou",
    name: "Tema–Ouagadougou Corridor",
    geography: "Tema — Ouagadougou",
    modes: ["Port", "Road"],
    countrySlugs: ["ghana", "burkina-faso"],
    note: "Distinct from Abidjan–Lagos. Volumes unpublished.",
  },
  {
    slug: "abidjan-bamako",
    name: "Abidjan–Bamako Corridor",
    geography: "Abidjan — Bamako",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["cote-divoire", "mali"],
    note: "Distinct from Abidjan–Lagos and Dakar–Bamako. Throughput blank.",
  },
  {
    slug: "lome-niamey",
    name: "Lomé–Niamey Corridor",
    geography: "Lomé — Niamey",
    modes: ["Port", "Road"],
    countrySlugs: ["togo", "niger"],
    note: "Hinterland span. No invented dwell.",
  },
  {
    slug: "nouakchott-dakar",
    name: "Nouakchott–Dakar Corridor",
    geography: "Nouakchott — Dakar",
    modes: ["Port", "Road"],
    countrySlugs: ["mauritania", "senegal"],
    note: "Coastal span. Volumes unpublished.",
  },
  {
    slug: "lagos-niamey",
    name: "Lagos–Niamey Corridor",
    geography: "Lagos — Niamey",
    modes: ["Port", "Road"],
    countrySlugs: ["nigeria", "niger"],
    note: "Distinct from Abidjan–Lagos and Cotonou–Niamey. Freight volumes blank.",
  },
  {
    slug: "matadi-kinshasa",
    name: "Matadi–Kinshasa Corridor",
    geography: "Matadi — Kinshasa",
    modes: ["Port", "Rail", "Road"],
    countrySlugs: ["dr-congo"],
    note: "Domestic river and rail span. Tonnage unpublished.",
  },
  {
    slug: "berbera-addis",
    name: "Berbera–Addis Corridor",
    geography: "Berbera — Addis Ababa",
    modes: ["Port", "Road"],
    countrySlugs: ["somalia", "ethiopia"],
    note: "Distinct from Djibouti–Addis. Cargo series not stored.",
  },
  {
    slug: "cape-town-johannesburg",
    name: "Cape Town–Johannesburg Corridor",
    geography: "Cape Town — Johannesburg",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["south-africa"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "alexandria-cairo",
    name: "Alexandria–Cairo Corridor",
    geography: "Alexandria — Cairo",
    modes: ["Port", "Road"],
    countrySlugs: ["egypt"],
    note: "Domestic span. Distinct from Port Said–Cairo. Throughput blank.",
  },
  {
    slug: "port-said-cairo",
    name: "Port Said–Cairo Corridor",
    geography: "Port Said — Cairo",
    modes: ["Port", "Road"],
    countrySlugs: ["egypt"],
    note: "Domestic span. Distinct from Alexandria–Cairo. Throughput blank.",
  },
  {
    slug: "banjul-dakar",
    name: "Banjul–Dakar Corridor",
    geography: "Banjul — Dakar",
    modes: ["Port", "Road"],
    countrySlugs: ["gambia", "senegal"],
    note: "Coastal span. Volumes unpublished.",
  },
  {
    slug: "freetown-monrovia",
    name: "Freetown–Monrovia Corridor",
    geography: "Freetown — Monrovia",
    modes: ["Port", "Road"],
    countrySlugs: ["sierra-leone", "liberia"],
    note: "Coastal span. Volumes unpublished.",
  },
  {
    slug: "luanda-lobito",
    name: "Luanda–Lobito Corridor",
    geography: "Luanda — Lobito",
    modes: ["Port", "Road"],
    countrySlugs: ["angola"],
    note: "Coastal span. Distinct from the Lobito Corridor. Volumes unpublished.",
  },
  {
    slug: "port-sudan-khartoum",
    name: "Port Sudan–Khartoum Corridor",
    geography: "Port Sudan — Khartoum",
    modes: ["Port", "Road"],
    countrySlugs: ["sudan"],
    note: "Domestic span. Transit times unpublished.",
  },
  {
    slug: "toamasina-antananarivo",
    name: "Toamasina–Antananarivo Corridor",
    geography: "Toamasina — Antananarivo",
    modes: ["Port", "Road"],
    countrySlugs: ["madagascar"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "mbabane-maputo",
    name: "Mbabane–Maputo Corridor",
    geography: "Mbabane — Maputo",
    modes: ["Port", "Road"],
    countrySlugs: ["eswatini", "mozambique"],
    note: "Maputo port file stays on the Maputo Corridor. Volumes unpublished.",
  },
  {
    slug: "maseru-johannesburg",
    name: "Maseru–Johannesburg Corridor",
    geography: "Maseru — Johannesburg",
    modes: ["Road"],
    countrySlugs: ["lesotho", "south-africa"],
    note: "Landlocked span. Volumes unpublished.",
  },
  {
    slug: "bissau-dakar",
    name: "Bissau–Dakar Corridor",
    geography: "Bissau — Dakar",
    modes: ["Port", "Road"],
    countrySlugs: ["guinea-bissau", "senegal"],
    note: "Dakar port file stays on Dakar–Bamako. Volumes unpublished.",
  },
  {
    slug: "mogadishu-berbera",
    name: "Mogadishu–Berbera Corridor",
    geography: "Mogadishu — Berbera",
    modes: ["Port", "Road"],
    countrySlugs: ["somalia"],
    note: "Domestic coastal span. Distinct from Berbera–Addis. Volumes unpublished.",
  },
  {
    slug: "accra-tema",
    name: "Accra–Tema Corridor",
    geography: "Accra — Tema",
    modes: ["Port", "Road"],
    countrySlugs: ["ghana"],
    note: "Tema port file stays on Abidjan–Lagos. Volumes unpublished.",
  },
  {
    slug: "abuja-lagos",
    name: "Abuja–Lagos Corridor",
    geography: "Abuja — Lagos",
    modes: ["Port", "Road"],
    countrySlugs: ["nigeria"],
    note: "Lagos port file stays on Abidjan–Lagos. Volumes unpublished.",
  },
  {
    slug: "douala-yaounde",
    name: "Douala–Yaoundé Corridor",
    geography: "Douala — Yaoundé",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["cameroon"],
    note: "Domestic span. Distinct from Douala–Bangui and Douala–N'Djamena. Volumes unpublished.",
  },
  {
    slug: "massawa-asmara",
    name: "Massawa–Asmara Corridor",
    geography: "Massawa — Asmara",
    modes: ["Port", "Road"],
    countrySlugs: ["eritrea"],
    note: "Domestic span. Transit times unpublished.",
  },
  {
    slug: "tangier-casablanca",
    name: "Tangier–Casablanca Corridor",
    geography: "Tangier — Casablanca",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["morocco"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "tunis-sfax",
    name: "Tunis–Sfax Corridor",
    geography: "Tunis — Sfax",
    modes: ["Port", "Road"],
    countrySlugs: ["tunisia"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "algiers-oran",
    name: "Algiers–Oran Corridor",
    geography: "Algiers — Oran",
    modes: ["Port", "Road"],
    countrySlugs: ["algeria"],
    note: "Coastal span. Volumes unpublished.",
  },
  {
    slug: "tripoli-benghazi",
    name: "Tripoli–Benghazi Corridor",
    geography: "Tripoli — Benghazi",
    modes: ["Port", "Road"],
    countrySlugs: ["libya"],
    note: "Coastal span. Volumes unpublished.",
  },
  {
    slug: "libreville-port-gentil",
    name: "Libreville–Port-Gentil Corridor",
    geography: "Libreville — Port-Gentil",
    modes: ["Port", "Road"],
    countrySlugs: ["gabon"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "malabo-bata",
    name: "Malabo–Bata Corridor",
    geography: "Malabo — Bata",
    modes: ["Port", "Road"],
    countrySlugs: ["equatorial-guinea"],
    note: "Domestic span. Volumes unpublished.",
  },
  {
    slug: "nouakchott-nouadhibou",
    name: "Nouakchott–Nouadhibou Corridor",
    geography: "Nouakchott — Nouadhibou",
    modes: ["Port", "Road"],
    countrySlugs: ["mauritania"],
    note: "Coastal span. Distinct from Nouakchott–Dakar. Volumes unpublished.",
  },
  {
    slug: "lusaka-ndola",
    name: "Lusaka–Ndola Corridor",
    geography: "Lusaka — Ndola",
    modes: ["Road", "Rail"],
    countrySlugs: ["zambia"],
    note: "Domestic span. Distinct from Walvis Bay–Ndola and the Lobito Corridor. Volumes unpublished.",
  },
  {
    slug: "beira-lilongwe",
    name: "Beira–Lilongwe Corridor",
    geography: "Beira — Lilongwe",
    modes: ["Port", "Road"],
    countrySlugs: ["mozambique", "malawi"],
    note: "Distinct from the Nacala Corridor. Beira port file stays on the Beira Corridor. Volumes unpublished.",
  },
  {
    slug: "harare-bulawayo",
    name: "Harare–Bulawayo Corridor",
    geography: "Harare — Bulawayo",
    modes: ["Road", "Rail"],
    countrySlugs: ["zimbabwe"],
    note: "Domestic span. Distinct from the Beira Corridor and the North-South Corridor. Volumes unpublished.",
  },
  {
    slug: "accra-kumasi",
    name: "Accra–Kumasi Corridor",
    geography: "Accra — Kumasi",
    modes: ["Road"],
    countrySlugs: ["ghana"],
    note: "Domestic span. Distinct from Accra–Tema. Volumes unpublished.",
  },
  {
    slug: "brazzaville-kinshasa",
    name: "Brazzaville–Kinshasa Corridor",
    geography: "Brazzaville — Kinshasa",
    modes: ["Road"],
    countrySlugs: ["congo", "dr-congo"],
    note: "River span. Distinct from Matadi–Kinshasa and Pointe-Noire–Brazzaville. Tonnage unpublished.",
  },
  {
    slug: "gaborone-francistown",
    name: "Gaborone–Francistown Corridor",
    geography: "Gaborone — Francistown",
    modes: ["Road"],
    countrySlugs: ["botswana"],
    note: "Domestic span. Distinct from the Trans-Kalahari Corridor. Volumes unpublished.",
  },
  {
    slug: "windhoek-walvis-bay",
    name: "Windhoek–Walvis Bay Corridor",
    geography: "Windhoek — Walvis Bay",
    modes: ["Port", "Road"],
    countrySlugs: ["namibia"],
    note: "Domestic span. Walvis Bay stays on the Trans-Kalahari Corridor. Volumes unpublished.",
  },
  {
    slug: "mombasa-nairobi",
    name: "Mombasa–Nairobi Corridor",
    geography: "Mombasa — Nairobi",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["kenya"],
    note: "Domestic span. Distinct from the Northern Corridor and LAPSSET. Mombasa stays on the Northern Corridor. Volumes unpublished.",
  },
  {
    slug: "dar-es-salaam-dodoma",
    name: "Dar es Salaam–Dodoma Corridor",
    geography: "Dar es Salaam — Dodoma",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["tanzania"],
    note: "Domestic span. Dar es Salaam stays on the Central Corridor. Volumes unpublished.",
  },
  {
    slug: "kano-lagos",
    name: "Kano–Lagos Corridor",
    geography: "Kano — Lagos",
    modes: ["Road"],
    countrySlugs: ["nigeria"],
    note: "Domestic span. Distinct from Abuja–Lagos. Lagos stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "blantyre-lilongwe",
    name: "Blantyre–Lilongwe Corridor",
    geography: "Blantyre — Lilongwe",
    modes: ["Road"],
    countrySlugs: ["malawi"],
    note: "Domestic span. Distinct from the Nacala Corridor and Beira–Lilongwe. Volumes unpublished.",
  },
  {
    slug: "cairo-aswan",
    name: "Cairo–Aswan Corridor",
    geography: "Cairo — Aswan",
    modes: ["Road", "Rail"],
    countrySlugs: ["egypt"],
    note: "Domestic span. Distinct from Alexandria–Cairo and Port Said–Cairo. Volumes unpublished.",
  },
  {
    slug: "casablanca-marrakech",
    name: "Casablanca–Marrakech Corridor",
    geography: "Casablanca — Marrakech",
    modes: ["Road", "Rail"],
    countrySlugs: ["morocco"],
    note: "Domestic span. Distinct from Tangier–Casablanca. Volumes unpublished.",
  },
  {
    slug: "durban-johannesburg",
    name: "Durban–Johannesburg Corridor",
    geography: "Durban — Johannesburg",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["south-africa"],
    note: "Domestic span. Distinct from the Maputo Corridor, the North-South Corridor and Cape Town–Johannesburg. Durban stays on the Maputo Corridor. Volumes unpublished.",
  },
  {
    slug: "kampala-kigali",
    name: "Kampala–Kigali Corridor",
    geography: "Kampala — Kigali",
    modes: ["Road"],
    countrySlugs: ["uganda", "rwanda"],
    note: "Land span. Distinct from the Northern Corridor. Volumes unpublished.",
  },
  {
    slug: "juba-kampala",
    name: "Juba–Kampala Corridor",
    geography: "Juba — Kampala",
    modes: ["Road"],
    countrySlugs: ["south-sudan", "uganda"],
    note: "Land span. Distinct from the Northern Corridor. Volumes unpublished.",
  },
  {
    slug: "ouagadougou-niamey",
    name: "Ouagadougou–Niamey Corridor",
    geography: "Ouagadougou — Niamey",
    modes: ["Road"],
    countrySlugs: ["burkina-faso", "niger"],
    note: "Land span. Distinct from the coastal gateway corridors. Volumes unpublished.",
  },
  {
    slug: "addis-ababa-nairobi",
    name: "Addis Ababa–Nairobi Corridor",
    geography: "Addis Ababa — Nairobi",
    modes: ["Road"],
    countrySlugs: ["ethiopia", "kenya"],
    note: "Land span. Distinct from Djibouti–Addis, Berbera–Addis and Mombasa–Nairobi. Volumes unpublished.",
  },
  {
    slug: "bamako-ouagadougou",
    name: "Bamako–Ouagadougou Corridor",
    geography: "Bamako — Ouagadougou",
    modes: ["Road"],
    countrySlugs: ["mali", "burkina-faso"],
    note: "Land span. Distinct from Dakar–Bamako, Abidjan–Bamako, Conakry–Bamako and Abidjan–Ouagadougou. Volumes unpublished.",
  },
  {
    slug: "niamey-kano",
    name: "Niamey–Kano Corridor",
    geography: "Niamey — Kano",
    modes: ["Road"],
    countrySlugs: ["niger", "nigeria"],
    note: "Land span. Distinct from Lagos–Niamey, Kano–Lagos and Ouagadougou–Niamey. Volumes unpublished.",
  },
  {
    slug: "algiers-constantine",
    name: "Algiers–Constantine Corridor",
    geography: "Algiers — Constantine",
    modes: ["Road", "Rail"],
    countrySlugs: ["algeria"],
    note: "Domestic span. Distinct from Algiers–Oran. Volumes unpublished.",
  },
  {
    slug: "accra-takoradi",
    name: "Accra–Takoradi Corridor",
    geography: "Accra — Takoradi",
    modes: ["Port", "Road"],
    countrySlugs: ["ghana"],
    note: "Domestic span. Distinct from Accra–Tema and Accra–Kumasi. Tema stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "kigali-bujumbura",
    name: "Kigali–Bujumbura Corridor",
    geography: "Kigali — Bujumbura",
    modes: ["Road"],
    countrySlugs: ["rwanda", "burundi"],
    note: "Land span. Distinct from the Northern Corridor and the Central Corridor. Volumes unpublished.",
  },
  {
    slug: "lusaka-harare",
    name: "Lusaka–Harare Corridor",
    geography: "Lusaka — Harare",
    modes: ["Road"],
    countrySlugs: ["zambia", "zimbabwe"],
    note: "Land span. Distinct from the North-South Corridor. Volumes unpublished.",
  },
  {
    slug: "lagos-port-harcourt",
    name: "Lagos–Port Harcourt Corridor",
    geography: "Lagos — Port Harcourt",
    modes: ["Port", "Road"],
    countrySlugs: ["nigeria"],
    note: "Domestic span. Distinct from Abuja–Lagos and Kano–Lagos. Lagos stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "nairobi-kisumu",
    name: "Nairobi–Kisumu Corridor",
    geography: "Nairobi — Kisumu",
    modes: ["Road", "Rail"],
    countrySlugs: ["kenya"],
    note: "Domestic span. Distinct from Mombasa–Nairobi and the Northern Corridor. Volumes unpublished.",
  },
  {
    slug: "abidjan-san-pedro",
    name: "Abidjan–San-Pédro Corridor",
    geography: "Abidjan — San-Pédro",
    modes: ["Port", "Road"],
    countrySlugs: ["cote-divoire"],
    note: "Domestic span. Abidjan stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "beira-tete",
    name: "Beira–Tete Corridor",
    geography: "Beira — Tete",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["mozambique"],
    note: "Domestic span. Distinct from the Beira Corridor and Beira–Lilongwe. Beira stays on the Beira Corridor. Volumes unpublished.",
  },
  {
    slug: "monrovia-buchanan",
    name: "Monrovia–Buchanan Corridor",
    geography: "Monrovia — Buchanan",
    modes: ["Port", "Road"],
    countrySlugs: ["liberia"],
    note: "Domestic span. Distinct from Freetown–Monrovia. Volumes unpublished.",
  },
  {
    slug: "casablanca-rabat",
    name: "Casablanca–Rabat Corridor",
    geography: "Casablanca — Rabat",
    modes: ["Road", "Rail"],
    countrySlugs: ["morocco"],
    note: "Domestic span. Distinct from Tangier–Casablanca and Casablanca–Marrakech. Volumes unpublished.",
  },
  {
    slug: "johannesburg-pretoria",
    name: "Johannesburg–Pretoria Corridor",
    geography: "Johannesburg — Pretoria",
    modes: ["Road", "Rail"],
    countrySlugs: ["south-africa"],
    note: "Domestic span. Distinct from Cape Town–Johannesburg, Durban–Johannesburg, and Maseru–Johannesburg. Volumes unpublished.",
  },
  {
    slug: "dakar-saint-louis",
    name: "Dakar–Saint-Louis Corridor",
    geography: "Dakar — Saint-Louis",
    modes: ["Road"],
    countrySlugs: ["senegal"],
    note: "Domestic span. Distinct from Dakar–Bamako. Dakar stays on the Dakar–Bamako Corridor. Volumes unpublished.",
  },
  {
    slug: "accra-tamale",
    name: "Accra–Tamale Corridor",
    geography: "Accra — Tamale",
    modes: ["Road"],
    countrySlugs: ["ghana"],
    note: "Domestic span. Distinct from Accra–Tema, Accra–Kumasi, and Accra–Takoradi. Volumes unpublished.",
  },
  {
    slug: "luanda-namibe",
    name: "Luanda–Namibe Corridor",
    geography: "Luanda — Namibe",
    modes: ["Port", "Road"],
    countrySlugs: ["angola"],
    note: "Domestic span. Distinct from Luanda–Lobito. Lobito stays on the Lobito Corridor. Volumes unpublished.",
  },
  {
    slug: "kinshasa-lubumbashi",
    name: "Kinshasa–Lubumbashi Corridor",
    geography: "Kinshasa — Lubumbashi",
    modes: ["Road", "Rail"],
    countrySlugs: ["dr-congo"],
    note: "Domestic span. Distinct from Matadi–Kinshasa and Brazzaville–Kinshasa. Volumes unpublished.",
  },
  {
    slug: "algiers-annaba",
    name: "Algiers–Annaba Corridor",
    geography: "Algiers — Annaba",
    modes: ["Port", "Road"],
    countrySlugs: ["algeria"],
    note: "Domestic span. Distinct from Algiers–Oran and Algiers–Constantine. Volumes unpublished.",
  },
  {
    slug: "lagos-calabar",
    name: "Lagos–Calabar Corridor",
    geography: "Lagos — Calabar",
    modes: ["Port", "Road"],
    countrySlugs: ["nigeria"],
    note: "Domestic span. Distinct from Abuja–Lagos, Kano–Lagos, and Lagos–Port Harcourt. Lagos stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "kampala-entebbe",
    name: "Kampala–Entebbe Corridor",
    geography: "Kampala — Entebbe",
    modes: ["Road"],
    countrySlugs: ["uganda"],
    note: "Domestic span. Distinct from Kampala–Kigali and Juba–Kampala. Volumes unpublished.",
  },
  {
    slug: "dar-es-salaam-mwanza",
    name: "Dar es Salaam–Mwanza Corridor",
    geography: "Dar es Salaam — Mwanza",
    modes: ["Port", "Road", "Rail"],
    countrySlugs: ["tanzania"],
    note: "Domestic span. Distinct from the Central Corridor and Dar es Salaam–Dodoma. Dar es Salaam stays on the Central Corridor. Volumes unpublished.",
  },
  {
    slug: "cotonou-porto-novo",
    name: "Cotonou–Porto-Novo Corridor",
    geography: "Cotonou — Porto-Novo",
    modes: ["Road"],
    countrySlugs: ["benin"],
    note: "Domestic span. Distinct from Cotonou–Niamey. Volumes unpublished.",
  },
  {
    slug: "lome-kara",
    name: "Lomé–Kara Corridor",
    geography: "Lomé — Kara",
    modes: ["Road"],
    countrySlugs: ["togo"],
    note: "Domestic span. Distinct from Lomé–Ouagadougou and Lomé–Niamey. Lomé stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "tunis-sousse",
    name: "Tunis–Sousse Corridor",
    geography: "Tunis — Sousse",
    modes: ["Port", "Road"],
    countrySlugs: ["tunisia"],
    note: "Domestic span. Distinct from Tunis–Sfax. Sfax stays on the Tunis–Sfax Corridor. Volumes unpublished.",
  },
  {
    slug: "cairo-luxor",
    name: "Cairo–Luxor Corridor",
    geography: "Cairo — Luxor",
    modes: ["Road", "Rail"],
    countrySlugs: ["egypt"],
    note: "Domestic span. Distinct from Cairo–Aswan, Alexandria–Cairo, and Port Said–Cairo. Volumes unpublished.",
  },
  {
    slug: "conakry-kankan",
    name: "Conakry–Kankan Corridor",
    geography: "Conakry — Kankan",
    modes: ["Road"],
    countrySlugs: ["guinea"],
    note: "Domestic span. Distinct from Conakry–Bamako. Conakry stays on the Conakry–Bamako Corridor. Volumes unpublished.",
  },
  {
    slug: "libreville-franceville",
    name: "Libreville–Franceville Corridor",
    geography: "Libreville — Franceville",
    modes: ["Road"],
    countrySlugs: ["gabon"],
    note: "Domestic span. Distinct from Libreville–Port-Gentil. Port-Gentil stays on the Libreville–Port-Gentil Corridor. Volumes unpublished.",
  },
  {
    slug: "nairobi-nakuru",
    name: "Nairobi–Nakuru Corridor",
    geography: "Nairobi — Nakuru",
    modes: ["Road", "Rail"],
    countrySlugs: ["kenya"],
    note: "Domestic span. Distinct from Nairobi–Kisumu, Mombasa–Nairobi, and the Northern Corridor. Volumes unpublished.",
  },
  {
    slug: "addis-ababa-dire-dawa",
    name: "Addis Ababa–Dire Dawa Corridor",
    geography: "Addis Ababa — Dire Dawa",
    modes: ["Road", "Rail"],
    countrySlugs: ["ethiopia"],
    note: "Domestic span. Distinct from Djibouti–Addis, Berbera–Addis, and Addis Ababa–Nairobi. Volumes unpublished.",
  },
  {
    slug: "abidjan-bouake",
    name: "Abidjan–Bouaké Corridor",
    geography: "Abidjan — Bouaké",
    modes: ["Road"],
    countrySlugs: ["cote-divoire"],
    note: "Domestic span. Distinct from Abidjan–San-Pédro, Abidjan–Bamako, and Abidjan–Ouagadougou. Abidjan stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "lagos-ibadan",
    name: "Lagos–Ibadan Corridor",
    geography: "Lagos — Ibadan",
    modes: ["Road"],
    countrySlugs: ["nigeria"],
    note: "Domestic span. Distinct from Abuja–Lagos, Kano–Lagos, Lagos–Port Harcourt, and Lagos–Calabar. Lagos stays on the Abidjan–Lagos Corridor. Volumes unpublished.",
  },
  {
    slug: "johannesburg-bloemfontein",
    name: "Johannesburg–Bloemfontein Corridor",
    geography: "Johannesburg — Bloemfontein",
    modes: ["Road"],
    countrySlugs: ["south-africa"],
    note: "Domestic span. Distinct from Johannesburg–Pretoria, Cape Town–Johannesburg, and Durban–Johannesburg. Volumes unpublished.",
  },
  {
    slug: "lusaka-livingstone",
    name: "Lusaka–Livingstone Corridor",
    geography: "Lusaka — Livingstone",
    modes: ["Road"],
    countrySlugs: ["zambia"],
    note: "Domestic span. Distinct from Lusaka–Ndola, Lusaka–Harare, and the North-South Corridor. Volumes unpublished.",
  },
  {
    slug: "marrakech-agadir",
    name: "Marrakech–Agadir Corridor",
    geography: "Marrakech — Agadir",
    modes: ["Port", "Road"],
    countrySlugs: ["morocco"],
    note: "Domestic span. Distinct from Casablanca–Marrakech and Tangier–Casablanca. Volumes unpublished.",
  },
  {
    slug: "kampala-jinja",
    name: "Kampala–Jinja Corridor",
    geography: "Kampala — Jinja",
    modes: ["Road"],
    countrySlugs: ["uganda"],
    note: "Domestic span. Distinct from Kampala–Entebbe, Kampala–Kigali, and Juba–Kampala. Volumes unpublished.",
  },
  {
    slug: "yaounde-garoua",
    name: "Yaoundé–Garoua Corridor",
    geography: "Yaoundé — Garoua",
    modes: ["Road"],
    countrySlugs: ["cameroon"],
    note: "Domestic span. Distinct from Douala–Yaoundé and Douala–N'Djamena. Volumes unpublished.",
  },
  {
    slug: "harare-mutare",
    name: "Harare–Mutare Corridor",
    geography: "Harare — Mutare",
    modes: ["Road"],
    countrySlugs: ["zimbabwe"],
    note: "Domestic span. Distinct from Harare–Bulawayo and the Beira Corridor. Volumes unpublished.",
  },
  {
    slug: "maputo-nampula",
    name: "Maputo–Nampula Corridor",
    geography: "Maputo — Nampula",
    modes: ["Road"],
    countrySlugs: ["mozambique"],
    note: "Domestic span. Distinct from the Maputo Corridor and the Nacala Corridor. Maputo stays on the Maputo Corridor. Volumes unpublished.",
  },
  {
    slug: "accra-cape-coast",
    name: "Accra–Cape Coast Corridor",
    geography: "Accra — Cape Coast",
    modes: ["Road"],
    countrySlugs: ["ghana"],
    note: "Domestic span. Distinct from Accra–Tema, Accra–Kumasi, Accra–Takoradi, and Accra–Tamale. Tema and Takoradi keep their corridor files. Volumes unpublished.",
  },
  {
    slug: "windhoek-rundu",
    name: "Windhoek–Rundu Corridor",
    geography: "Windhoek — Rundu",
    modes: ["Road"],
    countrySlugs: ["namibia"],
    note: "Domestic span. Distinct from Windhoek–Walvis Bay and the Trans-Kalahari Corridor. Walvis Bay stays on the Trans-Kalahari Corridor. Volumes unpublished.",
  },
  {
    slug: "gaborone-maun",
    name: "Gaborone–Maun Corridor",
    geography: "Gaborone — Maun",
    modes: ["Road"],
    countrySlugs: ["botswana"],
    note: "Domestic span. Distinct from Gaborone–Francistown and the Trans-Kalahari Corridor. Volumes unpublished.",
  },
  {
    slug: "tripoli-misrata",
    name: "Tripoli–Misrata Corridor",
    geography: "Tripoli — Misrata",
    modes: ["Port", "Road"],
    countrySlugs: ["libya"],
    note: "Domestic span. Distinct from Tripoli–Benghazi. Volumes unpublished.",
  },
  {
    slug: "oran-constantine",
    name: "Oran–Constantine Corridor",
    geography: "Oran — Constantine",
    modes: ["Road", "Rail"],
    countrySlugs: ["algeria"],
    note: "Domestic span. Distinct from Algiers–Oran and Algiers–Constantine. Oran stays on the Algiers–Oran Corridor. Volumes unpublished.",
  },
  {
    slug: "blantyre-zomba",
    name: "Blantyre–Zomba Corridor",
    geography: "Blantyre — Zomba",
    modes: ["Road"],
    countrySlugs: ["malawi"],
    note: "Domestic span. Distinct from Blantyre–Lilongwe and Beira–Lilongwe. Volumes unpublished.",
  },
  {
    slug: "asmara-keren",
    name: "Asmara–Keren Corridor",
    geography: "Asmara — Keren",
    modes: ["Road"],
    countrySlugs: ["eritrea"],
    note: "Domestic span. Distinct from Massawa–Asmara. Massawa stays on the Massawa–Asmara Corridor. Volumes unpublished.",
  },
  {
    slug: "luanda-malanje",
    name: "Luanda–Malanje Corridor",
    geography: "Luanda — Malanje",
    modes: ["Road"],
    countrySlugs: ["angola"],
    note: "Domestic span. Distinct from Luanda–Lobito and Luanda–Namibe. Lobito stays on the Lobito Corridor. Volumes unpublished.",
  },
  {
    slug: "antananarivo-fianarantsoa",
    name: "Antananarivo–Fianarantsoa Corridor",
    geography: "Antananarivo — Fianarantsoa",
    modes: ["Road"],
    countrySlugs: ["madagascar"],
    note: "Domestic span. Distinct from Toamasina–Antananarivo. Toamasina stays on the Toamasina–Antananarivo Corridor. Volumes unpublished.",
  },
] as const;

export type Port = {
  slug: string;
  name: string;
  countrySlug: string;
  waters: string;
  corridorSlug?: string;
};

export const ports: Port[] = [
  { slug: "mombasa", name: "Mombasa", countrySlug: "kenya", waters: "Indian Ocean", corridorSlug: "northern-corridor" },
  { slug: "dar-es-salaam", name: "Dar es Salaam", countrySlug: "tanzania", waters: "Indian Ocean", corridorSlug: "central-corridor" },
  { slug: "lobito", name: "Lobito", countrySlug: "angola", waters: "Atlantic", corridorSlug: "lobito-corridor" },
  { slug: "maputo", name: "Maputo", countrySlug: "mozambique", waters: "Indian Ocean", corridorSlug: "maputo-corridor" },
  { slug: "durban", name: "Durban", countrySlug: "south-africa", waters: "Indian Ocean", corridorSlug: "maputo-corridor" },
  { slug: "cape-town", name: "Cape Town", countrySlug: "south-africa", waters: "Atlantic", corridorSlug: "cape-town-johannesburg" },
  { slug: "lagos", name: "Lagos (Apapa / Tin Can)", countrySlug: "nigeria", waters: "Atlantic", corridorSlug: "abidjan-lagos" },
  { slug: "tema", name: "Tema", countrySlug: "ghana", waters: "Atlantic", corridorSlug: "abidjan-lagos" },
  { slug: "alexandria", name: "Alexandria", countrySlug: "egypt", waters: "Mediterranean", corridorSlug: "alexandria-cairo" },
  { slug: "port-said", name: "Port Said", countrySlug: "egypt", waters: "Mediterranean / Suez", corridorSlug: "port-said-cairo" },
  { slug: "djibouti", name: "Djibouti", countrySlug: "djibouti", waters: "Red Sea / Gulf of Aden", corridorSlug: "djibouti-addis" },
  { slug: "abidjan", name: "Abidjan", countrySlug: "cote-divoire", waters: "Atlantic", corridorSlug: "abidjan-lagos" },
  { slug: "dakar", name: "Dakar", countrySlug: "senegal", waters: "Atlantic", corridorSlug: "dakar-bamako" },
  { slug: "lome", name: "Lomé", countrySlug: "togo", waters: "Atlantic", corridorSlug: "abidjan-lagos" },
  { slug: "walvis-bay", name: "Walvis Bay", countrySlug: "namibia", waters: "Atlantic", corridorSlug: "trans-kalahari" },
  { slug: "beira", name: "Beira", countrySlug: "mozambique", waters: "Indian Ocean", corridorSlug: "beira-corridor" },
  { slug: "nacala", name: "Nacala", countrySlug: "mozambique", waters: "Indian Ocean", corridorSlug: "nacala-corridor" },
  { slug: "lamu", name: "Lamu", countrySlug: "kenya", waters: "Indian Ocean", corridorSlug: "lapsset" },
  { slug: "conakry", name: "Conakry", countrySlug: "guinea", waters: "Atlantic", corridorSlug: "conakry-bamako" },
  { slug: "pointe-noire", name: "Pointe-Noire", countrySlug: "congo", waters: "Atlantic", corridorSlug: "pointe-noire-brazzaville" },
  { slug: "matadi", name: "Matadi", countrySlug: "dr-congo", waters: "Atlantic", corridorSlug: "matadi-kinshasa" },
  { slug: "berbera", name: "Berbera", countrySlug: "somalia", waters: "Gulf of Aden", corridorSlug: "berbera-addis" },
  { slug: "freetown", name: "Freetown", countrySlug: "sierra-leone", waters: "Atlantic", corridorSlug: "freetown-monrovia" },
  { slug: "port-sudan", name: "Port Sudan", countrySlug: "sudan", waters: "Red Sea", corridorSlug: "port-sudan-khartoum" },
  { slug: "toamasina", name: "Toamasina", countrySlug: "madagascar", waters: "Indian Ocean", corridorSlug: "toamasina-antananarivo" },
  { slug: "massawa", name: "Massawa", countrySlug: "eritrea", waters: "Red Sea", corridorSlug: "massawa-asmara" },
  { slug: "tangier", name: "Tangier", countrySlug: "morocco", waters: "Mediterranean / Strait of Gibraltar", corridorSlug: "tangier-casablanca" },
  { slug: "sfax", name: "Sfax", countrySlug: "tunisia", waters: "Mediterranean", corridorSlug: "tunis-sfax" },
  { slug: "oran", name: "Oran", countrySlug: "algeria", waters: "Mediterranean", corridorSlug: "algiers-oran" },
  { slug: "benghazi", name: "Benghazi", countrySlug: "libya", waters: "Mediterranean", corridorSlug: "tripoli-benghazi" },
  { slug: "port-gentil", name: "Port-Gentil", countrySlug: "gabon", waters: "Atlantic", corridorSlug: "libreville-port-gentil" },
  { slug: "bata", name: "Bata", countrySlug: "equatorial-guinea", waters: "Atlantic", corridorSlug: "malabo-bata" },
  { slug: "nouadhibou", name: "Nouadhibou", countrySlug: "mauritania", waters: "Atlantic", corridorSlug: "nouakchott-nouadhibou" },
  { slug: "takoradi", name: "Takoradi", countrySlug: "ghana", waters: "Atlantic", corridorSlug: "accra-takoradi" },
  { slug: "port-harcourt", name: "Port Harcourt", countrySlug: "nigeria", waters: "Atlantic", corridorSlug: "lagos-port-harcourt" },
  { slug: "san-pedro", name: "San-Pédro", countrySlug: "cote-divoire", waters: "Atlantic", corridorSlug: "abidjan-san-pedro" },
  { slug: "buchanan", name: "Buchanan", countrySlug: "liberia", waters: "Atlantic", corridorSlug: "monrovia-buchanan" },
  { slug: "namibe", name: "Namibe", countrySlug: "angola", waters: "Atlantic", corridorSlug: "luanda-namibe" },
  { slug: "annaba", name: "Annaba", countrySlug: "algeria", waters: "Mediterranean", corridorSlug: "algiers-annaba" },
  { slug: "calabar", name: "Calabar", countrySlug: "nigeria", waters: "Atlantic", corridorSlug: "lagos-calabar" },
  { slug: "sousse", name: "Sousse", countrySlug: "tunisia", waters: "Mediterranean", corridorSlug: "tunis-sousse" },
  { slug: "agadir", name: "Agadir", countrySlug: "morocco", waters: "Atlantic", corridorSlug: "marrakech-agadir" },
  { slug: "misrata", name: "Misrata", countrySlug: "libya", waters: "Mediterranean", corridorSlug: "tripoli-misrata" },
];

export const tradeRegimes = [
  {
    slug: "afcfta",
    name: "AfCFTA",
    lede: "Protocols and national gazettes stay blank until a cited instrument exists. Not a modelled tariff book.",
  },
] as const;

export function getCorridor(slug: string) {
  return corridors.find((item) => item.slug === slug);
}

export function getPort(slug: string) {
  return ports.find((item) => item.slug === slug);
}

export function getTradeRegime(slug: string) {
  return tradeRegimes.find((item) => item.slug === slug);
}

export function corridorCountryHref(corridorSlug: string, countrySlug: string) {
  return `/trade/${corridorSlug}/${countrySlug}`;
}

export function portFileHref(slug: string) {
  return `/trade/ports/${slug}`;
}

export function corridorCountryParams() {
  return corridors.flatMap((corridor) => corridor.countrySlugs.map((country) => ({ slug: corridor.slug, country })));
}

export function portsForCountry(countrySlug: string) {
  return ports.filter((item) => item.countrySlug === countrySlug);
}

export function portsForCorridor(corridorSlug: string) {
  return ports.filter((item) => item.corridorSlug === corridorSlug);
}

export function corridorsForCountry(countrySlug: string) {
  return corridors.filter((corridor) => (corridor.countrySlugs as readonly string[]).includes(countrySlug));
}
