/** North-star event names. Wire a collector later — do not invent dashboards. */
export const analyticsEvents = [
  "brief_open",
  "country_view",
  "signal_open",
  "search",
  "ask_query",
  "watchlist_add",
  "alert_subscribe",
  "pro_cta",
  "export_csv",
  "graph_open",
  "pack_open",
  "usage_view",
  "method_open",
  "source_open",
  "compare_open",
  "ingestion_view",
  "feed_open",
  "status_view",
  "search_save",
  "licence_view",
  "notification_pref",
  "changelog_open",
  "audit_view",
  "report_open",
  "calendar_open",
  "partner_view",
  "coverage_view",
  "glossary_open",
  "onboarding_open",
  "webhook_view",
  "region_open",
  "runbook_open",
  "layers_open",
  "press_open",
  "golive_open",
  "social_open",
  "embed_view",
  "security_open",
  "integration_view",
  "sla_open",
  "brand_open",
  "roadmap_open",
  "a11y_open",
  "sdk_open",
] as const;

export type AnalyticsEvent = (typeof analyticsEvents)[number];
