insert into public.entities (slug, name, kind, country_id, metadata)
select v.slug, v.name, v.kind, c.id, v.meta::jsonb
from (values
('kenya', 'Kenya', 'country', 'kenya', '{"href":"/countries/kenya"}'),
('kes', 'KES', 'currency', '', '{"href":"/markets/currencies/usd-kes"}'),
('cbk', 'CBK', 'agency', '', '{"href":"/institutions/cbk"}'),
('nse', 'NSE', 'exchange', '', '{"href":"/institutions/nse"}'),
('nairobi', 'Nairobi', 'city', 'kenya', '{"href":"/cities/nairobi","role":"Capital / markets"}'),
('mombasa', 'Mombasa', 'city', 'kenya', '{"href":"/cities/mombasa","role":"Port city","portSlug":"mombasa","waters":"Indian Ocean","corridorSlug":"northern-corridor"}'),
('banking', 'Banking', 'industry', '', '{"href":"/industries/banking/kenya"}'),
('agriculture', 'Agriculture', 'industry', '', '{"href":"/industries/agriculture/kenya"}'),
('energy', 'Energy', 'industry', '', '{"href":"/industries/energy/kenya"}'),
('policy-rate', 'Policy rate', 'indicator', '', '{"href":"/indicators/policy-rate/kenya"}'),
('northern-corridor', 'Northern Corridor', 'corridor', '', '{"href":"/trade/northern-corridor/kenya"}'),
('safaricom', 'Safaricom', 'company', 'kenya', '{"href":"/companies/safaricom"}'),
('equity', 'Equity Group', 'company', '', '{"href":"/companies/equity-group"}'),
('governor', 'CBK governor', 'person', '', '{"href":"/people/central-bank-governor/kenya"}'),
('inflation-costs', 'Inflation / manufacturing costs', 'concept', '', '{}'),
('nigeria', 'Nigeria', 'country', 'nigeria', '{"href":"/countries/nigeria"}'),
('ngn', 'NGN', 'currency', '', '{"href":"/markets/currencies/usd-ngn"}'),
('cbn', 'CBN', 'agency', '', '{"href":"/agencies/central-bank/nigeria"}'),
('ngx', 'NGX', 'exchange', '', '{"href":"/markets/exchanges/ngx-asi"}'),
('lagos', 'Lagos', 'city', 'nigeria', '{"href":"/cities/lagos","role":"Commercial / port","portSlug":"lagos","waters":"Atlantic","corridorSlug":"abidjan-lagos"}'),
('mtn-nigeria', 'MTN Nigeria', 'company', 'nigeria', '{"href":"/companies/mtn-nigeria"}'),
('ng-banking', 'Banking · Nigeria', 'industry', '', '{"href":"/industries/banking/nigeria"}'),
('ng-policy-rate', 'Policy rate · Nigeria', 'indicator', '', '{"href":"/indicators/policy-rate/nigeria"}'),
('south-africa', 'South Africa', 'country', 'south-africa', '{"href":"/countries/south-africa"}'),
('zar', 'ZAR', 'currency', '', '{"href":"/markets/currencies/usd-zar"}'),
('sarb', 'SARB', 'agency', '', '{"href":"/agencies/central-bank/south-africa"}'),
('jse', 'JSE', 'exchange', '', '{"href":"/markets/exchanges/jse-alsi"}'),
('johannesburg', 'Johannesburg', 'city', 'south-africa', '{"href":"/cities/johannesburg","role":"Markets"}'),
('standard-bank', 'Standard Bank', 'company', 'south-africa', '{"href":"/companies/standard-bank"}'),
('za-banking', 'Banking · South Africa', 'industry', '', '{"href":"/industries/banking/south-africa"}'),
('egypt', 'Egypt', 'country', 'egypt', '{"href":"/countries/egypt"}'),
('egp', 'EGP', 'currency', '', '{"href":"/markets/currencies/usd-egp"}'),
('cbe', 'CBE', 'agency', '', '{"href":"/agencies/central-bank/egypt"}'),
('egx', 'EGX', 'exchange', '', '{"href":"/markets/exchanges/egx-30"}'),
('cairo', 'Cairo', 'city', 'egypt', '{"href":"/cities/cairo","role":"Capital / markets"}'),
('eg-energy', 'Energy · Egypt', 'industry', '', '{"href":"/industries/energy/egypt"}'),
('ghana', 'Ghana', 'country', 'ghana', '{"href":"/countries/ghana"}'),
('ghs', 'GHS', 'currency', '', '{"href":"/markets/currencies/usd-ghs"}'),
('bog', 'BoG', 'agency', '', '{"href":"/agencies/central-bank/ghana"}'),
('gse', 'GSE', 'exchange', '', '{"href":"/markets/exchanges/gse-ci"}'),
('accra', 'Accra', 'city', 'ghana', '{"href":"/cities/accra","role":"Capital / markets"}'),
('gh-banking', 'Banking · Ghana', 'industry', '', '{"href":"/industries/banking/ghana"}'),
('tema', 'Tema', 'city', '', '{"href":"/trade/ports/tema","waters":"Atlantic","corridorSlug":"abidjan-lagos"}'),
('rwanda', 'Rwanda', 'country', 'rwanda', '{"href":"/countries/rwanda"}'),
('rwf', 'RWF', 'currency', '', '{"href":"/markets/currencies/usd-rwf"}'),
('bnr', 'BNR', 'agency', '', '{"href":"/agencies/central-bank/rwanda"}'),
('kigali', 'Kigali', 'city', 'rwanda', '{"href":"/cities/kigali","role":"Capital"}'),
('rw-fintech', 'Fintech · Rwanda', 'industry', '', '{"href":"/technology/fintech/rwanda"}'),
('northern-corridor-rw', 'Northern Corridor · Rwanda', 'corridor', '', '{"href":"/trade/northern-corridor/rwanda"}'),
('uganda', 'Uganda', 'country', 'uganda', '{"href":"/countries/uganda"}'),
('ugx', 'UGX', 'currency', '', '{"href":"/markets/currencies/usd-ugx"}'),
('bou', 'BoU', 'agency', '', '{"href":"/agencies/central-bank/uganda"}'),
('kampala', 'Kampala', 'city', 'uganda', '{"href":"/cities/kampala","role":"Capital"}'),
('northern-corridor-ug', 'Northern Corridor · Uganda', 'corridor', '', '{"href":"/trade/northern-corridor/uganda"}'),
('ug-agriculture', 'Agriculture · Uganda', 'industry', '', '{"href":"/industries/agriculture/uganda"}'),
('tanzania', 'Tanzania', 'country', 'tanzania', '{"href":"/countries/tanzania"}'),
('tzs', 'TZS', 'currency', '', '{"href":"/markets/currencies/usd-tzs"}'),
('bot', 'BoT', 'agency', '', '{"href":"/agencies/central-bank/tanzania"}'),
('dar-es-salaam', 'Dar es Salaam', 'city', 'tanzania', '{"href":"/cities/dar-es-salaam","role":"Port / commercial","portSlug":"dar-es-salaam","waters":"Indian Ocean","corridorSlug":"central-corridor"}'),
('central-corridor', 'Central Corridor', 'corridor', '', '{"href":"/trade/central-corridor"}'),
('tz-ports', 'Ports · Tanzania', 'industry', '', '{"href":"/industries/logistics/tanzania"}'),
('ethiopia', 'Ethiopia', 'country', 'ethiopia', '{"href":"/countries/ethiopia"}'),
('etb', 'ETB', 'currency', '', '{"href":"/countries/ethiopia"}'),
('nbe', 'NBE', 'agency', '', '{"href":"/agencies/central-bank/ethiopia"}'),
('addis-ababa', 'Addis Ababa', 'city', 'ethiopia', '{"href":"/cities/addis-ababa","role":"Capital / aviation"}'),
('et-agriculture', 'Agriculture · Ethiopia', 'industry', '', '{"href":"/industries/agriculture/ethiopia"}'),
('et-aviation', 'Aviation · Ethiopia', 'industry', '', '{"href":"/industries/logistics/ethiopia"}'),
('morocco', 'Morocco', 'country', 'morocco', '{"href":"/countries/morocco"}'),
('mad', 'MAD', 'currency', '', '{"href":"/markets/currencies/usd-mad"}'),
('bam', 'BAM', 'agency', '', '{"href":"/agencies/central-bank/morocco"}'),
('casablanca', 'Casablanca', 'city', 'morocco', '{"href":"/cities/casablanca","role":"Commercial / markets"}'),
('ma-banking', 'Banking · Morocco', 'industry', '', '{"href":"/industries/banking/morocco"}'),
('ma-tourism', 'Tourism · Morocco', 'industry', '', '{"href":"/industries/tourism/morocco"}'),
('cote-divoire', 'Côte d’Ivoire', 'country', 'cote-divoire', '{"href":"/countries/cote-divoire"}'),
('xof', 'XOF', 'currency', '', '{"href":"/markets/currencies/usd-xof"}'),
('bceao', 'BCEAO', 'agency', '', '{"href":"/agencies/central-bank/cote-divoire"}'),
('abidjan', 'Abidjan', 'city', 'cote-divoire', '{"href":"/cities/abidjan","role":"Commercial / port","portSlug":"abidjan","waters":"Atlantic","corridorSlug":"abidjan-lagos"}'),
('ci-banking', 'Banking · Côte d’Ivoire', 'industry', '', '{"href":"/industries/banking/cote-divoire"}'),
('ci-cocoa', 'Cocoa · Côte d’Ivoire', 'industry', '', '{"href":"/industries/agriculture/cote-divoire"}'),
('angola', 'Angola', 'country', 'angola', '{"href":"/countries/angola"}'),
('aoa', 'AOA', 'currency', '', '{"href":"/countries/angola"}'),
('luanda', 'Luanda', 'city', 'angola', '{"href":"/cities/luanda","role":"Capital"}'),
('lobito', 'Lobito', 'city', '', '{"href":"/trade/ports/lobito","waters":"Atlantic","corridorSlug":"lobito-corridor"}'),
('lobito-corridor', 'Lobito Corridor', 'corridor', '', '{"href":"/trade/lobito-corridor"}'),
('ao-energy', 'Energy · Angola', 'industry', '', '{"href":"/industries/energy/angola"}'),
('senegal', 'Senegal', 'country', 'senegal', '{"href":"/countries/senegal"}'),
('dakar', 'Dakar', 'city', 'senegal', '{"href":"/cities/dakar","role":"Capital / port","portSlug":"dakar","waters":"Atlantic","corridorSlug":"dakar-bamako"}'),
('sn-energy', 'Energy · Senegal', 'industry', '', '{"href":"/industries/energy/senegal"}'),
('sn-ports', 'Ports · Senegal', 'industry', '', '{"href":"/industries/logistics/senegal"}'),
('mozambique', 'Mozambique', 'country', 'mozambique', '{"href":"/countries/mozambique"}'),
('maputo', 'Maputo', 'city', 'mozambique', '{"href":"/cities/maputo","role":"Capital / port","portSlug":"maputo","waters":"Indian Ocean","corridorSlug":"maputo-corridor"}'),
('durban', 'Durban', 'city', 'south-africa', '{"href":"/cities/durban","role":"Port city","portSlug":"durban","waters":"Indian Ocean","corridorSlug":"maputo-corridor"}'),
('maputo-corridor', 'Maputo Corridor', 'corridor', '', '{"href":"/trade/maputo-corridor"}'),
('mz-energy', 'Energy · Mozambique', 'industry', '', '{"href":"/industries/energy/mozambique"}'),
('zambia', 'Zambia', 'country', 'zambia', '{"href":"/countries/zambia"}'),
('zmw', 'ZMW', 'currency', '', '{"href":"/countries/zambia"}'),
('lusaka', 'Lusaka', 'city', 'zambia', '{"href":"/cities/lusaka","role":"Capital"}'),
('zm-mining', 'Mining · Zambia', 'industry', '', '{"href":"/industries/mining/zambia"}'),
('zm-energy', 'Energy · Zambia', 'industry', '', '{"href":"/industries/energy/zambia"}'),
('tunisia', 'Tunisia', 'country', 'tunisia', '{"href":"/countries/tunisia"}'),
('tnd', 'TND', 'currency', '', '{"href":"/countries/tunisia"}'),
('tunis', 'Tunis', 'city', 'tunisia', '{"href":"/cities/tunis","role":"Capital"}'),
('tn-industry', 'Industry · Tunisia', 'industry', '', '{"href":"/industries/industry/tunisia"}'),
('tn-tourism', 'Tourism · Tunisia', 'industry', '', '{"href":"/industries/tourism/tunisia"}'),
('algeria', 'Algeria', 'country', 'algeria', '{"href":"/countries/algeria"}'),
('dzd', 'DZD', 'currency', '', '{"href":"/countries/algeria"}'),
('algiers', 'Algiers', 'city', 'algeria', '{"href":"/cities/algiers","role":"Capital"}'),
('dz-energy', 'Energy · Algeria', 'industry', '', '{"href":"/industries/energy/algeria"}'),
('dz-banking', 'Banking · Algeria', 'industry', '', '{"href":"/industries/banking/algeria"}'),
('botswana', 'Botswana', 'country', 'botswana', '{"href":"/countries/botswana"}'),
('bwp', 'BWP', 'currency', '', '{"href":"/countries/botswana"}'),
('gaborone', 'Gaborone', 'city', 'botswana', '{"href":"/cities/gaborone","role":"Capital"}'),
('bw-mining', 'Mining · Botswana', 'industry', '', '{"href":"/industries/mining/botswana"}'),
('bw-banking', 'Banking · Botswana', 'industry', '', '{"href":"/industries/banking/botswana"}'),
('cameroon', 'Cameroon', 'country', 'cameroon', '{"href":"/countries/cameroon"}'),
('xaf-cm', 'XAF · CM', 'currency', '', '{"href":"/countries/cameroon"}'),
('douala', 'Douala', 'city', 'cameroon', '{"href":"/cities/douala","role":"Commercial / port"}'),
('cm-energy', 'Energy · Cameroon', 'industry', '', '{"href":"/industries/energy/cameroon"}'),
('cm-agriculture', 'Agriculture · Cameroon', 'industry', '', '{"href":"/industries/agriculture/cameroon"}'),
('namibia', 'Namibia', 'country', 'namibia', '{"href":"/countries/namibia"}'),
('nad', 'NAD', 'currency', '', '{"href":"/countries/namibia"}'),
('windhoek', 'Windhoek', 'city', 'namibia', '{"href":"/cities/windhoek","role":"Capital"}'),
('na-mining', 'Mining · Namibia', 'industry', '', '{"href":"/industries/mining/namibia"}'),
('na-banking', 'Banking · Namibia', 'industry', '', '{"href":"/industries/banking/namibia"}'),
('walvis-bay', 'Walvis Bay', 'city', '', '{"href":"/trade/ports/walvis-bay","waters":"Atlantic","corridorSlug":"trans-kalahari"}'),
('trans-kalahari', 'Trans-Kalahari Corridor', 'corridor', '', '{"href":"/trade/trans-kalahari"}'),
('libya', 'Libya', 'country', 'libya', '{"href":"/countries/libya"}'),
('lyd', 'LYD', 'currency', '', '{"href":"/countries/libya"}'),
('tripoli', 'Tripoli', 'city', 'libya', '{"href":"/cities/tripoli","role":"Capital"}'),
('ly-energy', 'Energy · Libya', 'industry', '', '{"href":"/industries/energy/libya"}'),
('ly-oil', 'Oil · Libya', 'industry', '', '{"href":"/industries/oil/libya"}'),
('zimbabwe', 'Zimbabwe', 'country', 'zimbabwe', '{"href":"/countries/zimbabwe"}'),
('zwg', 'ZWG', 'currency', '', '{"href":"/countries/zimbabwe"}'),
('harare', 'Harare', 'city', 'zimbabwe', '{"href":"/cities/harare","role":"Capital"}'),
('beira', 'Beira', 'city', '', '{"href":"/trade/ports/beira","waters":"Indian Ocean","corridorSlug":"beira-corridor"}'),
('beira-corridor', 'Beira Corridor', 'corridor', '', '{"href":"/trade/beira-corridor"}'),
('mauritius', 'Mauritius', 'country', 'mauritius', '{"href":"/countries/mauritius"}'),
('mur', 'MUR', 'currency', '', '{"href":"/countries/mauritius"}'),
('port-louis', 'Port Louis', 'city', 'mauritius', '{"href":"/cities/port-louis","role":"Capital / finance"}'),
('mu-finance', 'Finance · Mauritius', 'industry', '', '{"href":"/industries/finance/mauritius"}'),
('mu-services', 'Services · Mauritius', 'industry', '', '{"href":"/industries/services/mauritius"}'),
('djibouti', 'Djibouti', 'country', 'djibouti', '{"href":"/countries/djibouti","waters":"Red Sea / Gulf of Aden","corridorSlug":"djibouti-addis"}'),
('djf', 'DJF', 'currency', '', '{"href":"/countries/djibouti"}'),
('djibouti-city', 'Djibouti City', 'city', 'djibouti', '{"href":"/cities/djibouti-city","role":"Capital / port","portSlug":"djibouti"}'),
('dj-ports', 'Ports · Djibouti', 'industry', '', '{"href":"/industries/logistics/djibouti"}'),
('dj-logistics', 'Logistics · Djibouti', 'industry', '', '{"href":"/industries/logistics/djibouti"}'),
('gabon', 'Gabon', 'country', 'gabon', '{"href":"/countries/gabon"}'),
('xaf-ga', 'XAF · GA', 'currency', '', '{"href":"/countries/gabon"}'),
('libreville', 'Libreville', 'city', 'gabon', '{"href":"/cities/libreville","role":"Capital"}'),
('ga-oil', 'Oil · Gabon', 'industry', '', '{"href":"/industries/oil/gabon"}'),
('ga-timber', 'Timber · Gabon', 'industry', '', '{"href":"/industries/timber/gabon"}'),
('malawi', 'Malawi', 'country', 'malawi', '{"href":"/countries/malawi"}'),
('mwk', 'MWK', 'currency', '', '{"href":"/countries/malawi"}'),
('lilongwe', 'Lilongwe', 'city', 'malawi', '{"href":"/cities/lilongwe","role":"Capital"}'),
('mw-agriculture', 'Agriculture · Malawi', 'industry', '', '{"href":"/industries/agriculture/malawi"}'),
('benin', 'Benin', 'country', 'benin', '{"href":"/countries/benin"}'),
('xof-bj', 'XOF · BJ', 'currency', '', '{"href":"/countries/benin"}'),
('cotonou', 'Cotonou', 'city', 'benin', '{"href":"/cities/cotonou","role":"Commercial / port"}'),
('bj-agriculture', 'Agriculture · Benin', 'industry', '', '{"href":"/industries/agriculture/benin"}'),
('bj-ports', 'Ports · Benin', 'industry', '', '{"href":"/industries/logistics/benin"}'),
('togo', 'Togo', 'country', 'togo', '{"href":"/countries/togo"}'),
('xof-tg', 'XOF · TG', 'currency', '', '{"href":"/countries/togo"}'),
('lome', 'Lomé', 'city', 'togo', '{"href":"/cities/lome","role":"Capital / port","portSlug":"lome","waters":"Atlantic","corridorSlug":"abidjan-lagos"}'),
('tg-ports', 'Ports · Togo', 'industry', '', '{"href":"/industries/logistics/togo"}'),
('mali', 'Mali', 'country', 'mali', '{"href":"/countries/mali"}'),
('xof-ml', 'XOF · ML', 'currency', '', '{"href":"/countries/mali"}'),
('bamako', 'Bamako', 'city', 'mali', '{"href":"/cities/bamako","role":"Capital"}'),
('ml-gold', 'Gold · Mali', 'industry', '', '{"href":"/industries/mining/mali"}'),
('ml-agriculture', 'Agriculture · Mali', 'industry', '', '{"href":"/industries/agriculture/mali"}'),
('niger', 'Niger', 'country', 'niger', '{"href":"/countries/niger"}'),
('xof-ne', 'XOF · NE', 'currency', '', '{"href":"/countries/niger"}'),
('niamey', 'Niamey', 'city', 'niger', '{"href":"/cities/niamey","role":"Capital"}'),
('ne-uranium', 'Uranium · Niger', 'industry', '', '{"href":"/industries/mining/niger"}'),
('burkina-faso', 'Burkina Faso', 'country', 'burkina-faso', '{"href":"/countries/burkina-faso"}'),
('xof-bf', 'XOF · BF', 'currency', '', '{"href":"/countries/burkina-faso"}'),
('ouagadougou', 'Ouagadougou', 'city', 'burkina-faso', '{"href":"/cities/ouagadougou","role":"Capital"}'),
('bf-gold', 'Gold · Burkina Faso', 'industry', '', '{"href":"/industries/mining/burkina-faso"}'),
('bf-agriculture', 'Agriculture · Burkina Faso', 'industry', '', '{"href":"/industries/agriculture/burkina-faso"}'),
('guinea', 'Guinea', 'country', 'guinea', '{"href":"/countries/guinea"}'),
('gnf', 'GNF', 'currency', '', '{"href":"/countries/guinea"}'),
('conakry', 'Conakry', 'city', 'guinea', '{"href":"/cities/conakry","role":"Capital / port","portSlug":"conakry","waters":"Atlantic","corridorSlug":"conakry-bamako"}'),
('gn-mining', 'Mining · Guinea', 'industry', '', '{"href":"/industries/mining/guinea"}'),
('liberia', 'Liberia', 'country', 'liberia', '{"href":"/countries/liberia"}'),
('lrd', 'LRD', 'currency', '', '{"href":"/countries/liberia"}'),
('monrovia', 'Monrovia', 'city', 'liberia', '{"href":"/cities/monrovia","role":"Capital"}'),
('lr-mining', 'Mining · Liberia', 'industry', '', '{"href":"/industries/mining/liberia"}'),
('sierra-leone', 'Sierra Leone', 'country', 'sierra-leone', '{"href":"/countries/sierra-leone"}'),
('sle', 'SLE', 'currency', '', '{"href":"/countries/sierra-leone"}'),
('freetown', 'Freetown', 'city', 'sierra-leone', '{"href":"/cities/freetown","role":"Capital / port","portSlug":"freetown","waters":"Atlantic","corridorSlug":"freetown-monrovia"}'),
('sl-mining', 'Mining · Sierra Leone', 'industry', '', '{"href":"/industries/mining/sierra-leone"}'),
('mauritania', 'Mauritania', 'country', 'mauritania', '{"href":"/countries/mauritania"}'),
('mru', 'MRU', 'currency', '', '{"href":"/countries/mauritania"}'),
('nouakchott', 'Nouakchott', 'city', 'mauritania', '{"href":"/cities/nouakchott","role":"Capital"}'),
('mr-mining', 'Mining · Mauritania', 'industry', '', '{"href":"/industries/mining/mauritania"}'),
('gambia', 'Gambia', 'country', 'gambia', '{"href":"/countries/gambia"}'),
('gmd', 'GMD', 'currency', '', '{"href":"/countries/gambia"}'),
('banjul', 'Banjul', 'city', 'gambia', '{"href":"/cities/banjul","role":"Capital"}'),
('gm-agriculture', 'Agriculture · Gambia', 'industry', '', '{"href":"/industries/agriculture/gambia"}'),
('chad', 'Chad', 'country', 'chad', '{"href":"/countries/chad"}'),
('xaf-td', 'XAF · TD', 'currency', '', '{"href":"/countries/chad"}'),
('ndjamena', 'N’Djamena', 'city', 'chad', '{"href":"/cities/ndjamena","role":"Capital"}'),
('td-oil', 'Oil · Chad', 'industry', '', '{"href":"/industries/oil/chad"}'),
('madagascar', 'Madagascar', 'country', 'madagascar', '{"href":"/countries/madagascar"}'),
('mga', 'MGA', 'currency', '', '{"href":"/countries/madagascar"}'),
('antananarivo', 'Antananarivo', 'city', 'madagascar', '{"href":"/cities/antananarivo","role":"Capital"}'),
('mg-agriculture', 'Agriculture · Madagascar', 'industry', '', '{"href":"/industries/agriculture/madagascar"}'),
('congo', 'Congo', 'country', 'congo', '{"href":"/countries/congo"}'),
('xaf-cg', 'XAF · CG', 'currency', '', '{"href":"/countries/congo"}'),
('brazzaville', 'Brazzaville', 'city', 'congo', '{"href":"/cities/brazzaville","role":"Capital"}'),
('cg-oil', 'Oil · Congo', 'industry', '', '{"href":"/industries/oil/congo"}'),
('burundi', 'Burundi', 'country', 'burundi', '{"href":"/countries/burundi"}'),
('bif', 'BIF', 'currency', '', '{"href":"/countries/burundi"}'),
('bujumbura', 'Bujumbura', 'city', 'burundi', '{"href":"/cities/bujumbura","role":"Commercial capital"}'),
('bi-agriculture', 'Agriculture · Burundi', 'industry', '', '{"href":"/industries/agriculture/burundi"}'),
('central-african-republic', 'Central African Republic', 'country', 'central-african-republic', '{"href":"/countries/central-african-republic"}'),
('xaf-cf', 'XAF · CF', 'currency', '', '{"href":"/countries/central-african-republic"}'),
('bangui', 'Bangui', 'city', 'central-african-republic', '{"href":"/cities/bangui","role":"Capital"}'),
('cf-mining', 'Mining · CAR', 'industry', '', '{"href":"/industries/mining/central-african-republic"}'),
('equatorial-guinea', 'Equatorial Guinea', 'country', 'equatorial-guinea', '{"href":"/countries/equatorial-guinea"}'),
('xaf-gq', 'XAF · GQ', 'currency', '', '{"href":"/countries/equatorial-guinea"}'),
('malabo', 'Malabo', 'city', 'equatorial-guinea', '{"href":"/cities/malabo","role":"Capital"}'),
('gq-energy', 'Oil · Equatorial Guinea', 'industry', '', '{"href":"/industries/energy/equatorial-guinea"}'),
('dr-congo', 'DR Congo', 'country', 'dr-congo', '{"href":"/countries/dr-congo"}'),
('cdf', 'CDF', 'currency', '', '{"href":"/countries/dr-congo"}'),
('kinshasa', 'Kinshasa', 'city', 'dr-congo', '{"href":"/cities/kinshasa","role":"Capital"}'),
('cd-mining', 'Mining · DR Congo', 'industry', '', '{"href":"/industries/mining/dr-congo"}'),
('cd-infrastructure', 'Infrastructure · DR Congo', 'industry', '', '{"href":"/industries/infrastructure/dr-congo"}'),
('sao-tome-and-principe', 'São Tomé and Príncipe', 'country', 'sao-tome-and-principe', '{"href":"/countries/sao-tome-and-principe"}'),
('stn', 'STN', 'currency', '', '{"href":"/countries/sao-tome-and-principe"}'),
('sao-tome', 'São Tomé', 'city', 'sao-tome-and-principe', '{"href":"/cities/sao-tome","role":"Capital"}'),
('st-agriculture', 'Agriculture · São Tomé and Príncipe', 'industry', '', '{"href":"/industries/agriculture/sao-tome-and-principe"}'),
('south-sudan', 'South Sudan', 'country', 'south-sudan', '{"href":"/countries/south-sudan"}'),
('ssp', 'SSP', 'currency', '', '{"href":"/countries/south-sudan"}'),
('juba', 'Juba', 'city', 'south-sudan', '{"href":"/cities/juba","role":"Capital"}'),
('ss-energy', 'Oil · South Sudan', 'industry', '', '{"href":"/industries/energy/south-sudan"}'),
('sudan', 'Sudan', 'country', 'sudan', '{"href":"/countries/sudan"}'),
('sdg', 'SDG', 'currency', '', '{"href":"/countries/sudan"}'),
('khartoum', 'Khartoum', 'city', 'sudan', '{"href":"/cities/khartoum","role":"Capital"}'),
('sd-agriculture', 'Agriculture · Sudan', 'industry', '', '{"href":"/industries/agriculture/sudan"}'),
('eritrea', 'Eritrea', 'country', 'eritrea', '{"href":"/countries/eritrea"}'),
('ern', 'ERN', 'currency', '', '{"href":"/countries/eritrea"}'),
('asmara', 'Asmara', 'city', 'eritrea', '{"href":"/cities/asmara","role":"Capital"}'),
('er-mining', 'Mining · Eritrea', 'industry', '', '{"href":"/industries/mining/eritrea"}'),
('somalia', 'Somalia', 'country', 'somalia', '{"href":"/countries/somalia"}'),
('sos', 'SOS', 'currency', '', '{"href":"/countries/somalia"}'),
('mogadishu', 'Mogadishu', 'city', 'somalia', '{"href":"/cities/mogadishu","role":"Capital"}'),
('so-livestock', 'Livestock · Somalia', 'industry', '', '{"href":"/industries/agriculture/somalia"}'),
('so-remittances', 'Remittances · Somalia', 'industry', '', '{"href":"/industries/industry/somalia"}'),
('cabo-verde', 'Cabo Verde', 'country', 'cabo-verde', '{"href":"/countries/cabo-verde"}'),
('cve', 'CVE', 'currency', '', '{"href":"/countries/cabo-verde"}'),
('praia', 'Praia', 'city', 'cabo-verde', '{"href":"/cities/praia","role":"Capital"}'),
('cv-tourism', 'Tourism · Cabo Verde', 'industry', '', '{"href":"/industries/tourism/cabo-verde"}'),
('cv-services', 'Services · Cabo Verde', 'industry', '', '{"href":"/industries/industry/cabo-verde"}'),
('guinea-bissau', 'Guinea-Bissau', 'country', 'guinea-bissau', '{"href":"/countries/guinea-bissau"}'),
('xof-gw', 'XOF · GW', 'currency', '', '{"href":"/countries/guinea-bissau"}'),
('bissau', 'Bissau', 'city', 'guinea-bissau', '{"href":"/cities/bissau","role":"Capital"}'),
('gw-agriculture', 'Agriculture · Guinea-Bissau', 'industry', '', '{"href":"/industries/agriculture/guinea-bissau"}'),
('comoros', 'Comoros', 'country', 'comoros', '{"href":"/countries/comoros"}'),
('kmf', 'KMF', 'currency', '', '{"href":"/countries/comoros"}'),
('moroni', 'Moroni', 'city', 'comoros', '{"href":"/cities/moroni","role":"Capital"}'),
('km-agriculture', 'Agriculture · Comoros', 'industry', '', '{"href":"/industries/agriculture/comoros"}'),
('eswatini', 'Eswatini', 'country', 'eswatini', '{"href":"/countries/eswatini"}'),
('szl', 'SZL', 'currency', '', '{"href":"/countries/eswatini"}'),
('mbabane', 'Mbabane', 'city', 'eswatini', '{"href":"/cities/mbabane","role":"Administrative capital"}'),
('sz-agriculture', 'Agriculture · Eswatini', 'industry', '', '{"href":"/industries/agriculture/eswatini"}'),
('lesotho', 'Lesotho', 'country', 'lesotho', '{"href":"/countries/lesotho"}'),
('lsl', 'LSL', 'currency', '', '{"href":"/countries/lesotho"}'),
('maseru', 'Maseru', 'city', 'lesotho', '{"href":"/cities/maseru","role":"Capital"}'),
('ls-water', 'Water · Lesotho', 'industry', '', '{"href":"/industries/industry/lesotho"}'),
('ls-apparel', 'Apparel · Lesotho', 'industry', '', '{"href":"/industries/industry/lesotho"}'),
('seychelles', 'Seychelles', 'country', 'seychelles', '{"href":"/countries/seychelles"}'),
('scr', 'SCR', 'currency', '', '{"href":"/countries/seychelles"}'),
('victoria', 'Victoria', 'city', 'seychelles', '{"href":"/cities/victoria","role":"Capital"}'),
('sc-tourism', 'Tourism · Seychelles', 'industry', '', '{"href":"/industries/tourism/seychelles"}'),
('sc-finance', 'Finance · Seychelles', 'industry', '', '{"href":"/industries/banking/seychelles"}'),
('abidjan-lagos', 'Abidjan–Lagos Corridor', 'corridor', '', '{"href":"/trade/abidjan-lagos"}'),
('nacala', 'Nacala', 'city', 'mozambique', '{"href":"/trade/ports/nacala","role":"Port city","portSlug":"nacala","waters":"Indian Ocean","corridorSlug":"nacala-corridor"}'),
('nacala-corridor', 'Nacala Corridor', 'corridor', '', '{"href":"/trade/nacala-corridor"}'),
('lamu', 'Lamu', 'city', 'kenya', '{"href":"/trade/ports/lamu","role":"Port city","portSlug":"lamu","waters":"Indian Ocean","corridorSlug":"lapsset"}'),
('lapsset', 'LAPSSET Corridor', 'corridor', '', '{"href":"/trade/lapsset"}'),
('north-south-corridor', 'North-South Corridor', 'corridor', '', '{"href":"/trade/north-south-corridor"}'),
('douala-ndjamena', 'Douala–N''Djamena Corridor', 'corridor', '', '{"href":"/trade/douala-ndjamena"}'),
('ndola', 'Ndola', 'city', 'zambia', '{"href":"/cities/ndola","role":"Copperbelt"}'),
('walvis-ndola', 'Walvis Bay–Ndola Corridor', 'corridor', '', '{"href":"/trade/walvis-ndola"}'),
('djibouti-addis', 'Djibouti–Addis Corridor', 'corridor', '', '{"href":"/trade/djibouti-addis"}'),
('dakar-bamako', 'Dakar–Bamako Corridor', 'corridor', '', '{"href":"/trade/dakar-bamako"}'),
('cotonou-niamey', 'Cotonou–Niamey Corridor', 'corridor', '', '{"href":"/trade/cotonou-niamey"}'),
('lome-ouagadougou', 'Lomé–Ouagadougou Corridor', 'corridor', '', '{"href":"/trade/lome-ouagadougou"}'),
('abidjan-ouagadougou', 'Abidjan–Ouagadougou Corridor', 'corridor', '', '{"href":"/trade/abidjan-ouagadougou"}'),
('conakry-bamako', 'Conakry–Bamako Corridor', 'corridor', '', '{"href":"/trade/conakry-bamako"}'),
('pointe-noire', 'Pointe-Noire', 'city', 'congo', '{"href":"/trade/ports/pointe-noire","role":"Port city","portSlug":"pointe-noire","waters":"Atlantic","corridorSlug":"pointe-noire-brazzaville"}'),
('pointe-noire-brazzaville', 'Pointe-Noire–Brazzaville Corridor', 'corridor', 'congo', '{"href":"/trade/pointe-noire-brazzaville"}'),
('tazara', 'TAZARA', 'corridor', '', '{"href":"/trade/tazara"}'),
('douala-bangui', 'Douala–Bangui Corridor', 'corridor', '', '{"href":"/trade/douala-bangui"}'),
('tema-ouagadougou', 'Tema–Ouagadougou Corridor', 'corridor', '', '{"href":"/trade/tema-ouagadougou"}'),
('abidjan-bamako', 'Abidjan–Bamako Corridor', 'corridor', '', '{"href":"/trade/abidjan-bamako"}'),
('lome-niamey', 'Lomé–Niamey Corridor', 'corridor', '', '{"href":"/trade/lome-niamey"}'),
('nouakchott-dakar', 'Nouakchott–Dakar Corridor', 'corridor', '', '{"href":"/trade/nouakchott-dakar"}'),
('lagos-niamey', 'Lagos–Niamey Corridor', 'corridor', '', '{"href":"/trade/lagos-niamey"}'),
('matadi', 'Matadi', 'city', 'dr-congo', '{"href":"/trade/ports/matadi","role":"Port city","portSlug":"matadi","waters":"Atlantic","corridorSlug":"matadi-kinshasa"}'),
('matadi-kinshasa', 'Matadi–Kinshasa Corridor', 'corridor', 'dr-congo', '{"href":"/trade/matadi-kinshasa"}'),
('berbera', 'Berbera', 'city', 'somalia', '{"href":"/trade/ports/berbera","role":"Port city","portSlug":"berbera","waters":"Gulf of Aden","corridorSlug":"berbera-addis"}'),
('berbera-addis', 'Berbera–Addis Corridor', 'corridor', '', '{"href":"/trade/berbera-addis"}'),
('cape-town', 'Cape Town', 'city', 'south-africa', '{"href":"/cities/cape-town","role":"Port city","portSlug":"cape-town","waters":"Atlantic","corridorSlug":"cape-town-johannesburg"}'),
('cape-town-johannesburg', 'Cape Town–Johannesburg Corridor', 'corridor', 'south-africa', '{"href":"/trade/cape-town-johannesburg"}'),
('alexandria', 'Alexandria', 'city', 'egypt', '{"href":"/cities/alexandria","role":"Port city","portSlug":"alexandria","waters":"Mediterranean","corridorSlug":"alexandria-cairo"}'),
('alexandria-cairo', 'Alexandria–Cairo Corridor', 'corridor', 'egypt', '{"href":"/trade/alexandria-cairo"}'),
('port-said', 'Port Said', 'city', 'egypt', '{"href":"/cities/port-said","role":"Port city","portSlug":"port-said","waters":"Mediterranean / Suez","corridorSlug":"port-said-cairo"}'),
('port-said-cairo', 'Port Said–Cairo Corridor', 'corridor', 'egypt', '{"href":"/trade/port-said-cairo"}'),
('banjul-dakar', 'Banjul–Dakar Corridor', 'corridor', '', '{"href":"/trade/banjul-dakar"}'),
('freetown-monrovia', 'Freetown–Monrovia Corridor', 'corridor', '', '{"href":"/trade/freetown-monrovia"}'),
('luanda-lobito', 'Luanda–Lobito Corridor', 'corridor', 'angola', '{"href":"/trade/luanda-lobito"}'),
('port-sudan', 'Port Sudan', 'city', 'sudan', '{"href":"/cities/port-sudan","role":"Port city","portSlug":"port-sudan","waters":"Red Sea","corridorSlug":"port-sudan-khartoum"}'),
('port-sudan-khartoum', 'Port Sudan–Khartoum Corridor', 'corridor', 'sudan', '{"href":"/trade/port-sudan-khartoum"}'),
('toamasina', 'Toamasina', 'city', 'madagascar', '{"href":"/cities/toamasina","role":"Port city","portSlug":"toamasina","waters":"Indian Ocean","corridorSlug":"toamasina-antananarivo"}'),
('toamasina-antananarivo', 'Toamasina–Antananarivo Corridor', 'corridor', 'madagascar', '{"href":"/trade/toamasina-antananarivo"}'),
('abuja', 'Abuja', 'city', 'nigeria', '{"href":"/cities/abuja","role":"Federal capital"}'),
('yaounde', 'Yaoundé', 'city', 'cameroon', '{"href":"/cities/yaounde","role":"Capital"}'),
('massawa', 'Massawa', 'city', 'eritrea', '{"href":"/cities/massawa","role":"Port city","portSlug":"massawa","waters":"Red Sea","corridorSlug":"massawa-asmara"}'),
('mbabane-maputo', 'Mbabane–Maputo Corridor', 'corridor', '', '{"href":"/trade/mbabane-maputo"}'),
('maseru-johannesburg', 'Maseru–Johannesburg Corridor', 'corridor', '', '{"href":"/trade/maseru-johannesburg"}'),
('bissau-dakar', 'Bissau–Dakar Corridor', 'corridor', '', '{"href":"/trade/bissau-dakar"}'),
('mogadishu-berbera', 'Mogadishu–Berbera Corridor', 'corridor', 'somalia', '{"href":"/trade/mogadishu-berbera"}'),
('accra-tema', 'Accra–Tema Corridor', 'corridor', 'ghana', '{"href":"/trade/accra-tema"}'),
('abuja-lagos', 'Abuja–Lagos Corridor', 'corridor', 'nigeria', '{"href":"/trade/abuja-lagos"}'),
('douala-yaounde', 'Douala–Yaoundé Corridor', 'corridor', 'cameroon', '{"href":"/trade/douala-yaounde"}'),
('massawa-asmara', 'Massawa–Asmara Corridor', 'corridor', 'eritrea', '{"href":"/trade/massawa-asmara"}'),
('tangier', 'Tangier', 'city', 'morocco', '{"href":"/cities/tangier","role":"Port city","portSlug":"tangier","waters":"Mediterranean / Strait of Gibraltar","corridorSlug":"tangier-casablanca"}'),
('tangier-casablanca', 'Tangier–Casablanca Corridor', 'corridor', 'morocco', '{"href":"/trade/tangier-casablanca"}'),
('sfax', 'Sfax', 'city', 'tunisia', '{"href":"/cities/sfax","role":"Port city","portSlug":"sfax","waters":"Mediterranean","corridorSlug":"tunis-sfax"}'),
('tunis-sfax', 'Tunis–Sfax Corridor', 'corridor', 'tunisia', '{"href":"/trade/tunis-sfax"}'),
('oran', 'Oran', 'city', 'algeria', '{"href":"/cities/oran","role":"Port city","portSlug":"oran","waters":"Mediterranean","corridorSlug":"algiers-oran"}'),
('algiers-oran', 'Algiers–Oran Corridor', 'corridor', 'algeria', '{"href":"/trade/algiers-oran"}'),
('benghazi', 'Benghazi', 'city', 'libya', '{"href":"/cities/benghazi","role":"Port city","portSlug":"benghazi","waters":"Mediterranean","corridorSlug":"tripoli-benghazi"}'),
('tripoli-benghazi', 'Tripoli–Benghazi Corridor', 'corridor', 'libya', '{"href":"/trade/tripoli-benghazi"}'),
('port-gentil', 'Port-Gentil', 'city', 'gabon', '{"href":"/cities/port-gentil","role":"Port city","portSlug":"port-gentil","waters":"Atlantic","corridorSlug":"libreville-port-gentil"}'),
('libreville-port-gentil', 'Libreville–Port-Gentil Corridor', 'corridor', 'gabon', '{"href":"/trade/libreville-port-gentil"}'),
('bata', 'Bata', 'city', 'equatorial-guinea', '{"href":"/cities/bata","role":"Port city","portSlug":"bata","waters":"Atlantic","corridorSlug":"malabo-bata"}'),
('malabo-bata', 'Malabo–Bata Corridor', 'corridor', 'equatorial-guinea', '{"href":"/trade/malabo-bata"}'),
('nouadhibou', 'Nouadhibou', 'city', 'mauritania', '{"href":"/cities/nouadhibou","role":"Port city","portSlug":"nouadhibou","waters":"Atlantic","corridorSlug":"nouakchott-nouadhibou"}'),
('nouakchott-nouadhibou', 'Nouakchott–Nouadhibou Corridor', 'corridor', 'mauritania', '{"href":"/trade/nouakchott-nouadhibou"}'),
('lusaka-ndola', 'Lusaka–Ndola Corridor', 'corridor', 'zambia', '{"href":"/trade/lusaka-ndola"}'),
('beira-lilongwe', 'Beira–Lilongwe Corridor', 'corridor', '', '{"href":"/trade/beira-lilongwe"}'),
('bulawayo', 'Bulawayo', 'city', 'zimbabwe', '{"href":"/cities/bulawayo","role":"Inland city"}'),
('harare-bulawayo', 'Harare–Bulawayo Corridor', 'corridor', 'zimbabwe', '{"href":"/trade/harare-bulawayo"}'),
('kumasi', 'Kumasi', 'city', 'ghana', '{"href":"/cities/kumasi","role":"Inland city"}'),
('accra-kumasi', 'Accra–Kumasi Corridor', 'corridor', 'ghana', '{"href":"/trade/accra-kumasi"}'),
('brazzaville-kinshasa', 'Brazzaville–Kinshasa Corridor', 'corridor', '', '{"href":"/trade/brazzaville-kinshasa"}'),
('francistown', 'Francistown', 'city', 'botswana', '{"href":"/cities/francistown","role":"Inland city"}'),
('gaborone-francistown', 'Gaborone–Francistown Corridor', 'corridor', 'botswana', '{"href":"/trade/gaborone-francistown"}'),
('windhoek-walvis-bay', 'Windhoek–Walvis Bay Corridor', 'corridor', 'namibia', '{"href":"/trade/windhoek-walvis-bay"}'),
('mombasa-nairobi', 'Mombasa–Nairobi Corridor', 'corridor', 'kenya', '{"href":"/trade/mombasa-nairobi"}'),
('dodoma', 'Dodoma', 'city', 'tanzania', '{"href":"/cities/dodoma","role":"Capital"}'),
('dar-es-salaam-dodoma', 'Dar es Salaam–Dodoma Corridor', 'corridor', 'tanzania', '{"href":"/trade/dar-es-salaam-dodoma"}'),
('kano', 'Kano', 'city', 'nigeria', '{"href":"/cities/kano","role":"Inland city"}'),
('kano-lagos', 'Kano–Lagos Corridor', 'corridor', 'nigeria', '{"href":"/trade/kano-lagos"}'),
('blantyre', 'Blantyre', 'city', 'malawi', '{"href":"/cities/blantyre","role":"Commercial city"}'),
('blantyre-lilongwe', 'Blantyre–Lilongwe Corridor', 'corridor', 'malawi', '{"href":"/trade/blantyre-lilongwe"}'),
('aswan', 'Aswan', 'city', 'egypt', '{"href":"/cities/aswan","role":"Inland city"}'),
('cairo-aswan', 'Cairo–Aswan Corridor', 'corridor', 'egypt', '{"href":"/trade/cairo-aswan"}'),
('marrakech', 'Marrakech', 'city', 'morocco', '{"href":"/cities/marrakech","role":"Inland city"}'),
('casablanca-marrakech', 'Casablanca–Marrakech Corridor', 'corridor', 'morocco', '{"href":"/trade/casablanca-marrakech"}'),
('durban-johannesburg', 'Durban–Johannesburg Corridor', 'corridor', 'south-africa', '{"href":"/trade/durban-johannesburg"}'),
('kampala-kigali', 'Kampala–Kigali Corridor', 'corridor', '', '{"href":"/trade/kampala-kigali"}'),
('juba-kampala', 'Juba–Kampala Corridor', 'corridor', '', '{"href":"/trade/juba-kampala"}'),
('ouagadougou-niamey', 'Ouagadougou–Niamey Corridor', 'corridor', '', '{"href":"/trade/ouagadougou-niamey"}'),
('addis-ababa-nairobi', 'Addis Ababa–Nairobi Corridor', 'corridor', '', '{"href":"/trade/addis-ababa-nairobi"}'),
('bamako-ouagadougou', 'Bamako–Ouagadougou Corridor', 'corridor', '', '{"href":"/trade/bamako-ouagadougou"}'),
('niamey-kano', 'Niamey–Kano Corridor', 'corridor', '', '{"href":"/trade/niamey-kano"}'),
('constantine', 'Constantine', 'city', 'algeria', '{"href":"/cities/constantine","role":"Inland city"}'),
('algiers-constantine', 'Algiers–Constantine Corridor', 'corridor', 'algeria', '{"href":"/trade/algiers-constantine"}'),
('takoradi', 'Takoradi', 'city', 'ghana', '{"href":"/cities/takoradi","role":"Port city","portSlug":"takoradi","waters":"Atlantic","corridorSlug":"accra-takoradi"}'),
('accra-takoradi', 'Accra–Takoradi Corridor', 'corridor', 'ghana', '{"href":"/trade/accra-takoradi"}'),
('kigali-bujumbura', 'Kigali–Bujumbura Corridor', 'corridor', '', '{"href":"/trade/kigali-bujumbura"}'),
('lusaka-harare', 'Lusaka–Harare Corridor', 'corridor', '', '{"href":"/trade/lusaka-harare"}'),
('port-harcourt', 'Port Harcourt', 'city', 'nigeria', '{"href":"/cities/port-harcourt","role":"Port city","portSlug":"port-harcourt","waters":"Atlantic","corridorSlug":"lagos-port-harcourt"}'),
('lagos-port-harcourt', 'Lagos–Port Harcourt Corridor', 'corridor', 'nigeria', '{"href":"/trade/lagos-port-harcourt"}'),
('kisumu', 'Kisumu', 'city', 'kenya', '{"href":"/cities/kisumu","role":"Inland city"}'),
('nairobi-kisumu', 'Nairobi–Kisumu Corridor', 'corridor', 'kenya', '{"href":"/trade/nairobi-kisumu"}'),
('san-pedro', 'San-Pédro', 'city', 'cote-divoire', '{"href":"/cities/san-pedro","role":"Port city","portSlug":"san-pedro","waters":"Atlantic","corridorSlug":"abidjan-san-pedro"}'),
('abidjan-san-pedro', 'Abidjan–San-Pédro Corridor', 'corridor', 'cote-divoire', '{"href":"/trade/abidjan-san-pedro"}'),
('tete', 'Tete', 'city', 'mozambique', '{"href":"/cities/tete","role":"Inland city"}'),
('beira-tete', 'Beira–Tete Corridor', 'corridor', 'mozambique', '{"href":"/trade/beira-tete"}'),
('buchanan', 'Buchanan', 'city', 'liberia', '{"href":"/cities/buchanan","role":"Port city","portSlug":"buchanan","waters":"Atlantic","corridorSlug":"monrovia-buchanan"}'),
('monrovia-buchanan', 'Monrovia–Buchanan Corridor', 'corridor', 'liberia', '{"href":"/trade/monrovia-buchanan"}'),
('rabat', 'Rabat', 'city', 'morocco', '{"href":"/cities/rabat","role":"Capital"}'),
('casablanca-rabat', 'Casablanca–Rabat Corridor', 'corridor', 'morocco', '{"href":"/trade/casablanca-rabat"}'),
('pretoria', 'Pretoria', 'city', 'south-africa', '{"href":"/cities/pretoria","role":"Administrative capital"}'),
('johannesburg-pretoria', 'Johannesburg–Pretoria Corridor', 'corridor', 'south-africa', '{"href":"/trade/johannesburg-pretoria"}'),
('saint-louis', 'Saint-Louis', 'city', 'senegal', '{"href":"/cities/saint-louis","role":"City"}'),
('dakar-saint-louis', 'Dakar–Saint-Louis Corridor', 'corridor', 'senegal', '{"href":"/trade/dakar-saint-louis"}'),
('tamale', 'Tamale', 'city', 'ghana', '{"href":"/cities/tamale","role":"Inland city"}'),
('accra-tamale', 'Accra–Tamale Corridor', 'corridor', 'ghana', '{"href":"/trade/accra-tamale"}'),
('namibe', 'Namibe', 'city', 'angola', '{"href":"/cities/namibe","role":"Port city","portSlug":"namibe","waters":"Atlantic","corridorSlug":"luanda-namibe"}'),
('luanda-namibe', 'Luanda–Namibe Corridor', 'corridor', 'angola', '{"href":"/trade/luanda-namibe"}'),
('lubumbashi', 'Lubumbashi', 'city', 'dr-congo', '{"href":"/cities/lubumbashi","role":"Inland city"}'),
('kinshasa-lubumbashi', 'Kinshasa–Lubumbashi Corridor', 'corridor', 'dr-congo', '{"href":"/trade/kinshasa-lubumbashi"}'),
('annaba', 'Annaba', 'city', 'algeria', '{"href":"/cities/annaba","role":"Port city","portSlug":"annaba","waters":"Mediterranean","corridorSlug":"algiers-annaba"}'),
('algiers-annaba', 'Algiers–Annaba Corridor', 'corridor', 'algeria', '{"href":"/trade/algiers-annaba"}'),
('calabar', 'Calabar', 'city', 'nigeria', '{"href":"/cities/calabar","role":"Port city","portSlug":"calabar","waters":"Atlantic","corridorSlug":"lagos-calabar"}'),
('lagos-calabar', 'Lagos–Calabar Corridor', 'corridor', 'nigeria', '{"href":"/trade/lagos-calabar"}'),
('entebbe', 'Entebbe', 'city', 'uganda', '{"href":"/cities/entebbe","role":"City"}'),
('kampala-entebbe', 'Kampala–Entebbe Corridor', 'corridor', 'uganda', '{"href":"/trade/kampala-entebbe"}'),
('mwanza', 'Mwanza', 'city', 'tanzania', '{"href":"/cities/mwanza","role":"Inland city"}'),
('dar-es-salaam-mwanza', 'Dar es Salaam–Mwanza Corridor', 'corridor', 'tanzania', '{"href":"/trade/dar-es-salaam-mwanza"}'),
('porto-novo', 'Porto-Novo', 'city', 'benin', '{"href":"/cities/porto-novo","role":"Capital"}'),
('cotonou-porto-novo', 'Cotonou–Porto-Novo Corridor', 'corridor', 'benin', '{"href":"/trade/cotonou-porto-novo"}'),
('kara', 'Kara', 'city', 'togo', '{"href":"/cities/kara","role":"Inland city"}'),
('lome-kara', 'Lomé–Kara Corridor', 'corridor', 'togo', '{"href":"/trade/lome-kara"}'),
('sousse', 'Sousse', 'city', 'tunisia', '{"href":"/cities/sousse","role":"Port city","portSlug":"sousse","waters":"Mediterranean","corridorSlug":"tunis-sousse"}'),
('tunis-sousse', 'Tunis–Sousse Corridor', 'corridor', 'tunisia', '{"href":"/trade/tunis-sousse"}'),
('luxor', 'Luxor', 'city', 'egypt', '{"href":"/cities/luxor","role":"Inland city"}'),
('cairo-luxor', 'Cairo–Luxor Corridor', 'corridor', 'egypt', '{"href":"/trade/cairo-luxor"}'),
('kankan', 'Kankan', 'city', 'guinea', '{"href":"/cities/kankan","role":"Inland city"}'),
('conakry-kankan', 'Conakry–Kankan Corridor', 'corridor', 'guinea', '{"href":"/trade/conakry-kankan"}'),
('franceville', 'Franceville', 'city', 'gabon', '{"href":"/cities/franceville","role":"Inland city"}'),
('libreville-franceville', 'Libreville–Franceville Corridor', 'corridor', 'gabon', '{"href":"/trade/libreville-franceville"}'),
('nakuru', 'Nakuru', 'city', 'kenya', '{"href":"/cities/nakuru","role":"Inland city"}'),
('nairobi-nakuru', 'Nairobi–Nakuru Corridor', 'corridor', 'kenya', '{"href":"/trade/nairobi-nakuru"}'),
('dire-dawa', 'Dire Dawa', 'city', 'ethiopia', '{"href":"/cities/dire-dawa","role":"Inland city"}'),
('addis-ababa-dire-dawa', 'Addis Ababa–Dire Dawa Corridor', 'corridor', 'ethiopia', '{"href":"/trade/addis-ababa-dire-dawa"}'),
('bouake', 'Bouaké', 'city', 'cote-divoire', '{"href":"/cities/bouake","role":"Inland city"}'),
('abidjan-bouake', 'Abidjan–Bouaké Corridor', 'corridor', 'cote-divoire', '{"href":"/trade/abidjan-bouake"}'),
('ibadan', 'Ibadan', 'city', 'nigeria', '{"href":"/cities/ibadan","role":"Inland city"}'),
('lagos-ibadan', 'Lagos–Ibadan Corridor', 'corridor', 'nigeria', '{"href":"/trade/lagos-ibadan"}'),
('bloemfontein', 'Bloemfontein', 'city', 'south-africa', '{"href":"/cities/bloemfontein","role":"Judicial capital"}'),
('johannesburg-bloemfontein', 'Johannesburg–Bloemfontein Corridor', 'corridor', 'south-africa', '{"href":"/trade/johannesburg-bloemfontein"}'),
('livingstone', 'Livingstone', 'city', 'zambia', '{"href":"/cities/livingstone","role":"Inland city"}'),
('lusaka-livingstone', 'Lusaka–Livingstone Corridor', 'corridor', 'zambia', '{"href":"/trade/lusaka-livingstone"}'),
('agadir', 'Agadir', 'city', 'morocco', '{"href":"/cities/agadir","role":"Port city","portSlug":"agadir","waters":"Atlantic","corridorSlug":"marrakech-agadir"}'),
('marrakech-agadir', 'Marrakech–Agadir Corridor', 'corridor', 'morocco', '{"href":"/trade/marrakech-agadir"}'),
('jinja', 'Jinja', 'city', 'uganda', '{"href":"/cities/jinja","role":"Inland city"}'),
('kampala-jinja', 'Kampala–Jinja Corridor', 'corridor', 'uganda', '{"href":"/trade/kampala-jinja"}'),
('garoua', 'Garoua', 'city', 'cameroon', '{"href":"/cities/garoua","role":"Inland city"}'),
('yaounde-garoua', 'Yaoundé–Garoua Corridor', 'corridor', 'cameroon', '{"href":"/trade/yaounde-garoua"}'),
('mutare', 'Mutare', 'city', 'zimbabwe', '{"href":"/cities/mutare","role":"Inland city"}'),
('harare-mutare', 'Harare–Mutare Corridor', 'corridor', 'zimbabwe', '{"href":"/trade/harare-mutare"}'),
('nampula', 'Nampula', 'city', 'mozambique', '{"href":"/cities/nampula","role":"Inland city"}'),
('maputo-nampula', 'Maputo–Nampula Corridor', 'corridor', 'mozambique', '{"href":"/trade/maputo-nampula"}'),
('cape-coast', 'Cape Coast', 'city', 'ghana', '{"href":"/cities/cape-coast","role":"City"}'),
('accra-cape-coast', 'Accra–Cape Coast Corridor', 'corridor', 'ghana', '{"href":"/trade/accra-cape-coast"}'),
('rundu', 'Rundu', 'city', 'namibia', '{"href":"/cities/rundu","role":"Inland city"}'),
('windhoek-rundu', 'Windhoek–Rundu Corridor', 'corridor', 'namibia', '{"href":"/trade/windhoek-rundu"}'),
('maun', 'Maun', 'city', 'botswana', '{"href":"/cities/maun","role":"Inland city"}'),
('gaborone-maun', 'Gaborone–Maun Corridor', 'corridor', 'botswana', '{"href":"/trade/gaborone-maun"}'),
('misrata', 'Misrata', 'city', 'libya', '{"href":"/cities/misrata","role":"Port city","portSlug":"misrata","waters":"Mediterranean","corridorSlug":"tripoli-misrata"}'),
('tripoli-misrata', 'Tripoli–Misrata Corridor', 'corridor', 'libya', '{"href":"/trade/tripoli-misrata"}'),
('oran-constantine', 'Oran–Constantine Corridor', 'corridor', 'algeria', '{"href":"/trade/oran-constantine"}'),
('zomba', 'Zomba', 'city', 'malawi', '{"href":"/cities/zomba","role":"Inland city"}'),
('blantyre-zomba', 'Blantyre–Zomba Corridor', 'corridor', 'malawi', '{"href":"/trade/blantyre-zomba"}'),
('keren', 'Keren', 'city', 'eritrea', '{"href":"/cities/keren","role":"Inland city"}'),
('asmara-keren', 'Asmara–Keren Corridor', 'corridor', 'eritrea', '{"href":"/trade/asmara-keren"}'),
('malanje', 'Malanje', 'city', 'angola', '{"href":"/cities/malanje","role":"Inland city"}'),
('luanda-malanje', 'Luanda–Malanje Corridor', 'corridor', 'angola', '{"href":"/trade/luanda-malanje"}'),
('fianarantsoa', 'Fianarantsoa', 'city', 'madagascar', '{"href":"/cities/fianarantsoa","role":"Inland city"}'),
('antananarivo-fianarantsoa', 'Antananarivo–Fianarantsoa Corridor', 'corridor', 'madagascar', '{"href":"/trade/antananarivo-fianarantsoa"}'),
('mining', 'Mining', 'industry', '', '{"href":"/industries/mining"}'),
('telecoms', 'Telecoms', 'industry', '', '{"href":"/industries/telecoms"}'),
('logistics', 'Logistics & ports', 'industry', '', '{"href":"/industries/logistics"}'),
('infrastructure', 'Infrastructure', 'industry', '', '{"href":"/industries/infrastructure"}'),
('tourism', 'Tourism', 'industry', '', '{"href":"/industries/tourism"}'),
('consumer', 'Consumer', 'industry', '', '{"href":"/industries/consumer"}'),
('fintech', 'Fintech', 'industry', '', '{"href":"/industries/fintech"}'),
('insurance', 'Insurance', 'industry', '', '{"href":"/industries/insurance"}'),
('industry', 'Industry', 'industry', '', '{"href":"/industries/industry"}')
) as v(slug, name, kind, country, meta)
left join public.countries c on c.slug = v.country and v.country <> ''
on conflict (slug) do update set name = excluded.name, kind = excluded.kind, country_id = excluded.country_id, metadata = excluded.metadata;
