insert into public.entity_relationships (from_entity_id, to_entity_id, rel_type)
select f.id, t.id, v.rel
from (values
('kenya', 'kes', 'currency'),
('kenya', 'cbk', 'central bank'),
('cbk', 'policy-rate', 'policy'),
('cbk', 'banking', 'supervises'),
('cbk', 'governor', 'role'),
('kenya', 'nse', 'exchange'),
('kenya', 'nairobi', 'capital desk'),
('kenya', 'mombasa', 'port city'),
('kenya', 'agriculture', 'sector'),
('kenya', 'energy', 'sector'),
('energy', 'inflation-costs', 'exposes'),
('kenya', 'northern-corridor', 'corridor'),
('nse', 'safaricom', 'lists'),
('nse', 'equity', 'lists'),
('banking', 'equity', 'issuer'),
('nigeria', 'ngn', 'currency'),
('nigeria', 'cbn', 'central bank'),
('cbn', 'ng-policy-rate', 'policy'),
('nigeria', 'ngx', 'exchange'),
('nigeria', 'lagos', 'commercial desk'),
('ngx', 'mtn-nigeria', 'lists'),
('nigeria', 'ng-banking', 'sector'),
('south-africa', 'zar', 'currency'),
('south-africa', 'sarb', 'central bank'),
('south-africa', 'jse', 'exchange'),
('south-africa', 'johannesburg', 'markets desk'),
('jse', 'standard-bank', 'lists'),
('south-africa', 'za-banking', 'sector'),
('egypt', 'egp', 'currency'),
('egypt', 'cbe', 'central bank'),
('egypt', 'egx', 'exchange'),
('egypt', 'cairo', 'capital desk'),
('egypt', 'eg-energy', 'sector'),
('ghana', 'ghs', 'currency'),
('ghana', 'bog', 'central bank'),
('ghana', 'gse', 'exchange'),
('ghana', 'accra', 'capital desk'),
('ghana', 'gh-banking', 'sector'),
('ghana', 'tema', 'port'),
('rwanda', 'rwf', 'currency'),
('rwanda', 'bnr', 'central bank'),
('rwanda', 'kigali', 'capital desk'),
('rwanda', 'rw-fintech', 'sector'),
('rwanda', 'northern-corridor-rw', 'corridor'),
('uganda', 'ugx', 'currency'),
('uganda', 'bou', 'central bank'),
('uganda', 'kampala', 'capital desk'),
('uganda', 'northern-corridor-ug', 'corridor'),
('uganda', 'ug-agriculture', 'sector'),
('tanzania', 'tzs', 'currency'),
('tanzania', 'bot', 'central bank'),
('tanzania', 'dar-es-salaam', 'port desk'),
('tanzania', 'central-corridor', 'corridor'),
('tanzania', 'tz-ports', 'sector'),
('ethiopia', 'etb', 'currency'),
('ethiopia', 'nbe', 'central bank'),
('ethiopia', 'addis-ababa', 'capital desk'),
('ethiopia', 'et-agriculture', 'sector'),
('ethiopia', 'et-aviation', 'sector'),
('northern-corridor', 'kenya', 'spans'),
('northern-corridor', 'uganda', 'spans'),
('northern-corridor', 'rwanda', 'spans'),
('northern-corridor', 'mombasa', 'gateway'),
('morocco', 'mad', 'currency'),
('morocco', 'bam', 'central bank'),
('morocco', 'casablanca', 'markets desk'),
('morocco', 'ma-banking', 'sector'),
('morocco', 'ma-tourism', 'sector'),
('central-corridor', 'tanzania', 'spans'),
('central-corridor', 'rwanda', 'spans'),
('central-corridor', 'dar-es-salaam', 'gateway'),
('cote-divoire', 'xof', 'currency'),
('cote-divoire', 'bceao', 'central bank'),
('cote-divoire', 'abidjan', 'commercial desk'),
('cote-divoire', 'ci-banking', 'sector'),
('cote-divoire', 'ci-cocoa', 'sector'),
('angola', 'aoa', 'currency'),
('angola', 'luanda', 'capital desk'),
('angola', 'lobito', 'port'),
('angola', 'ao-energy', 'sector'),
('lobito-corridor', 'angola', 'spans'),
('lobito-corridor', 'lobito', 'gateway'),
('senegal', 'xof', 'currency'),
('senegal', 'bceao', 'central bank'),
('senegal', 'dakar', 'capital desk'),
('senegal', 'sn-energy', 'sector'),
('senegal', 'sn-ports', 'sector'),
('mozambique', 'maputo', 'capital desk'),
('mozambique', 'mz-energy', 'sector'),
('maputo-corridor', 'mozambique', 'spans'),
('maputo-corridor', 'south-africa', 'spans'),
('maputo-corridor', 'maputo', 'gateway'),
('maputo-corridor', 'durban', 'peer port'),
('zambia', 'zmw', 'currency'),
('zambia', 'lusaka', 'capital desk'),
('zambia', 'zm-mining', 'sector'),
('zambia', 'zm-energy', 'sector'),
('lobito-corridor', 'zambia', 'spans'),
('tunisia', 'tnd', 'currency'),
('tunisia', 'tunis', 'capital desk'),
('tunisia', 'tn-industry', 'sector'),
('tunisia', 'tn-tourism', 'sector'),
('algeria', 'dzd', 'currency'),
('algeria', 'algiers', 'capital desk'),
('algeria', 'dz-energy', 'sector'),
('algeria', 'dz-banking', 'sector'),
('botswana', 'bwp', 'currency'),
('botswana', 'gaborone', 'capital desk'),
('botswana', 'bw-mining', 'sector'),
('botswana', 'bw-banking', 'sector'),
('cameroon', 'xaf-cm', 'currency'),
('cameroon', 'douala', 'commercial desk'),
('cameroon', 'cm-energy', 'sector'),
('cameroon', 'cm-agriculture', 'sector'),
('namibia', 'nad', 'currency'),
('namibia', 'windhoek', 'capital desk'),
('namibia', 'na-mining', 'sector'),
('namibia', 'na-banking', 'sector'),
('trans-kalahari', 'namibia', 'spans'),
('trans-kalahari', 'botswana', 'spans'),
('trans-kalahari', 'south-africa', 'spans'),
('trans-kalahari', 'walvis-bay', 'gateway'),
('trans-kalahari', 'gaborone', 'node'),
('trans-kalahari', 'johannesburg', 'node'),
('libya', 'lyd', 'currency'),
('libya', 'tripoli', 'capital desk'),
('libya', 'ly-energy', 'sector'),
('libya', 'ly-oil', 'sector'),
('zimbabwe', 'zwg', 'currency'),
('zimbabwe', 'harare', 'capital desk'),
('beira-corridor', 'mozambique', 'spans'),
('beira-corridor', 'zimbabwe', 'spans'),
('beira-corridor', 'beira', 'gateway'),
('beira-corridor', 'harare', 'node'),
('mauritius', 'mur', 'currency'),
('mauritius', 'port-louis', 'capital desk'),
('mauritius', 'mu-finance', 'sector'),
('mauritius', 'mu-services', 'sector'),
('djibouti', 'djf', 'currency'),
('djibouti', 'djibouti-city', 'capital desk'),
('djibouti', 'dj-ports', 'sector'),
('djibouti', 'dj-logistics', 'sector'),
('gabon', 'xaf-ga', 'currency'),
('gabon', 'libreville', 'capital desk'),
('gabon', 'ga-oil', 'sector'),
('gabon', 'ga-timber', 'sector'),
('malawi', 'mwk', 'currency'),
('malawi', 'lilongwe', 'capital desk'),
('malawi', 'mw-agriculture', 'sector'),
('benin', 'xof-bj', 'currency'),
('benin', 'cotonou', 'commercial desk'),
('benin', 'bj-agriculture', 'sector'),
('benin', 'bj-ports', 'sector'),
('togo', 'xof-tg', 'currency'),
('togo', 'lome', 'capital desk'),
('togo', 'tg-ports', 'sector'),
('mali', 'xof-ml', 'currency'),
('mali', 'bamako', 'capital desk'),
('mali', 'ml-gold', 'sector'),
('mali', 'ml-agriculture', 'sector'),
('niger', 'xof-ne', 'currency'),
('niger', 'niamey', 'capital desk'),
('niger', 'ne-uranium', 'sector'),
('burkina-faso', 'xof-bf', 'currency'),
('burkina-faso', 'ouagadougou', 'capital desk'),
('burkina-faso', 'bf-gold', 'sector'),
('burkina-faso', 'bf-agriculture', 'sector'),
('guinea', 'gnf', 'currency'),
('guinea', 'conakry', 'capital desk'),
('guinea', 'gn-mining', 'sector'),
('liberia', 'lrd', 'currency'),
('liberia', 'monrovia', 'capital desk'),
('liberia', 'lr-mining', 'sector'),
('sierra-leone', 'sle', 'currency'),
('sierra-leone', 'freetown', 'capital desk'),
('sierra-leone', 'sl-mining', 'sector'),
('mauritania', 'mru', 'currency'),
('mauritania', 'nouakchott', 'capital desk'),
('mauritania', 'mr-mining', 'sector'),
('gambia', 'gmd', 'currency'),
('gambia', 'banjul', 'capital desk'),
('gambia', 'gm-agriculture', 'sector'),
('chad', 'xaf-td', 'currency'),
('chad', 'ndjamena', 'capital desk'),
('chad', 'td-oil', 'sector'),
('madagascar', 'mga', 'currency'),
('madagascar', 'antananarivo', 'capital desk'),
('madagascar', 'mg-agriculture', 'sector'),
('congo', 'xaf-cg', 'currency'),
('congo', 'brazzaville', 'capital desk'),
('congo', 'cg-oil', 'sector'),
('burundi', 'bif', 'currency'),
('burundi', 'bujumbura', 'capital desk'),
('burundi', 'bi-agriculture', 'sector'),
('central-african-republic', 'xaf-cf', 'currency'),
('central-african-republic', 'bangui', 'capital desk'),
('central-african-republic', 'cf-mining', 'sector'),
('equatorial-guinea', 'xaf-gq', 'currency'),
('equatorial-guinea', 'malabo', 'capital desk'),
('equatorial-guinea', 'gq-energy', 'sector'),
('dr-congo', 'cdf', 'currency'),
('dr-congo', 'kinshasa', 'capital desk'),
('dr-congo', 'cd-mining', 'sector'),
('dr-congo', 'cd-infrastructure', 'sector'),
('sao-tome-and-principe', 'stn', 'currency'),
('sao-tome-and-principe', 'sao-tome', 'capital desk'),
('sao-tome-and-principe', 'st-agriculture', 'sector'),
('south-sudan', 'ssp', 'currency'),
('south-sudan', 'juba', 'capital desk'),
('south-sudan', 'ss-energy', 'sector'),
('sudan', 'sdg', 'currency'),
('sudan', 'khartoum', 'capital desk'),
('sudan', 'sd-agriculture', 'sector'),
('eritrea', 'ern', 'currency'),
('eritrea', 'asmara', 'capital desk'),
('eritrea', 'er-mining', 'sector'),
('somalia', 'sos', 'currency'),
('somalia', 'mogadishu', 'capital desk'),
('somalia', 'so-livestock', 'sector'),
('somalia', 'so-remittances', 'sector'),
('cabo-verde', 'cve', 'currency'),
('cabo-verde', 'praia', 'capital desk'),
('cabo-verde', 'cv-tourism', 'sector'),
('cabo-verde', 'cv-services', 'sector'),
('guinea-bissau', 'xof-gw', 'currency'),
('guinea-bissau', 'bissau', 'capital desk'),
('guinea-bissau', 'gw-agriculture', 'sector'),
('comoros', 'kmf', 'currency'),
('comoros', 'moroni', 'capital desk'),
('comoros', 'km-agriculture', 'sector'),
('eswatini', 'szl', 'currency'),
('eswatini', 'mbabane', 'capital desk'),
('eswatini', 'sz-agriculture', 'sector'),
('lesotho', 'lsl', 'currency'),
('lesotho', 'maseru', 'capital desk'),
('lesotho', 'ls-water', 'sector'),
('lesotho', 'ls-apparel', 'sector'),
('seychelles', 'scr', 'currency'),
('seychelles', 'victoria', 'capital desk'),
('seychelles', 'sc-tourism', 'sector'),
('seychelles', 'sc-finance', 'sector'),
('abidjan-lagos', 'cote-divoire', 'spans'),
('abidjan-lagos', 'ghana', 'spans'),
('abidjan-lagos', 'togo', 'spans'),
('abidjan-lagos', 'benin', 'spans'),
('abidjan-lagos', 'nigeria', 'spans'),
('abidjan-lagos', 'abidjan', 'port'),
('abidjan-lagos', 'tema', 'port'),
('abidjan-lagos', 'lome', 'port'),
('abidjan-lagos', 'cotonou', 'port'),
('abidjan-lagos', 'lagos', 'port'),
('nacala-corridor', 'mozambique', 'spans'),
('nacala-corridor', 'malawi', 'spans'),
('nacala-corridor', 'zambia', 'spans'),
('nacala-corridor', 'nacala', 'port'),
('nacala-corridor', 'lilongwe', 'city'),
('nacala-corridor', 'lusaka', 'city'),
('lapsset', 'kenya', 'spans'),
('lapsset', 'south-sudan', 'spans'),
('lapsset', 'ethiopia', 'spans'),
('lapsset', 'lamu', 'port'),
('lapsset', 'juba', 'city'),
('lapsset', 'addis-ababa', 'city'),
('north-south-corridor', 'south-africa', 'spans'),
('north-south-corridor', 'zimbabwe', 'spans'),
('north-south-corridor', 'zambia', 'spans'),
('north-south-corridor', 'tanzania', 'spans'),
('north-south-corridor', 'durban', 'port'),
('north-south-corridor', 'harare', 'city'),
('north-south-corridor', 'lusaka', 'city'),
('north-south-corridor', 'dar-es-salaam', 'port'),
('douala-ndjamena', 'cameroon', 'spans'),
('douala-ndjamena', 'chad', 'spans'),
('douala-ndjamena', 'douala', 'port'),
('douala-ndjamena', 'ndjamena', 'city'),
('walvis-ndola', 'namibia', 'spans'),
('walvis-ndola', 'zambia', 'spans'),
('walvis-ndola', 'walvis-bay', 'port'),
('walvis-ndola', 'lusaka', 'city'),
('walvis-ndola', 'ndola', 'city'),
('djibouti-addis', 'djibouti', 'spans'),
('djibouti-addis', 'ethiopia', 'spans'),
('djibouti-addis', 'djibouti-city', 'port'),
('djibouti-addis', 'addis-ababa', 'city'),
('dakar-bamako', 'senegal', 'spans'),
('dakar-bamako', 'mali', 'spans'),
('dakar-bamako', 'dakar', 'port'),
('dakar-bamako', 'bamako', 'city'),
('cotonou-niamey', 'benin', 'spans'),
('cotonou-niamey', 'niger', 'spans'),
('cotonou-niamey', 'cotonou', 'port'),
('cotonou-niamey', 'niamey', 'city'),
('lome-ouagadougou', 'togo', 'spans'),
('lome-ouagadougou', 'burkina-faso', 'spans'),
('lome-ouagadougou', 'lome', 'port'),
('lome-ouagadougou', 'ouagadougou', 'city'),
('abidjan-ouagadougou', 'cote-divoire', 'spans'),
('abidjan-ouagadougou', 'burkina-faso', 'spans'),
('abidjan-ouagadougou', 'abidjan', 'port'),
('abidjan-ouagadougou', 'ouagadougou', 'city'),
('conakry-bamako', 'guinea', 'spans'),
('conakry-bamako', 'mali', 'spans'),
('conakry-bamako', 'conakry', 'port'),
('conakry-bamako', 'bamako', 'city'),
('pointe-noire-brazzaville', 'congo', 'spans'),
('pointe-noire-brazzaville', 'pointe-noire', 'port'),
('pointe-noire-brazzaville', 'brazzaville', 'city'),
('tazara', 'tanzania', 'spans'),
('tazara', 'zambia', 'spans'),
('tazara', 'dar-es-salaam', 'port'),
('tazara', 'lusaka', 'city'),
('douala-bangui', 'cameroon', 'spans'),
('douala-bangui', 'central-african-republic', 'spans'),
('douala-bangui', 'douala', 'port'),
('douala-bangui', 'bangui', 'city'),
('tema-ouagadougou', 'ghana', 'spans'),
('tema-ouagadougou', 'burkina-faso', 'spans'),
('tema-ouagadougou', 'tema', 'port'),
('tema-ouagadougou', 'ouagadougou', 'city'),
('abidjan-bamako', 'cote-divoire', 'spans'),
('abidjan-bamako', 'mali', 'spans'),
('abidjan-bamako', 'abidjan', 'port'),
('abidjan-bamako', 'bamako', 'city'),
('lome-niamey', 'togo', 'spans'),
('lome-niamey', 'niger', 'spans'),
('lome-niamey', 'lome', 'port'),
('lome-niamey', 'niamey', 'city'),
('nouakchott-dakar', 'mauritania', 'spans'),
('nouakchott-dakar', 'senegal', 'spans'),
('nouakchott-dakar', 'nouakchott', 'city'),
('nouakchott-dakar', 'dakar', 'port'),
('lagos-niamey', 'nigeria', 'spans'),
('lagos-niamey', 'niger', 'spans'),
('lagos-niamey', 'lagos', 'port'),
('lagos-niamey', 'niamey', 'city'),
('matadi-kinshasa', 'dr-congo', 'spans'),
('matadi-kinshasa', 'matadi', 'port'),
('matadi-kinshasa', 'kinshasa', 'city'),
('berbera-addis', 'somalia', 'spans'),
('berbera-addis', 'ethiopia', 'spans'),
('berbera-addis', 'berbera', 'port'),
('berbera-addis', 'addis-ababa', 'city'),
('cape-town-johannesburg', 'south-africa', 'spans'),
('cape-town-johannesburg', 'cape-town', 'port'),
('cape-town-johannesburg', 'johannesburg', 'city'),
('alexandria-cairo', 'egypt', 'spans'),
('alexandria-cairo', 'alexandria', 'port'),
('alexandria-cairo', 'cairo', 'city'),
('port-said-cairo', 'egypt', 'spans'),
('port-said-cairo', 'port-said', 'port'),
('port-said-cairo', 'cairo', 'city'),
('banjul-dakar', 'gambia', 'spans'),
('banjul-dakar', 'senegal', 'spans'),
('banjul-dakar', 'banjul', 'city'),
('banjul-dakar', 'dakar', 'port'),
('freetown-monrovia', 'sierra-leone', 'spans'),
('freetown-monrovia', 'liberia', 'spans'),
('freetown-monrovia', 'freetown', 'port'),
('freetown-monrovia', 'monrovia', 'city'),
('luanda-lobito', 'angola', 'spans'),
('luanda-lobito', 'luanda', 'city'),
('luanda-lobito', 'lobito', 'port'),
('port-sudan-khartoum', 'sudan', 'spans'),
('port-sudan-khartoum', 'port-sudan', 'port'),
('port-sudan-khartoum', 'khartoum', 'city'),
('toamasina-antananarivo', 'madagascar', 'spans'),
('toamasina-antananarivo', 'toamasina', 'port'),
('toamasina-antananarivo', 'antananarivo', 'city'),
('mbabane-maputo', 'eswatini', 'spans'),
('mbabane-maputo', 'mozambique', 'spans'),
('mbabane-maputo', 'mbabane', 'city'),
('mbabane-maputo', 'maputo', 'port'),
('maseru-johannesburg', 'lesotho', 'spans'),
('maseru-johannesburg', 'south-africa', 'spans'),
('maseru-johannesburg', 'maseru', 'city'),
('maseru-johannesburg', 'johannesburg', 'city'),
('bissau-dakar', 'guinea-bissau', 'spans'),
('bissau-dakar', 'senegal', 'spans'),
('bissau-dakar', 'bissau', 'city'),
('bissau-dakar', 'dakar', 'port'),
('mogadishu-berbera', 'somalia', 'spans'),
('mogadishu-berbera', 'mogadishu', 'city'),
('mogadishu-berbera', 'berbera', 'port'),
('accra-tema', 'ghana', 'spans'),
('accra-tema', 'accra', 'city'),
('accra-tema', 'tema', 'port'),
('abuja-lagos', 'nigeria', 'spans'),
('abuja-lagos', 'abuja', 'city'),
('abuja-lagos', 'lagos', 'port'),
('douala-yaounde', 'cameroon', 'spans'),
('douala-yaounde', 'douala', 'port'),
('douala-yaounde', 'yaounde', 'city'),
('massawa-asmara', 'eritrea', 'spans'),
('massawa-asmara', 'massawa', 'port'),
('massawa-asmara', 'asmara', 'city'),
('tangier-casablanca', 'morocco', 'spans'),
('tangier-casablanca', 'tangier', 'port'),
('tangier-casablanca', 'casablanca', 'city'),
('tunis-sfax', 'tunisia', 'spans'),
('tunis-sfax', 'tunis', 'city'),
('tunis-sfax', 'sfax', 'port'),
('algiers-oran', 'algeria', 'spans'),
('algiers-oran', 'algiers', 'city'),
('algiers-oran', 'oran', 'port'),
('tripoli-benghazi', 'libya', 'spans'),
('tripoli-benghazi', 'tripoli', 'city'),
('tripoli-benghazi', 'benghazi', 'port'),
('libreville-port-gentil', 'gabon', 'spans'),
('libreville-port-gentil', 'libreville', 'city'),
('libreville-port-gentil', 'port-gentil', 'port'),
('malabo-bata', 'equatorial-guinea', 'spans'),
('malabo-bata', 'malabo', 'city'),
('malabo-bata', 'bata', 'port'),
('nouakchott-nouadhibou', 'mauritania', 'spans'),
('nouakchott-nouadhibou', 'nouakchott', 'city'),
('nouakchott-nouadhibou', 'nouadhibou', 'port'),
('lusaka-ndola', 'zambia', 'spans'),
('lusaka-ndola', 'lusaka', 'city'),
('lusaka-ndola', 'ndola', 'city'),
('beira-lilongwe', 'mozambique', 'spans'),
('beira-lilongwe', 'malawi', 'spans'),
('beira-lilongwe', 'beira', 'port'),
('beira-lilongwe', 'lilongwe', 'city'),
('harare-bulawayo', 'zimbabwe', 'spans'),
('harare-bulawayo', 'harare', 'city'),
('harare-bulawayo', 'bulawayo', 'city'),
('accra-kumasi', 'ghana', 'spans'),
('accra-kumasi', 'accra', 'city'),
('accra-kumasi', 'kumasi', 'city'),
('brazzaville-kinshasa', 'congo', 'spans'),
('brazzaville-kinshasa', 'dr-congo', 'spans'),
('brazzaville-kinshasa', 'brazzaville', 'city'),
('brazzaville-kinshasa', 'kinshasa', 'city'),
('gaborone-francistown', 'botswana', 'spans'),
('gaborone-francistown', 'gaborone', 'city'),
('gaborone-francistown', 'francistown', 'city'),
('windhoek-walvis-bay', 'namibia', 'spans'),
('windhoek-walvis-bay', 'windhoek', 'city'),
('windhoek-walvis-bay', 'walvis-bay', 'port'),
('mombasa-nairobi', 'kenya', 'spans'),
('mombasa-nairobi', 'mombasa', 'port'),
('mombasa-nairobi', 'nairobi', 'city'),
('dar-es-salaam-dodoma', 'tanzania', 'spans'),
('dar-es-salaam-dodoma', 'dar-es-salaam', 'port'),
('dar-es-salaam-dodoma', 'dodoma', 'city'),
('kano-lagos', 'nigeria', 'spans'),
('kano-lagos', 'kano', 'city'),
('kano-lagos', 'lagos', 'port'),
('blantyre-lilongwe', 'malawi', 'spans'),
('blantyre-lilongwe', 'blantyre', 'city'),
('blantyre-lilongwe', 'lilongwe', 'city'),
('cairo-aswan', 'egypt', 'spans'),
('cairo-aswan', 'cairo', 'city'),
('cairo-aswan', 'aswan', 'city'),
('casablanca-marrakech', 'morocco', 'spans'),
('casablanca-marrakech', 'casablanca', 'city'),
('casablanca-marrakech', 'marrakech', 'city'),
('durban-johannesburg', 'south-africa', 'spans'),
('durban-johannesburg', 'durban', 'port'),
('durban-johannesburg', 'johannesburg', 'city'),
('kampala-kigali', 'uganda', 'spans'),
('kampala-kigali', 'rwanda', 'spans'),
('kampala-kigali', 'kampala', 'city'),
('kampala-kigali', 'kigali', 'city'),
('juba-kampala', 'south-sudan', 'spans'),
('juba-kampala', 'uganda', 'spans'),
('juba-kampala', 'juba', 'city'),
('juba-kampala', 'kampala', 'city'),
('ouagadougou-niamey', 'burkina-faso', 'spans'),
('ouagadougou-niamey', 'niger', 'spans'),
('ouagadougou-niamey', 'ouagadougou', 'city'),
('ouagadougou-niamey', 'niamey', 'city'),
('addis-ababa-nairobi', 'ethiopia', 'spans'),
('addis-ababa-nairobi', 'kenya', 'spans'),
('addis-ababa-nairobi', 'addis-ababa', 'city'),
('addis-ababa-nairobi', 'nairobi', 'city'),
('bamako-ouagadougou', 'mali', 'spans'),
('bamako-ouagadougou', 'burkina-faso', 'spans'),
('bamako-ouagadougou', 'bamako', 'city'),
('bamako-ouagadougou', 'ouagadougou', 'city'),
('niamey-kano', 'niger', 'spans'),
('niamey-kano', 'nigeria', 'spans'),
('niamey-kano', 'niamey', 'city'),
('niamey-kano', 'kano', 'city'),
('algiers-constantine', 'algeria', 'spans'),
('algiers-constantine', 'algiers', 'city'),
('algiers-constantine', 'constantine', 'city'),
('accra-takoradi', 'ghana', 'spans'),
('accra-takoradi', 'accra', 'city'),
('accra-takoradi', 'takoradi', 'port'),
('kigali-bujumbura', 'rwanda', 'spans'),
('kigali-bujumbura', 'burundi', 'spans'),
('kigali-bujumbura', 'kigali', 'city'),
('kigali-bujumbura', 'bujumbura', 'city'),
('lusaka-harare', 'zambia', 'spans'),
('lusaka-harare', 'zimbabwe', 'spans'),
('lusaka-harare', 'lusaka', 'city'),
('lusaka-harare', 'harare', 'city'),
('lagos-port-harcourt', 'nigeria', 'spans'),
('lagos-port-harcourt', 'lagos', 'port'),
('lagos-port-harcourt', 'port-harcourt', 'port'),
('nairobi-kisumu', 'kenya', 'spans'),
('nairobi-kisumu', 'nairobi', 'city'),
('nairobi-kisumu', 'kisumu', 'city'),
('abidjan-san-pedro', 'cote-divoire', 'spans'),
('abidjan-san-pedro', 'abidjan', 'port'),
('abidjan-san-pedro', 'san-pedro', 'port'),
('beira-tete', 'mozambique', 'spans'),
('beira-tete', 'beira', 'port'),
('beira-tete', 'tete', 'city'),
('monrovia-buchanan', 'liberia', 'spans'),
('monrovia-buchanan', 'monrovia', 'city'),
('monrovia-buchanan', 'buchanan', 'port'),
('casablanca-rabat', 'morocco', 'spans'),
('casablanca-rabat', 'casablanca', 'city'),
('casablanca-rabat', 'rabat', 'city'),
('johannesburg-pretoria', 'south-africa', 'spans'),
('johannesburg-pretoria', 'johannesburg', 'city'),
('johannesburg-pretoria', 'pretoria', 'city'),
('dakar-saint-louis', 'senegal', 'spans'),
('dakar-saint-louis', 'dakar', 'city'),
('dakar-saint-louis', 'saint-louis', 'city'),
('accra-tamale', 'ghana', 'spans'),
('accra-tamale', 'accra', 'city'),
('accra-tamale', 'tamale', 'city'),
('luanda-namibe', 'angola', 'spans'),
('luanda-namibe', 'luanda', 'city'),
('luanda-namibe', 'namibe', 'port'),
('kinshasa-lubumbashi', 'dr-congo', 'spans'),
('kinshasa-lubumbashi', 'kinshasa', 'city'),
('kinshasa-lubumbashi', 'lubumbashi', 'city'),
('algiers-annaba', 'algeria', 'spans'),
('algiers-annaba', 'algiers', 'city'),
('algiers-annaba', 'annaba', 'port'),
('lagos-calabar', 'nigeria', 'spans'),
('lagos-calabar', 'lagos', 'port'),
('lagos-calabar', 'calabar', 'port'),
('kampala-entebbe', 'uganda', 'spans'),
('kampala-entebbe', 'kampala', 'city'),
('kampala-entebbe', 'entebbe', 'city'),
('dar-es-salaam-mwanza', 'tanzania', 'spans'),
('dar-es-salaam-mwanza', 'dar-es-salaam', 'port'),
('dar-es-salaam-mwanza', 'mwanza', 'city'),
('cotonou-porto-novo', 'benin', 'spans'),
('cotonou-porto-novo', 'cotonou', 'city'),
('cotonou-porto-novo', 'porto-novo', 'city'),
('lome-kara', 'togo', 'spans'),
('lome-kara', 'lome', 'city'),
('lome-kara', 'kara', 'city'),
('tunis-sousse', 'tunisia', 'spans'),
('tunis-sousse', 'tunis', 'city'),
('tunis-sousse', 'sousse', 'port'),
('cairo-luxor', 'egypt', 'spans'),
('cairo-luxor', 'cairo', 'city'),
('cairo-luxor', 'luxor', 'city'),
('conakry-kankan', 'guinea', 'spans'),
('conakry-kankan', 'conakry', 'city'),
('conakry-kankan', 'kankan', 'city'),
('libreville-franceville', 'gabon', 'spans'),
('libreville-franceville', 'libreville', 'city'),
('libreville-franceville', 'franceville', 'city'),
('nairobi-nakuru', 'kenya', 'spans'),
('nairobi-nakuru', 'nairobi', 'city'),
('nairobi-nakuru', 'nakuru', 'city'),
('addis-ababa-dire-dawa', 'ethiopia', 'spans'),
('addis-ababa-dire-dawa', 'addis-ababa', 'city'),
('addis-ababa-dire-dawa', 'dire-dawa', 'city'),
('abidjan-bouake', 'cote-divoire', 'spans'),
('abidjan-bouake', 'abidjan', 'city'),
('abidjan-bouake', 'bouake', 'city'),
('lagos-ibadan', 'nigeria', 'spans'),
('lagos-ibadan', 'lagos', 'city'),
('lagos-ibadan', 'ibadan', 'city'),
('johannesburg-bloemfontein', 'south-africa', 'spans'),
('johannesburg-bloemfontein', 'johannesburg', 'city'),
('johannesburg-bloemfontein', 'bloemfontein', 'city'),
('lusaka-livingstone', 'zambia', 'spans'),
('lusaka-livingstone', 'lusaka', 'city'),
('lusaka-livingstone', 'livingstone', 'city'),
('marrakech-agadir', 'morocco', 'spans'),
('marrakech-agadir', 'marrakech', 'city'),
('marrakech-agadir', 'agadir', 'port'),
('kampala-jinja', 'uganda', 'spans'),
('kampala-jinja', 'kampala', 'city'),
('kampala-jinja', 'jinja', 'city'),
('yaounde-garoua', 'cameroon', 'spans'),
('yaounde-garoua', 'yaounde', 'city'),
('yaounde-garoua', 'garoua', 'city'),
('harare-mutare', 'zimbabwe', 'spans'),
('harare-mutare', 'harare', 'city'),
('harare-mutare', 'mutare', 'city'),
('maputo-nampula', 'mozambique', 'spans'),
('maputo-nampula', 'maputo', 'city'),
('maputo-nampula', 'nampula', 'city'),
('accra-cape-coast', 'ghana', 'spans'),
('accra-cape-coast', 'accra', 'city'),
('accra-cape-coast', 'cape-coast', 'city'),
('windhoek-rundu', 'namibia', 'spans'),
('windhoek-rundu', 'windhoek', 'city'),
('windhoek-rundu', 'rundu', 'city'),
('gaborone-maun', 'botswana', 'spans'),
('gaborone-maun', 'gaborone', 'city'),
('gaborone-maun', 'maun', 'city'),
('tripoli-misrata', 'libya', 'spans'),
('tripoli-misrata', 'tripoli', 'city'),
('tripoli-misrata', 'misrata', 'port'),
('oran-constantine', 'algeria', 'spans'),
('oran-constantine', 'oran', 'city'),
('oran-constantine', 'constantine', 'city'),
('blantyre-zomba', 'malawi', 'spans'),
('blantyre-zomba', 'blantyre', 'city'),
('blantyre-zomba', 'zomba', 'city'),
('asmara-keren', 'eritrea', 'spans'),
('asmara-keren', 'asmara', 'city'),
('asmara-keren', 'keren', 'city'),
('luanda-malanje', 'angola', 'spans'),
('luanda-malanje', 'luanda', 'city'),
('luanda-malanje', 'malanje', 'city'),
('antananarivo-fianarantsoa', 'madagascar', 'spans'),
('antananarivo-fianarantsoa', 'antananarivo', 'city'),
('antananarivo-fianarantsoa', 'fianarantsoa', 'city')
) as v(from_slug, to_slug, rel)
join public.entities f on f.slug = v.from_slug
join public.entities t on t.slug = v.to_slug
on conflict (from_entity_id, to_entity_id, rel_type) do nothing;
